<?php
  // ヘッダ表示
  include "../../config.inc.php";
  include "../../lib.inc.php";
  include "../../language.inc.php";

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">予定表</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>連続予定の登録</FONT>";

  include "../../header.inc.php";
  flush();

  if ($login && sizeof($MES)==0) {
    $env_uri = getenv("HTTP_REFERER");
    $user_id        = $login_id;
    $create_user_id = $login_id;

    // 通常時
    $viewsign = $user_viewsign;

    $sql = "select from_h,from_m,to_h,to_m from users where id = '".$login_id."'";
    $res = pg_query($conn,$sql);
    $row = pg_fetch_array($res,0);

    if (empty($from_hour)) {
      if ($row["from_h"] <> ""){
        $from_hour   = $row["from_h"];
        $from_minuts = $row["from_m"];
        $to_hour     = $row["to_h"];;
        $to_minuts   = $row["to_m"];
      } else {
        $from_hour   = 9;
        $from_minuts = 0;
        $to_hour     = -1;
        $to_minuts   = -1;
      }
    }
    if ($ey == "" or $em == "" or $ed == ""){
      $ey = date("Y",time());
      $em = date("m",time());
      $ed = date("d",time());
    }

    if (empty($count))   $count = 4;
    if (empty($note))    $note = "";
    if (empty($pattern)) $pattern = 0;

    // 曜日のセット(初期表示用)
    $weekno = floor((date("j",date2timestamp($ey."-".$em."-".$ed))-1) / 7)+1;
    $weekday = date("w",date2timestamp($ey."-".$em."-".$ed));

    $user_name = get_first("users","name_ryaku","id='".$user_id."'","不明または削除");

    $pagetext .= "
<SCRIPT LANGUAGE=\"JavaScript\">
my = \"$login_id\";
dat_groups = new Array();
";
    $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    $pagetext .= "cnt_groups = ".$cnt_group."\n";
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
        $cnt_entry = pg_num_rows($res_entry);

        if ($res_entry>0) {
          $users_entry = "";
          for ($j=0;$j<$cnt_entry;$j++) {
            $row_entry = pg_fetch_array($res_entry,$j);
            if ($users_entry != "") $users_entry .= ",";
            $users_entry .= $row_entry["user_id"];
          }
        }
        if ($users_entry!="") {
          $pagetext .= "dat_groups[\"".$row_group["id"]."\"] = \"".$users_entry."\";\n";
        }
      }
    }

    $pagetext .= "
dat_users = new Array();
";
    $all_users = "";

    $sql_user = "SELECT id,name FROM users ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);
    $pagetext .= "cnt_users = ".$cnt_user."\n";
    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        $pagetext .= "dat_users[\"".$row_user["id"]."\"] = \"".$row_user["name"]."\";\n";
        if ($i!=0) $all_users .= ",";
        $all_users .= $row_user["id"];
      }
    }

    $pagetext .= "dat_groups[\"all\"] = \"".$all_users."\";\n";

    $pagetext .= "
<!--
function delwin(seqno,id,date) {
  if(confirm('この予定を削除しますか。\\n注:一度削除した予定を戻すことはできません。')) {
    window.location.href = '../del/?seqno='+seqno+'&y=$y&m=$m&d=$d';
  }
}

function selectfromhour(t) {
  if (t.from_hour[0].selected) {
    t.from_minuts[0].selected = true;
  } else {
    if (t.from_minuts[0].selected == true) t.from_minuts[1].selected = true;
  }
}

function selecttohour(t) {
  if (t.to_hour[0].selected) {
    t.to_minuts[0].selected = true;
  } else {
    if (t.to_minuts[0].selected == true) t.to_minuts[1].selected = true;
  }
}

function showweekday(t) {
  document.images['weekno'].src = '/image/mw-.gif';
  document.images['weekday'].src = '/image/w-.gif';

  m = t.em.options[t.em.selectedIndex].value;
  d = t.ed.options[t.ed.selectedIndex].value;
  if (d==99) {
    d = t.ed.options[t.ed.selectedIndex-1].value;
  }

  if (!(isNaN(t.ey.value)) && (t.ey.value>0) && !(isNaN(m)) && (m>0) && !(isNaN(d)) && (d>0)) {
    w = new Date();
    s = new Date();
    y = parseInt(t.ey.value);
    w.setYear(y); w.setMonth(m-1); w.setDate(d);
    s.setYear(y); s.setMonth(m-1); s.setDate(1);

    mw = Math.floor((d-1)/7)+1;
    document.images['weekno'].src = '/image/mw'+ mw +'.gif';
    document.images['weekday'].src = '/image/w'+ w.getDay() +'.gif';
  }
}

function selectGroup(t) {
  group_id = t.groups[t.groups.selectedIndex].value;
  id_tos = new Array();

  t.users.length = 0;

  if (group_id == '') {
    id_tos = dat_groups['all'].split(',');
  } else {
    if (dat_groups[group_id] != null) {
      id_tos = dat_groups[group_id].split(',');
    }
  }
  if (id_tos.length>0) {
    c = 0;
    for (i=0;i<id_tos.length;i++) {
      if (id_tos[i] != my) {
        t.users.length = t.users.length + 1;
        t.users.options[c].value = id_tos[i];
        t.users.options[c].text  = dat_users[id_tos[i]];
        c++;
      }
    }
  }
}

function clearAllUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  o.length = 0;
  t.id_to.value = '';
}

function selectAllUser(t) {
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      t.users.options[i].selected = true;
    }
  }
  t.allcheck.checked = false;
}

function addUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }
  var o = t.elements[p];

  s = t.id_to.value;
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      if (t.users.options[i].selected) {
        t.users.options[i].selected = false;
        var id = t.users.options[i].value;
        var c = false;
        for(j=0;j<o.length;j++) {
          if (o.options[j].value == id) {
            c = true;
            break;
          }
        }
        if (!c) {
          if (o.length>0) s = s + ',';
          o.length = o.length + 1;
          o.options[o.length-1].value = id;
          o.options[o.length-1].text = dat_users[id];
          s = s + id;
        }
      }
    }
  }
  t.id_to.value = s;
}

function removeUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  var val = new Array();
  var txt = new Array();
  var c = 0;
  
  if (o.length>0) {
    for (i=0;i<o.length;i++) {
      if (!o.options[i].selected) {
        val[c] = o.options[i].value;
        txt[c] = o.options[i].text;
        c++;
      }
    }

    o.length = 0;
    s = '';
    if (c>0) {
      o.length = c;
      for (i=0;i<c;i++) {
        if (i>0) s = s + ',';
        o.options[i].value = val[i];
        o.options[i].text  = txt[i];
        s = s + val[i];
      }
    }
    t.id_to.value = s;
  }
}
//-->
</SCRIPT>
";

    $pagetext .= "<BR>\n";
    $pagetext .= "<TABLE WIDTH=100% HEIGHT=445 CELLPADDING=0 CELLSPACING=0><TR><TD ALIGN=CENTER VALIGN=TOP>\n";
    $pagetext .= "<FORM ACTION=\"./conf.phtml\" METHOD=POST>\n";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=0 ALIGN=CENTER>\n";
    $pagetext .= "<TR><TD ALIGN=CENTER COLSPAN=2>";
    $pagetext .= "繰り返し回数・内容、各項目を入力してから、登録ボタンを押してください";
    $pagetext .= "</TD></TR>";
    $pagetext .= "<TR><TD ALIGN=RIGHT>\n";
    $pagetext .= "<A HREF=\"#\" ONCLICK=\"history.back()\"><IMG SRC=\"../../image/entrysadd.gif\" WIDTH=10 HEIGHT=9 BORDER=0 ALT=\"予定表示へ\">通常の予定入力へ戻る</A>&nbsp;\n";
    $pagetext .= "</TD></TR>\n";
    $pagetext .= "
<TR>
<TD VALIGN=TOP ALIGN=CENTER>
<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 BGCOLOR=#999999>
<INPUT TYPE=HIDDEN NAME=\"seqno\"   value=\"$s\">
<INPUT TYPE=HIDDEN NAME=\"user_id\" value=\"$user_id\">

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;起算日&nbsp;</TD>
<TD ALIGN=LEFT BGCOLOR=".$td_back." COLSPAN=3>
<INPUT TYPE=TEXT NAME=\"ey\" VALUE=\"$ey\" SIZE=5 MAXLENGTH=4 ONCHANGE=\"showweekday(this.form)\" style=\"ime-mode:disabled\">年
<SELECT NAME=\"em\" ONCHANGE=\"showweekday(this.form)\" style=\"ime-mode:disabled\">
";
    for ($i=1;$i<=12;$i++){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i == $em) { $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i) == 1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "</SELECT>月";

    $pagetext .= "<SELECT NAME=\"ed\" ONCHANGE=\"showweekday(this.form)\" style=\"ime-mode:disabled\">";
    for ($i=1;$i<=31;$i++){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i == $ed){ $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i) == 1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "<OPTION VALUE=99>月末</OPTION>\n";

    $pagetext .= "</SELECT>日&nbsp;<IMG NAME=\"weekno\" SRC=\"/image/mw".$weekno.".gif\" style=\"vertical-align:text-top\" ALT=\"第\"$weekno WIDTH=24 HEIGHT=13><IMG NAME=\"weekday\" SRC=\"/image/w".$weekday.".gif\" style=\"vertical-align:text-top\" WIDTH=35 HEIGHT=13
</TD>
</TR>
";
    $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;時刻指定&nbsp;</TD>
<TD ALIGN=LEFT BGCOLOR=".$td_back." COLSPAN=3>
<SELECT NAME=\"from_hour\" ONCHANGE=\"selectfromhour(this.form)\" style=\"ime-mode:disabled\">";
    $pagetext .= "<OPTION VALUE=\"-1\"";
    if ($from_hour == -1){ $pagetext .= " SELECTED"; }
    $pagetext .= ">--</OPTION>\n";
    for ($i=0;$i<=23;$i++){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i == $from_hour){ $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i) == 1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "</SELECT>：<SELECT NAME=\"from_minuts\" style=\"ime-mode:disabled\">\n";

    $pagetext .= "<OPTION VALUE=\"-1\"";
    if ($from_minuts == -1){ $pagetext .= " SELECTED"; }
    $pagetext .= ">--</OPTION>\n";
    for ($i=0;$i<60;$i=$i+$interval){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i <= $from_minuts){ $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i) == 1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "</SELECT>&nbsp;〜&nbsp;<SELECT NAME=\"to_hour\" ONCHANGE=\"selecttohour(this.form)\" style=\"ime-mode:disabled\">\n";

    $pagetext .= "<OPTION VALUE=\"-1\"";
    if ($to_hour == -1){ $pagetext .= " SELECTED"; }
    $pagetext .= ">--</OPTION>\n";

    for ($i=0;$i<=23;$i++){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i == $to_hour){ $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i) == 1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "</SELECT>：<SELECT name=\"to_minuts\" style=\"ime-mode:disabled\">\n";

    $pagetext .= "<OPTION VALUE=\"-1\"";
    if ($to_minuts==-1){ $pagetext .= " SELECTED"; }
    $pagetext .= ">--</OPTION>\n";

    for ($i=0;$i<60;$i=$i+$interval){
      $pagetext .= "<OPTION VALUE=\"$i\"";
      if ($i <= $to_minuts){ $pagetext .= " SELECTED"; }
      $pagetext .= ">";
      if (strlen($i)==1) $pagetext .= "0";
      $pagetext .= $i."</OPTION>\n";
    }
    $pagetext .= "</SELECT>
</TD>
</TR>
";
    $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;繰り返し&nbsp;</TD>
<TD ALIGN=LEFT WIDTH=44% NOWRAP BGCOLOR=".$td_back.">";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"pattern\" VALUE=0";
    if ($pattern==0) $pagetext .= " checked";
    $pagetext .= ">毎日(連続)<BR>";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"pattern\" VALUE=1";
    if ($pattern==1) $pagetext .= " checked";
    $pagetext .= ">毎週Ｘ曜<BR>";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"pattern\" VALUE=2";
    if ($pattern==2) $pagetext .= " checked";
    $pagetext .= ">毎月第ｘＸ曜<BR>";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"pattern\" VALUE=3";
    if ($pattern==3) $pagetext .= " checked";
    $pagetext .= ">毎月同日";
    $pagetext .= "
</TD>";

    $pagetext .= "
<TD ALIGN=RIGHT WIDTH=12% NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;回数&nbsp;</TD>
<TD ALIGN=LEFT WIDTH=44% NOWRAP BGCOLOR=".$td_back.">
<INPUT TYPE=TEXT NAME=\"count\" SIZE=4 MAXLENGTH=3 VALUE=\"$count\" style=\"ime-mode:disabled\">回<BR>
<FONT COLOR=#555555 STYLE=\"font-size:8pt\">指定日を含みます<BR>最大24回まで入力可能<BR>
</TD>
</TR>
";

    // 作業分類
    $sql_kind = "SELECT * FROM schedule_kind ORDER BY seqno";
    $res_kind = pg_query($conn,$sql_kind);
    $cnt_kind = pg_num_rows($res_kind);
    if ($cnt_kind>0) {
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;作業分類&nbsp;</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT COLSPAN=3 BGCOLOR=$td_back>\n";
      $pagetext .= "<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0><TR><TD NOWRAP>\n";
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"kind\" VALUE=\"\"";
      if ($kind == "") { $pagetext .= " CHECKED"; }
      $pagetext .= ">なし&nbsp;\n";
      $pagetext .= "</TD>";
      $c = 1;
      for ($i=0;$i<$cnt_kind;$i++){
        $row_kind = pg_fetch_array($res_kind,$i);
        $pagetext .= "<TD NOWRAP>";
        $pagetext .= "<TABLE WIDTH=100% BORDER=0 CELLSPACING=0 CELLPADDING=0><TR>\n";
        $pagetext .= "<TD NOWRAP>\n";
        $pagetext .= "<INPUT TYPE=RADIO NAME=\"kind\" VALUE=\"".$row_kind["key"]."\"";
        if ($row_kind["key"] == $kind) { $pagetext .= " CHECKED"; }
        $pagetext .= ">".$row_kind["value"]."&nbsp;";
        $pagetext .= "</TD>\n";
        $pagetext .= "<TD ALIGN=RIGHT>\n";
        if ($row_kind["graphcolor"]!="") { $gcolor = $row_kind["graphcolor"]; } else { $gcolor = $sch_back; }
        $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=1 BGCOLOR=#000000><TR><TD BGCOLOR=$gcolor>";
        $pagetext .= "<IMG SRC=\"../../image/null.gif\" WIDTH=16 HEIGHT=16 ALT=\"".$row_kind["value"]."カラー\">";
        $pagetext .= "</TD></TR></TABLE>";
        $pagetext .= "</TR></TABLE>";
        $pagetext .= "</TD>";
        $c++;
        if ($c>3) {
          $pagetext .= "</TR>\n";
          $pagetext .= "<TR>\n";
          $c = 0;
        }
      }
      $pagetext .= "</TR>\n";
      $pagetext .= "</TABLE>\n";
      $pagetext .= "</TD></TR>\n";
    }

    $pagetext .= "<TR>";
    $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;内容&nbsp;</TD>";
    $pagetext .= "<TD ALIGN=LEFT BGCOLOR=".$td_back." COLSPAN=3>";
    $pagetext .= "<TEXTAREA NAME=\"note\" COLS=46 ROWS=5 STYLE=\"ime-mode:active\">$note</TEXTAREA>";
    $pagetext .= "<BR>";

    $pagetext .="<IMG SRC=\"../../image/key.gif\" ALIGN=ABSMIDDLE>表示モード:&nbsp;";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"openflag\" VALUE=\"0\"";
    if ($openflag==0) { $pagetext .= " checked";};
    $pagetext .= ">公開\n";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"openflag\" VALUE=\"1\"";
    if ($openflag==1) { $pagetext .= " checked";};
    $pagetext .= " >日時のみ公開\n";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"openflag\" VALUE=\"2\"";
    if ($openflag==2) { $pagetext .= " checked";};
    $pagetext .= ">非公開\n";
    $pagetext .= "</TD></TR>";

    $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=".$td_back_left.">&nbsp;共有&nbsp;</TD>
<TD ALIGN=LEFT BGCOLOR=".$td_back." COLSPAN=3>
";

    // 共有選択
    $pagetext .= "
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=2>
<TR>
<TD COLSPAN=2>&nbsp;</TD>
<TD><SELECT NAME=\"groups\" ONCHANGE=\"selectGroup(this.form)\" STYLE=\"width:120px\">\n";
    $pagetext .= "<OPTION VALUE=\"\" SELECTED>(全て)\n";

    $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
        if (pg_num_rows($res_entry)>0) {
          $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\">".$row_group["name"];
          $pagetext .= "\n";
        }
      }
    }

    $pagetext .= "</SELECT>
</TD>
</TR>

<TR>
<TD VALIGN=TOP><SELECT NAME=\"id_tos[]\" SIZE=8 STYLE=\"width:140px\">\n";
    $id_tos = split(",",$id_to);

    if (sizeof($id_tos)>0) {
      for ($i=0;$i<sizeof($id_tos);$i++) {
        if ($id_tos[$i]!="") {
          $pagetext .= "<OPTION VALUE=\"".$id_tos[$i]."\">";
          $pagetext .= get_first("users","name","id='".$id_tos[$i]."'","");
          $pagetext .= "\n";
        }
      }
    }
    $pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allclear\" VALUE=\"全て消去\" ONCLICK=\"clearAllUser(this.form)\">
</TD>
<TD ALIGN=CENTER VALIGN=MIDDLE>
<INPUT TYPE=BUTTON VALUE=\"&lt; 追加\" ONCLICK=\"addUser(this.form)\"><BR><BR>
<INPUT TYPE=BUTTON VALUE=\"削除 &gt;\" ONCLICK=\"removeUser(this.form)\"><BR><BR><BR>
</TD>
<TD VALIGN=TOP><SELECT NAME=\"users\" MULTIPLE SIZE=8 STYLE=\"width:140px\">
";

    $sql_user = "SELECT id,depa,post,name FROM users ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);

    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        if ($user_id != $row_user["id"]) { //自身を除外
          $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\" ";
          if ($send=="P" && preg_match("/(^|,)".$row_user["id"]."(,|$)/",$senddata)){
            $pagetext .= "selected";
          }
          $pagetext .= ">".$row_user["name"];
          $pagetext .= "</OPTION>\n";
        }
      }
    }
    $pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allcheck\" VALUE=\"全て選択\" ONCLICK=\"selectAllUser(this.form)\">
<INPUT TYPE=HIDDEN NAME=\"id_to\" VALUE=\"$id_to\">
</TD>
</TR>

</TABLE>
";
    $pagetext .= "&nbsp;※<FONT COLOR=#666666 STYLE=\"font-size:85%\">連続予定の登録時には共有者にメールで通知することはできません</FONT>";
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "
<TR BGCOLOR=#CCCCFF>
<TD ALIGN=RIGHT WIDTH=12% NOWRAP>&nbsp;施設予約&nbsp;</TD>
<TD ALIGN=LEFT WIDTH=88% NOWRAP BGCOLOR=#DADAFF COLSPAN=3>
";

    $sql_roomtype = "SELECT * FROM rooms_type ORDER BY seqno";
    $res_roomtype = pg_query($conn,$sql_roomtype);
    $cnt_roomtype = pg_num_rows($res_roomtype);
    if ($cnt_roomtype>0) {
      for ($i=0;$i<$cnt_roomtype;$i++) {
        $row_roomtype = pg_fetch_array($res_roomtype,$i);
        $types[($row_roomtype["seqno"])] = $row_roomtype["name"];
      }
    }
    $pagetext .= "<SELECT NAME=\"room_id\">\n";
    $pagetext .= "<OPTION VALUE=\"\" SELECTED>未選択</OPTION>\n";
    $pagetext .= "<OPTION VALUE=\"\">--------------------</OPTION>\n";
    $b_type = "";
    $sql_room = "SELECT * FROM rooms ORDER BY type,id";
    $res_room = pg_query($conn,$sql_room);
    $cnt_room = pg_num_rows($res_room);
    if ($cnt_room>0) {
      for ($i=0;$i<$cnt_room;$i++) {
        $row_room = pg_fetch_array($res_room,$i);
        $rooms[$i] = array($row_room["id"],$row_room["type"],$row_room["name"]);
        if ($b_type != $row_room["type"]) {
          if (substr($target,0,1)=="t" and substr($target,1)==$row_room["type"]) {
            $pagetext .= "<OPTION VALUE=\"\" SELECTED>【".$types[$row_room["type"]]."】</OPTION>\n";
          } else {
            $pagetext .= "<OPTION VALUE=\"\">【".$types[$row_room["type"]]."】</OPTION>\n";
          }
        }
        $b_type = $row_room["type"];
        if ((substr($target,0,1)=="r" and substr($target,1)==$row_room["id"]) or $room_id==$row_room["id"]) {
          $pagetext .= "<OPTION VALUE=\"".$row_room["id"]."\" SELECTED>・".$row_room["name"]."</OPTION>\n";
        } else {
          $pagetext .= "<OPTION VALUE=\"".$row_room["id"]."\">・".$row_room["name"]."</OPTION>\n";
        }
      }
    }
    $pagetext .= "</SELECT>\n";

    $pagetext .= "
<FONT COLOR=#555555>※ 施設の同時予約ができます</FONT>
</TD></TR>";

    // 利用人数
    if (empty($member_count)) { $member_count = "1"; }
    $pagetext .= "<TR BGCOLOR=#CCCCFF>\n";
    $pagetext .= "<TD ALIGN=RIGHT WIDTH=12% NOWRAP>&nbsp;利用人数&nbsp;</TD>\n";
    $pagetext .= "<TD ALIGN=LEFT WIDTH=88% NOWRAP BGCOLOR=#DADAFF COLSPAN=3>\n";
    $pagetext .= "<INPUT TYPE=TEXT NAME=\"member_count\" SIZE=4 STYLE=\"ime-mode:disabled\" VALUE=\"$member_count\">名\n";
    $pagetext .= "</TD>\n";
    $pagetext .= "</TR>\n";

    $pagetext .= "
</TABLE>

<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR>
<TD><INPUT TYPE=SUBMIT VALUE=\"予定の登録\" style=\"width:120px\"></TD>
</TR></TABLE>

</TD></TR></FORM></TABLE>
</TD></TR></TABLE>
";

  }

  include "../../detail.inc.php";
  include "../../footer.inc.php";
?>
