<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";
  include "../../language.inc.php";

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">住所録</A> &gt; ";
  $linktext .= "<A HREF=\"./search/\" CLASS=\"BAR\">フリーワード検索</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>検索結果</FONT>";
  include "../../header.inc.php";
  flush();

  // エラーチェック
  if ($login==false) {
    $MES[] = "先に、ログインしてください ⇒ <A HREF=\"$toppath/\">ログインページへ</A>";
  } else {
    if (trim($login_id) == "") {
      $MES[] = "ユーザーＩＤが正しくありません";
    } else {
      $sql = "select * from users where id='".$login_id."'";
      print "<!--";
      $res = pg_query($conn, $sql);

      if (pg_num_rows($res)<1) {
        $MES[] = "ユーザーＩＤが正しくありません";
      } else {
        $row = pg_fetch_array($res,0);
      }
      print "-->";
    }
  }

  if (sizeof($MES)>0) {
    // エラー時
    print "<TABLE BORDER=0 WIDTH=100%>\n";
    print "  <TR><TD ALIGN=CENTER>\n";
    print "    <TABLE BORDER=0 HEIGHT=260><TR><TD><FONT COLOR=#FF0000><B>\n";
    // エラーメッセージ出力
    while (list($key,$val)=each($MES)) {
      print "      ".$val."<BR>\n";
    }
    print "    </B></FONT></TD></TR></TABLE>\n";

    print "    <INPUT TYPE=\"BUTTON\" VALUE=\"閉じる\" onClick=\"window.close()\" tabindex=999>\n";
    print "  </TD></TR>\n";
    print "</TABLE>\n";

    include "../../footer.inc.php";
    exit;
  }

#  $kwd = urldecode($kwd);

  // 検索用キーワードへ調整
  $kwd = textsafe($kwd);
  $kwds = $kwd;
  $kwds = mb_convert_kana($kwds, "aKV");
  // 区切り処理
#  $kwds = str_replace("-", " ", $kwds);
#  $kwds = str_replace(",", " ", $kwds);
#  $kwds = str_replace("、", " ", $kwds);
  $kwds = trim($kwds);

  // 通常処理
#  $kwds = mbereg_replace("'","’",$kwds);

  if ($kwds != "") {
//    $kwds = str_replace(" ", "|", $kwds);
    $searchkeys = split(" ",$kwds);
    // 検索
    $sql = "SELECT * FROM address WHERE ";
    $c = 0;
    while (list($seq,$searchkey)=each($searchkeys)) {
      $c++;
      if ($c>1) $sql .= " AND ";
      $searchkey = db_textsafe($searchkey);
      $searchkey_katakana = db_textsafe(mb_convert_kana($searchkey,"CKV","EUC-JP"));
      $searchkey_hiragana = db_textsafe(mb_convert_kana($searchkey,"HcV","EUC-JP"));
      $sql .= "(";
      $sql .= "corp_name ~* '".$searchkey."' or ";
      $sql .= "corp_kana ~* '".$searchkey."' or ";
      $sql .= "corp_kana ~* '".$searchkey_katakana."' or ";
      $sql .= "corp_kana ~* '".$searchkey_hiragana."' or ";
      $sql .= "corp_email ~* '".$searchkey."' or ";
      $sql .= "corp_url ~* '".$searchkey."' or ";
      $sql .= "corp_zip ~* '".$searchkey."' or ";
      $sql .= "corp_state ~* '".$searchkey."' or ";
      $sql .= "corp_city ~* '".$searchkey."' or ";
      $sql .= "corp_street ~* '".$searchkey."' or ";
      $sql .= "corp_build ~* '".$searchkey."' or ";
      $sql .= "corp_tel ~* '".$searchkey."' or ";
      $sql .= "corp_fax ~* '".$searchkey."' or ";
      $sql .= "person_depa ~* '".$searchkey."' or ";
      $sql .= "person_post ~* '".$searchkey."' or ";
      $sql .= "person_name ~* '".$searchkey."' or ";
      $sql .= "person_kana ~* '".$searchkey_katakana."' or ";
      $sql .= "person_kana ~* '".$searchkey_hiragana."' or ";
      $sql .= "person_email ~* '".$searchkey."' or ";
      $sql .= "person_email2 ~* '".$searchkey."' or ";
      $sql .= "person_dialin ~* '".$searchkey."' or ";
      $sql .= "person_handy ~* '".$searchkey."' or ";
      $sql .= "person_zip ~* '".$searchkey."' or ";
      $sql .= "person_state ~* '".$searchkey."' or ";
      $sql .= "person_city ~* '".$searchkey."' or ";
      $sql .= "person_street ~* '".$searchkey."' or ";
      $sql .= "person_build ~* '".$searchkey."' or ";
      $sql .= "person_tel ~* '".$searchkey."' or ";
      $sql .= "person_fax ~* '".$searchkey."' or ";
      $sql .= "comment ~* '".$searchkey."')";
    }
    $sql .= " ORDER BY person_kana,createstamp DESC";
    $res = pg_query($conn,$sql);
    $cnt = pg_num_rows($res);
  } else {
    $cnt = 0;
  }
?>
<BR>

<CENTER>
<TABLE HEIGHT=445>
<TR><TD VALIGN=TOP ALIGN=CENTER>

<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=3 WIDTH=100%>
<TR>
<FORM NAME="search" ACTION="./" METHOD="POST">
<INPUT TYPE=HIDDEN NAME="kwd" VALUE="<? echo $kwd ?>">
<TD>
該当<? echo number_format($cnt) ?>件
<INPUT TYPE=SUBMIT NAME="submit" VALUE="再検索" style="width:80px">
</TD>
</FORM>

<TD DIV ALIGN=RIGHT>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0><TR>
<FORM ACTION="/sendmail/" METHOD=POST>
<INPUT TYPE=HIDDEN NAME="bcc" VALUE="<? 
    $c=0;
    for ($i=0;$i<$cnt;$i++) {
      $row = pg_fetch_array($res,$i);
      $email = "";
      if (empty($row["person_email"]) || trim($row["person_email"])=="") {
        $email = $row["corp_email"];
      } else {
        $email = $row["person_email"];
      }
      if (!empty($email) && trim($email) != "" && $email != "-" && $email != "@") {
        if ($c>0) { print ", "; }
        print $row["person_name"]."<";
        print $email;
        print ">";
        $c++;
      }
    }
?>">
<TD>
<INPUT TYPE=SUBMIT VALUE="一括メール送信" STYLE="width:120px">&nbsp;
</TD>
</FORM>
<FORM ACTION="./csvout.phtml" METHOD=POST>
<INPUT TYPE=HIDDEN NAME="type" VALUE="free">
<INPUT TYPE=HIDDEN NAME="kwd" VALUE="<? echo $kwd ?>">
<INPUT TYPE=HIDDEN NAME="name" VALUE="<? echo $name ?>">
<INPUT TYPE=HIDDEN NAME="corp" VALUE="<? echo $corp ?>">
<INPUT TYPE=HIDDEN NAME="depa" VALUE="<? echo $depa ?>">
<INPUT TYPE=HIDDEN NAME="addr" VALUE="<? echo $addr ?>">
<INPUT TYPE=HIDDEN NAME="tel" VALUE="<? echo $tel ?>">
<INPUT TYPE=HIDDEN NAME="url" VALUE="<? echo $url ?>">
<INPUT TYPE=HIDDEN NAME="comment" VALUE="<? echo $comment ?>">
<INPUT TYPE=HIDDEN NAME="kind_list" VALUE="<? echo $kind_list ?>">
<TD>
<INPUT TYPE=SUBMIT VALUE="CSVファイル出力" STYLE="width:120px">
</TD>
</FORM>
</TR>
</TABLE>
</TD>
</TR>
</TABLE>

<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=3 WIDTH=100%>
<TR BGCOLOR=#999999>
  <TH ALIGN=LEFT NOWRAP><FONT COLOR=#FFFFFF>勤務先・屋号</TH>
  <TH ALIGN=LEFT NOWRAP><FONT COLOR=#FFFFFF>氏名</TH>
  <TH ALIGN=LEFT NOWRAP><FONT COLOR=#FFFFFF>電話・EMAIL</TH>
  <TH ALIGN=CENTER NOWRAP><FONT COLOR=#FFFFFF>ログ</TH>
</TR>
<?
  if ($cnt < 1) {
    // 該当無し
    print "<TR BGCOLOR=#FFFFFF>\n";
    print "<TD BGCOLOR=#FFFFFF ALIGN=CENTER COLSPAN=4><BR>該当する情報はありません<BR><BR></TD>\n";
    print "</TR>\n";
  } else {
    // 該当あり

    for ($i=0;$i<$cnt;$i++) {
      $row = pg_fetch_array($res,$i);

      if ($i % 2 ==0) {
        print "<TR BGCOLOR=#FFFFFF>\n";
      } else {
        print "<TR BGCOLOR=#EEEEEE>\n";
      }

      print "<TD ALIGN=LEFT>";
      print "<FONT STYLE=\"font-size:80%\" COLOR=#555555>".$row["corp_kana"]."</FONT><BR>";
      $corp_name = $row["corp_name"];
      $corp_name = ereg_replace("株式会社","",$corp_name);
      $corp_name = ereg_replace("有限会社","",$corp_name);
      $corp_name = ereg_replace("合資会社","",$corp_name);
      $corp_name = ereg_replace("合名会社","",$corp_name);
      $corp_name = ereg_replace("財団法人","",$corp_name);
      $corp_name = ereg_replace("社団法人","",$corp_name);
      $corp_name = ereg_replace("学校法人","",$corp_name);
      $corp_name = ereg_replace("宗教法人","",$corp_name);
      $corp_name = ereg_replace("特定非営利活動法人","",$corp_name);
      $corp_name = ereg_replace("NPO法人","",$corp_name);
      $corp_name = ereg_replace("社会福祉法人","",$corp_name);
      $corp_name = ereg_replace("公益法人","",$corp_name);
      $corp_name = ereg_replace("医療法人","",$corp_name);
      $corp_name = ereg_replace("事業協同組合","",$corp_name);
      $corp_name = ereg_replace("協同組合連合会","",$corp_name);
      $corp_name = ereg_replace("企業組合","",$corp_name);
      $corp_name = ereg_replace("協業組合","",$corp_name);
      $corp_name = ereg_replace("振興組合","",$corp_name);
      $corp_name = trim($corp_name);
      $corp_name = mberegi_replace("　","",$corp_name);
      print "<A HREF=\"../edit/?s=".$row["seqno"]."\">".$corp_name."</A>";
      print "</TD>\n";

      print "<TD ALIGN=LEFT NOWRAP>";
      print "<FONT STYLE=\"font-size:80%\" COLOR=#555555>".$row["person_kana"]."</FONT><BR>";
      print "<A HREF=\"../edit/?s=".$row["seqno"]."&now_type=P\">".$row["person_name"]."</A>";
      print "</TD>\n";

      print "<TD ALIGN=LEFT $td_style>";
      if (empty($row["person_tel"]) || trim($row["person_tel"])=="") {
        print $row["corp_tel"];
        if (!empty($row["person_tel"]) && trim($row["person_tel"])!="") {
          print "(".$row["person_dialin"].")";
        }
      } else {
        print $row["person_tel"];
      }
      print "<BR>\n";
      if (empty($row["person_email"]) || trim($row["person_email"])=="") {
        $email = $row["corp_email"];
      } else {
        $email = $row["person_email"];
      }
      if (empty($email) || trim($email)=="" || $email =="-") {
      } else {
        print "<FONT STYLE=\"font-size:7pt\"><A HREF=\"mailto:$email\">$email</A>";
      }
      print "</TD>\n";

      $sql_log = "SELECT COUNT(*) AS allrecords FROM address_log WHERE address_seqno=".$row["seqno"];
      $res_log = pg_query($conn,$sql_log);
      $row_log = pg_fetch_array($res_log,0);
      print "<TD ALIGN=CENTER><FONT STYLE=\"font-size:7pt\">";
      print "<A HREF=\"../edit/?s=".$row["seqno"]."&now_type=L'\">(".$row_log["allrecords"].")</A>";
      print "</TD>\n";

      print "</TR>\n";
    }
  }
?>
</TABLE>
<BR>

</TD></TR></TABLE>
</CENTER>
<?php
  include "../../footer.inc.php";
?>