<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" ALT=\"トップページ\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" ALT=\"管理者メニュー\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>行き先名称設定</FONT> ";

  // ヘッダ表示
  include "../../header.inc.php";

  // 機能別メニュー内容の取得
  include "../menu.inc.php";

  if ($login && $admin_sign=="t") {
    print "<!--";
    $pagetext = "";
    $pagetext .= "<SCRIPT LANGUAGE=\"JavaScript\">\n";
    $pagetext .= "<!--\n";
    $pagetext .= "function delConfirm(seqno,id,p) {\n";
    $pagetext .= "  if (id=='1' || id=='2') {\n";
    $pagetext .= "    alert(\"この項目は削除できません\");\n";
    $pagetext .= "  } else {";
    $pagetext .= "    if (confirm(\"この項目を削除しますか？\\n注:一度削除した項目は元に戻すことはできません\")) {\n";
    $pagetext .= "      window.open('./delete.phtml?seqno='+seqno+'&id='+id+'&p='+p+'','_self');\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "// -->\n";
    $pagetext .= "</SCRIPT>\n";
    $pagetext .= "<BR><CENTER>\n";

    if (!empty($_POST["back"]) && $_POST["back"]=="t") {
      // 更新ページからの戻り(エラー)時
      $p      = stripslashes($_POST["p"]);
      $seqno  = stripslashes($_POST["seqno"]);
      $id     = stripslashes($_POST["id"]);
      $name   = stripslashes($_POST["name"]);
    } else {
      // 変数処理
      if (!empty($_REQUEST["p"])) $p = $_REQUEST["p"];

      // SELECT条件の指定
      if ((!empty($_REQUEST["seqno"]) && is_numeric($_REQUEST["seqno"])) &&
          (!empty($_REQUEST["id"])    && is_numeric($_REQUEST["id"])) ) {
        $sql = "SELECT * FROM locations WHERE seqno=".$_REQUEST["seqno"]." AND id='".$_REQUEST["id"]."'";
        $res = pg_query($conn, $sql);
        $cnt = pg_num_rows($res);
      } else {
        $cnt = 0;
      }

      if ($cnt>0) {
        $row = pg_fetch_array($res, 0);
        $seqno      = $row["seqno"];
        $id         = $row["id"];
        $old_id     = $row["id"];
        $name       = $row["name"];
      } else {
        $seqno      = "";
        $id         = "";
        $name       = "";
      }
    }

    //テーブル出力
    $pagetext .= "<TABLE BGCOLOR=#999999 BORDER=0 CELLPADDING=3 CELLSPACING=1>\n";
    $pagetext .= "<FORM ACTION=\"./update.phtml\" METHOD=POST>\n";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"id\" VALUE=\"$id\">\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$seqno\">\n";
    }
    $pagetext .= "<TR><TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;行き先名称&nbsp;</TD>";
    if ($id!="1" && $id!="2") {
      $pagetext .= "<TD NOWRAP BGCOLOR=#FFFFEE>";
      $pagetext .= "<INPUT TYPE=TEXT NAME=\"name\" SIZE=20 MAXLENGTH=60 VALUE=\"$name\">\n";
    } else {
      $pagetext .= "<TD NOWRAP BGCOLOR=#FFFFEE WIDTH=100>";
      $pagetext .= $name;
    }
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "</TABLE>\n";
    $pagetext .= "<BR>\n";

    if (!empty($_REQUEST["seqno"])) {
      if ($id!="1" && $id!="2") {
        $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"更新する\" STYLE=\"width:80px\">&nbsp;";
        $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"削除\" onclick=\"delConfirm(".$_REQUEST["seqno"].",'$id','$p')\">\n";
      }
    } else {
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"登録する\" STYLE=\"width:80px\">";
    }
    $pagetext .= "</FORM>\n";
    $pagetext .= "</CENTER>\n";
    print "-->";
  }
  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>