<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>掲示板設定</FONT> ";

  include "../../header.inc.php";
  flush();

  include "../menu.inc.php";

  if ($login && $admin_sign=="t") {
    if (!empty($_REQUEST["p"])) $p = $_REQUEST["p"];

    print "<!--";
    $pagetext = "";
    $pagetext .= "
<SCRIPT LANGUAGE=\"JavaScript\">
<!--
function delConfirm(seqno,id) {
  if (confirm(\"この掲示板情報を削除しますか？\\n同時に掲示板にある発言は全て削除されます\\n注:一度削除した掲示板情報は元に戻すことはできません\\nよろしいですか？\")) {
    window.open('./delete.phtml?seqno='+seqno+'&id='+id+'&p=".$p."','_self');
  }
}
function selGroup(f) {
  f.group[1].checked = true;
}
function clearGroup(f) {
  for (i=0;i<f.group_ids.length;i++) {
    f.group_ids.options[i].selected = false;
  }
}
function selUser(f) {
  f.user[1].checked = true;
}
function clearUser(f) {
  for (i=0;i<f.user_ids.length;i++) {
    f.user_ids.options[i].selected = false;
  }
}
// -->
</SCRIPT>

<BR><CENTER>

";
    if (!empty($_POST["back"]) && $_POST["back"] == "t") {
      // 更新ページからの戻り(エラー)時
      $seqno    = stripslashes($_POST["seqno"]);
      $name     = stripslashes($_POST["name"]);
      $id       = stripslashes($_POST["id"]);
      $admin_id = stripslashes($_POST["admin_id"]);
      $group_ids = get_first("boards","view_group_ids","seqno=$seqno","");
      $user_ids  = get_first("boards","view_user_ids","seqno=$seqno","");
      $sendsign = stripslashes($_POST["sendsign"]);
    } else {
      // SELECT条件の指定
      if ((!empty($_REQUEST["seqno"]) && is_numeric($_REQUEST["seqno"])))  {
        $sql = "SELECT * FROM boards WHERE seqno=".$_REQUEST["seqno"];
        $res = pg_query($conn, $sql);
        $cnt = pg_num_rows($res);
      } else {
        $cnt = 0;
      }

      if ($cnt>0) {
        $row         = pg_fetch_array($res, 0);
        $seqno       = $row["seqno"];
        $name        = $row["name"];
        $id          = $row["id"];
        $admin_id    = $row["admin_id"];
        $group_ids   = $row["view_group_ids"];
        $user_ids    = $row["view_user_ids"];
        $sendsign    = $row["sendsign"];
      } else {
        $seqno       = "";
        $name        = "";
        $id          = "";
        $admin_id    = "";
        $sendsign    = "";
      }
    }

    $group_id = split(",",$group_ids);
    $user_id  = split(",",$user_ids);

    //テーブル出力
    $pagetext .= "<TABLE BGCOLOR=#999999 BORDER=0 CELLPADDING=3 CELLSPACING=1>\n";
    $pagetext .= "<FORM ACTION=\"./update.phtml\" METHOD=POST>\n";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"".$p."\">\n";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"old_id\" VALUE=\"".$id."\">\n";
    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"".$_REQUEST["seqno"]."\">\n";
    }

    $pagetext .= "<TR>\n";
    $pagetext .= "<TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;掲示板ＩＤ&nbsp;</TH>\n";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    $pagetext .= "<INPUT TYPE=TEXT NAME=\"id\" SIZE=14 MAXLENGTH=12 VALUE=\"".$id."\" STYLE=\"ime-mode:disabled\"><BR>";
    $pagetext .= "<FONT COLOR=#FF0000>※半角英数字12文字まで</FONT>";
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "<TR>\n";
    $pagetext .= "<TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;掲示板名&nbsp;</TH>\n";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    $pagetext .= "<INPUT TYPE=TEXT NAME=\"name\" SIZE=34 VALUE=\"".$name."\"><BR>";
    $pagetext .= "<FONT COLOR=#FF0000>※全角14文字（半角28文字）まで</FONT>";
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "<TR>\n";
    $pagetext .= "<TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;管理者&nbsp;</TH>\n";
    $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>";

    $pagetext .= "<SELECT NAME=\"admin_id\">\n";
    $pagetext .= "<OPTION VALUE=\"\">------------</OPTION>\n";
    // 登録ユーザー情報の取得
    $sql_users = "SELECT * FROM users ORDER BY seqno";
    $res_users = pg_query($conn,$sql_users);
    $cnt_users = pg_num_rows($res_users);
    if ($cnt_users>0) {
      for ($i=0;$i<$cnt_users;$i++){
        $row_users = pg_fetch_array($res_users,$i);
        $pagetext .= "<OPTION VALUE=\"".$row_users["id"]."\"";
        if ($row_users["id"]==$admin_id) $pagetext .= " SELECTED";
        $pagetext .= ">";
       $pagetext .= $row_users["name"];
      $pagetext .= "</OPTION>\n";
      }
    } else {
      $pagetext .= "<OPTION VALUE=\"\">不明</OPTION>\n";
    }
    $pagetext .= "</SELECT>\n";
    $pagetext .= "</TD></TR>";

    $pagetext .= "<TR>\n";
    $pagetext .= "<TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;投稿通知&nbsp;</TH>\n";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    if ($sendsign=="t") {
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"sendsign\" VALUE=\"t\" CHECKED><FONT COLOR=#3333FF>あり</FONT>\n";
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"sendsign\" VALUE=\"f\"><FONT COLOR=#FF3333>なし</FONT>\n";
    } else {
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"sendsign\" VALUE=\"t\"><FONT COLOR=#3333FF>あり</FONT>\n";
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"sendsign\" VALUE=\"f\" CHECKED><FONT COLOR=#FF3333>なし</FONT>\n";
    }
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "<TR>\n";
    $pagetext .= "<TH NOWRAP BGCOLOR=$td_back_left COLSPAN=2>&nbsp;利用者設定&nbsp;</TH>\n";
    $pagetext .= "</TR>\n";

    $pagetext .= "<TR>\n";
    $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back COLSPAN=2>";

    $pagetext .= "<TABLE CELLPADDING=3 CELLSPACING=1 BGCOLOR=#999999>\n";
    $pagetext .= "<TR><TD BGCOLOR=#CCCCCC ALIGN=CENTER>グループ指定</TD>\n";
    $pagetext .= "<TD BGCOLOR=#999999 ALIGN=CENTER>ユーザー指定</TD></TR>\n";
    $pagetext .= "<TR>\n";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"target\" VALUE=\"group\">\n";
    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$seqno\">\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"id\" VALUE=\"$id\">\n";
    }
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
    $pagetext .= "<TD BGCOLOR=$td_back ALIGN=CENTER STYLE=\"text-align:center\">";

    $pagetext .= "<INPUT TYPE=RADIO NAME=\"group\" VALUE=\"all\"";
    if ($group_ids=="" || $group_ids=="all") {
      $pagetext .= " CHECKED";
    }
    $pagetext .= " ONCLICK=\"clearGroup(this.form)\">未設定";

    $pagetext .= "<INPUT TYPE=RADIO NAME=\"group\" VALUE=\"select\"";
    if ($group_ids!="" && $group_ids!="all") {
      $pagetext .= " CHECKED";
    }
    $pagetext .= ">個別選択<BR>\n";

    $pagetext .= "<SELECT NAME=\"group_ids[]\" SIZE=5 MULTIPLE STYLE=\"width:120px\" ONCLICK=\"selGroup(this.form)\">\n";
    $sql_group = "SELECT * FROM groups ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\"";
        if (sizeof($group_id)>0) {
          reset($group_id);
          while (list($key,$val)=each($group_id)) {
            if ($val==$row_group["id"]) { $pagetext .= " SELECTED"; break; }
          }
        }
        $pagetext .= ">".$row_group["name"]."\n";
      }
    }

    $pagetext .= "</SELECT><BR>\n";

    $pagetext .= "</TD>";

    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"target\" VALUE=\"user\">\n";
    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$seqno\">\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"id\" VALUE=\"$id\">\n";
    }
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
    $pagetext .= "<TD BGCOLOR=$td_back ALIGN=CENTER STYLE=\"text-align:center\">";

    $pagetext .= "<INPUT TYPE=RADIO NAME=\"user\" VALUE=\"all\"";
    if ($user_ids=="" || $user_ids=="all") {
      $pagetext .= " CHECKED";
    }
    $pagetext .= " ONCLICK=\"clearUser(this.form)\">未設定";

    $pagetext .= "<INPUT TYPE=RADIO NAME=\"user\" VALUE=\"select\"";
    if ($user_ids!="" && $user_ids!="all") {
      $pagetext .= " CHECKED";
    }
    $pagetext .= ">個別選択<BR>\n";

    $pagetext .= "<SELECT NAME=\"user_ids[]\" SIZE=5 MULTIPLE STYLE=\"width:160px\" ONCLICK=\"selUser(this.form)\">\n";

    $sql_user = "SELECT * FROM users ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);
    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\"";
        if (sizeof($user_id)>0) {
          reset($user_id);
          while (list($key,$val)=each($user_id)) {
            if ($val==$row_user["id"]) { $pagetext .= " SELECTED"; break; }
          }
        }
        $pagetext .= ">".$row_user["name"]."\n";
      }
    }

    $pagetext .= "</SELECT><BR>\n";
    $pagetext .= "</TD>";
    $pagetext .= "</TR></TABLE>\n";
    $pagetext .= "</TD></TR>";
    $pagetext .= "</TABLE>\n";
    $pagetext .= "<FONT STYLE=\"font-size:7pt\" COLOR=#777755>※ どちらかの指定に該当させることで閲覧可能になります</FONT>";
    $pagetext .= "<BR><BR>\n";

    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"更新する\" STYLE=\"width:80px\">&nbsp;";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"削除\" onclick=\"delConfirm(".$_REQUEST["seqno"].",'".$id."')\">\n";
    } else {
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"登録する\" STYLE=\"width:80px\">";
    }
    $pagetext .= "</FORM>\n";
    $pagetext .= "</CENTER>\n";
    print "-->";
  }
  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>