<?php  
  include "../config.inc.php";
  include "../lib.inc.php";
  include "../language.inc.php";

  $headertext .= "Set-Cookie: room_move=yearly; path=/;\n";
  if (!empty($y)) $headertext .= "Set-Cookie: room_y=$y; path=/;\n";
  if (!empty($m)) $headertext .= "Set-Cookie: room_m=$m; path=/;\n";
  if (!empty($d)) $headertext .= "Set-Cookie: room_d=$d; path=/;\n";
  if (empty($y)) $y = $_COOKIE["room_y"];
  if (empty($m)) $m = $_COOKIE["room_m"];
  if (empty($d)) $d = $_COOKIE["room_d"];

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../\" ALT=\"トップページ\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>施設・設備予約:月表示</FONT> ";

  // ヘッダ表示
  $cy = $y; //退避
  include ("../header.inc.php");
  $y = $cy; //復元
  flush();
  
  if ($login && sizeof($MES)==0) {
    //現在日の設定
    if ($y=="" or $y==0 or !is_numeric($y)) {
      $tempdate = getdate();
      $y = $tempdate["year"];
    }

    //表示開始日の調整
    $tempstamp = mktime(0, 0, 0, $m, 1, $y);
    $tempdate = getdate($tempstamp);
    $w = $tempdate["wday"];

    # 表示を月曜日初めか日曜日初めか、判断
    $sql_start_mon = "SELECT * FROM users where id='".$login_id."'";
    $res_start_mon = pg_query($conn,$sql_start_mon);
    if ($res_start_mon == "false"){
      $start_mon = "f";
    } else {
      $start_mon = pg_fetch_array($res_start_mon,0);
      $start_mon = $start_mon["startmonday"];
      if ($start_mon == ""){  // 情報が無い場合は、日曜日先頭
        $start_mon = "f";
      }
    }
    if ($start_mon == "f"){
      $stamp_s = $tempstamp - 86400 * $w;
    } else {
      $stamp_s = $tempstamp - 86400 * ($w-1);
    }
    $date_s = getdate($stamp_s);
    $year_s = $date_s["year"];
    $mon_s = $date_s["mon"];
    $day_s = $date_s["mday"];

    $stamp_e = $stamp_s + 86400 * 6;
    $date_e = getdate($stamp_e);
    $year_e = $date_e["year"];
    $mon_e = $date_e["mon"];
    $day_e = $date_e["mday"];

    if ($other == "") $other = $login_id;
?>

<SCRIPT LANGUAGE="JavaScript">
<!--
function reload(o){
<?
  print "  var v = o.options[o.selectedIndex].value;\n";
  print "  o.selectedIndex = 0;\n";
  print "  if (v!=\"\" && v!=\"null\") {\n";
  print "    location.href='./yearly.phtml';\n";
  print "  }\n";
?>
}
function selectyear(f){
<?
  $cy = $y;  // 月

  for ($i=0;$i<=2;$i++){
    print "if (f.year.selectedIndex == $i)";
    print "{location.href=\"./yearly.phtml?y=".($cy+$i-1)."\"}\n";
  }
?>
}
//-->
</SCRIPT>

<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH=100%><TR>
<FORM>
<TH ALIGN=LEFT WIDTH=60% NOWRAP>
<?php
    // 開始日 終了日の算出
    $today = getdate();
    if ($y=="") {
      $y = $today["year"];
    }

    $first = getdate(mktime(0, 0, 1, $m, 1, $y));

    $next_y = $y+1;
    $prev_y = $y-1;

    print "&nbsp;\n";
?>
</TH>
<TH ALIGN=RIGHT WIDTH=40% NOWRAP>
<A HREF="./add/?p=yearly&ey=<? echo $y ?>&em=<? echo $m ?>&ed=1"><IMG SRC="../image/entrysadd.gif" WIDTH=10 HEIGHT=9 BORDER="0" ALT="予約の追加">新しい予約</A>&nbsp;
</TH>
</FORM></TR></TABLE>
<?php
    // 年月表示
    print "<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=2 WIDTH=100%><TR>\n";
    print "<TD ALIGN=RIGHT VALIGN=MIDDLE NOWRAP WIDTH=45%>";
    print "<A HREF=\"./yearly.phtml?y=".$prev_y."\"><IMG SRC=\"../image/right1.gif\" BORDER=0 WIDTH=16 HEIGHT=16 ALT=\"前の年\"></A></TD>\n";

    // カレンダーメニュー（年単位）
    print "<TD ALIGN=LEFT WIDTH=80 NOWRAP>\n";
    print "<FORM><SELECT NAME=\"year\" onChange=\"selectyear(this.form)\">\n";
    for ($i=$y-1;$i<=$y+1;$i++){
      print "<OPTION";
      if ($i == $y){
        print " SELECTED>【";
      } else {
        print ">　";
      }
      print $i."年";
      if ($i == $y){
        print "】\n";
      } else {
        print "\n";
      }
    }
    print "</SELECT></TD></FORM>\n";
    // カレンダーメニュー終了
    
    print "<TD VALIGN=MIDDLE NOWRAP>";
    print "<A HREF=\"./yearly.phtml?y=".$next_y."\"><IMG SRC=\"../image/left1.gif\" BORDER=0 WIDTH=16 HEIGHT=16 ALT=\"次の年\"></A></TD>\n";

    print "<TD ALIGN=RIGHT NOWRAP>";
    print "<A HREF=\"./daily.phtml?y=".$today["year"]."&m=".$today["mon"]."&d=".$today["mday"]."\"><IMG SRC=\"./image/today.gif\" BORDER=0 WIDTH=61 HEIGHT=21 ALT=\"今日\"></A>";
    print "<A HREF=\"./?y=".$today["year"]."&m=".$today["mon"]."&d=".$today["mday"]."\"><IMG SRC=\"./image/toweek.gif\" BORDER=0 WIDTH=61 HEIGHT=21 ALT=\"今週\"></A>";
    print "<A HREF=\"./monthly.phtml?y=".$today["year"]."&m=".$today["mon"]."&d=".$today["mday"]."\"><IMG SRC=\"./image/tomonth.gif\" BORDER=0 WIDTH=61 HEIGHT=21 ALT=\"今月\"></A>";
    print "<A HREF=\"./yearly.phtml?y=".$today["year"]."&m=".$today["mon"]."&d=".$today["mday"]."\"><IMG SRC=\"./image/toyear.gif\" BORDER=0 WIDTH=61 HEIGHT=21 ALT=\"今年\"></A>";
    print "</TD>\n";

    print "</TR></TABLE>\n";
    
    // 曜日表示
    print "<TABLE BORDER=0 CELLSPACING=5 CELLPADDING=0 WIDTH=100%>\n";
    for ($m=1;$m<=12;$m++) {
      if ($m==1 or $m==5 or $m==9) {
        print "<TR>";
      }
      print "<TD ALIGN=CENTER VALIGN=TOP BGCOLOR=#FFFFFF>";

      print "<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0 BGCOLOR=$bodyBackColor><TR><TD ALIGN=CENTER>";
      print "<A HREF=\"./monthly.phtml?y=".$y."&m=".$m."\">".$m."月</A>";
      print "</TD></TR></TABLE>\n";

#      print "<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0 BGCOLOR=$bg_light>";
			print "<TABLE BORDER=0 WIDTH=100% CELLPADDING=0 CELLSPACING=0 BGCOLOR=#FFFFFF>";

      print "<TR BGCOLOR=$bg_dark><TD>&nbsp;</TD>";
      if ($start_mon == "f"){  // 月曜先頭か判断
        for ($col=0;$col<7;$col++) {
          print "<TD ALIGN=CENTER NOWRAP WIDTH=11%><FONT COLOR=\"".$wcolor_title[$col]."\">".$wname[$col]."</FONT></TD>";
        }
      } else {
        for ($col=1;$col<8;$col++) {
          if ($col == 7){ $col = 0; }
          print "<TD ALIGN=CENTER NOWRAP WIDTH=11%><FONT COLOR=\"".$wcolor_title[$col]."\">".$wname[$col]."</FONT></TD>";
          if ($col == 0){ break; }
        }
      }
      print "<TD>&nbsp;</TD></TR>\n";

#      print "<TR BGCOLOR=#FFFFFF>";
#      print "<TD BGCOLOR=#FFFFFF ALIGN=CENTER COLSPAN=9><TABLE><TR><TD><TT>";

      $first = getdate(mktime(0, 0, 1, $m, 1, $y));
      $next_y = $y;
      $next_m = $m + 1;
      if ($next_m>12) {
        $next_y = $y + 1;
        $next_m = 1;
      }
      $last  = getdate(mktime(0, 0, 1, $next_m, 1, $next_y)-86400);

      // カレンダー表示
        $draw = false;
        $d = 0;

        $drawin = false;

        $row=0;
        while (true) {
					print "<TR STYLE=\"line-height:140%\">\n";
					print "<TD>&nbsp;</TD>\n";
          if ($start_mon == "f"){
            $col=0;
          } else {
            $col=1; // 月曜日
          }
          while (true) {
            $daytype = "";
            // 前月まで
						if ($start_mon == "f"){
							if ($first["wday"]==$col || $first["wday"] == 0) {
								$drawin = true;
								$draw = true;
							}
						} else {
							if (($first["wday"]==$col || $first["wday"]==$col-7) || $first["wday"] == 1) {
								$drawin = true;
								$draw = true;
							}
						}

#            if (!$draw) {
#              if ($first["wday"]==$col or $first["wday"] == 0) {
#                $drawin = true;
#                $draw = true;
#              }
#            }
#            if ($first["wday"] == 0 and $draw_start <> "t" and $start_mon=="t"){
#              $draw_start = "t";
#              $d++; 
#            }
            // 当月まで
            if ($draw) {
              if ($d < $last["mday"]) {
                $d++;
                $checkdate = date("Y-m-d",mktime(0,0,0,$m,$d,$y));
                // 祭日チェック
                $sql_holiday = "select * from holiday where holiday='".$checkdate."'";
                $res_holiday = pg_query($conn, $sql_holiday);

                if (pg_num_rows($res_holiday)<1) {
                  $daytype = "normal";
                } else {
                  $daytype = "holiday";
                  $row_holiday = pg_fetch_array($res_holiday,0);
                  $holiday = $row_holiday["name"];
                }
                pg_free_result($res_holiday);
              }
            }

            // 表示データ作成
            switch ($daytype) {
              case "":
                $backcolor = $wcolor_back[$col];
                $forecolor = $wcolor[$col];
                if (!$drawin) {
                  // 当月以前
#                  $diff = $col-$first["wday"];
#                  $wd = getdate((mktime(0, 0, 1, $m, 1, $y)+(86400*$diff)));
#                  $checkdate = date("Y-m-d",mktime(0,0,0,$wd["mon"],$wd["mday"],$wd["year"]));
#                  $daytext = "&nbsp;&nbsp;&nbsp;";
                  $daytext = "&nbsp;";
                } else {
                  // 当月以降
#                  $diff = $col-$last["wday"]-1;
#                  $wd = getdate((mktime(0, 0, 1, $next_m, 1, $next_y)+(86400*$diff)));
#                  $checkdate = date("Y-m-d",mktime(0,0,0,$wd["mon"],$wd["mday"],$wd["year"]));
#                  $daytext = "&nbsp;&nbsp;&nbsp;";
                  $daytext = "&nbsp;";
                }
                break;
              case "normal":
                $backcolor = $wcolor_back[$col];
                $forecolor = $wcolor[$col];
                if ($restday[$col]!="t") {
                  $daytext = "";
                  if ($d<10) { $daytext .= "&nbsp;"; }
                  $daytext .= $d." ";
                } else {
                  $daytext = "<FONT STYLE=\"background-color:#FF9999\">";
                  if ($d<10) { $daytext .= "&nbsp;"; }
                  $daytext .= $d."</FONT> ";
                }
                break;
              case "holiday":
                $backcolor = $wcolor_back[7];
                $forecolor = $wcolor[7];
                $daytext = "<FONT STYLE=\"background-color:#FF9999\">";
                if ($d<10) { $daytext .= "&nbsp;"; }
                $daytext .= $d."</FONT> ";
                break;
            }

            if ($daytype != "") {
              if ($y==$today["year"] and $m==$today["mon"] and $d==$today["mday"]) {
                // 今日
#                $daytext = eregi_replace("#","color:#FFFFFF;font-weight:bold",$daytext);
                $backcolor = "#AAAAFF";
              } else {
                // 今日以外
#                $daytext = eregi_replace("#","color:".$forecolor.";font-weight:bold",$daytext);
              }
            } else {
              // 今日以外(別の月)
#              $daytext = eregi_replace("#","color:#999999;font-weight:normal",$daytext);
            }

            if (($start_mon == "f" && $col==0) || ($start_mon == "t" && $col==1)) {
              $d2 = $d;
              if ($d2<1) { $d2 = 1; }
              print " <A HREF=\"./?y=".$y."&m=".$m."&d=".$d2."\">";
            }

            // 日
						## 日付
						print "<TD WIDTH=11% ALIGN=CENTER><DIV><TT><A HREF=\"./?y=$y&m=$m&d=$d2\">$daytext</A></TT></DIV></TD>\n";
#            print $daytext;

            // データチェック
            $col++;
            if ($start_mon == "f"){
              if ($col>6) {
                break;
              }
            } else {
              if ($col>7) {
                $col = 0;
                $col_end = "t";
              } else {
                $col_end = "f";
              }
              if ($col_end == "t"){ break; }
            }
          }
#          print "</A></TD></TR>\n";
#          print "</A><BR>";
					print "<TD>&nbsp;</TD>\n";
					print "</TR>\n";

          $row++;
          if ($d >= $last["mday"]) {
            break;
          }
        }

#      print "</TD>";
#      print "</TR>";
#      print "</TABLE>";

#      print "</TD>";
#      print "</TR>";
      print "</TABLE>";

      print "</TD>";
      if ($m==4 or $m==8 or $m==12) {
        print "</TR>";
      }
    }
    print "</TABLE>\n";

    print "</TD></TR></TABLE>\n";
?>
<br>
<?php
  }
  // 後処理
  pg_free_result($res);

  // フッタ表示
  include ("../footer.inc.php");
?>
