<?
  include "../../config.inc.php";
  include "../../lib.inc.php";

  // 表示行数の調整
  if (empty($rows)) $rows= 15;
  if ($rows<10) $rows = 10;
  if ($rows>50) $rows = 50;

  if (!empty($_REQUEST["mode"])) { $mode = $_REQUEST["mode"]; }
  if (!empty($_REQUEST["from"])) { $from = $_REQUEST["from"]; }
  if (!empty($_REQUEST["to"]))   { $to   = $_REQUEST["to"]; }
  if (!empty($_REQUEST["p"]))    { $p    = $_REQUEST["p"]; } else { $p = 1; }
  if (!is_numeric($p)) $p = 1;

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>休日設定</FONT> ";

  // ヘッダ表示
  include "../../header.inc.php";

  // 機能別メニュー内容の取得
  include "../menu.inc.php";

  if ($login && $admin_sign=="t") {
    print "<!--";
    // ページ準備
    $pagetext  = "";
    $pagetext .= "<SCRIPT Language=\"JavaScript\">
<!--
function sequence(from,to) {
  window.location.href = './?mode=seq&from='+from+'&to='+to+'&p=".$p."';
}
// -->
</SCRIPT>
";
    // 検索条件の指定
    $sql = "SELECT * FROM holiday";
    if ($where<>"") {
      $sql .= " WHERE ".$where;
    }
    $sql .= " ORDER BY holiday DESC";
    $res = pg_query($conn, $sql);
    $cnt = pg_num_rows($res);

    if ($cnt>0) {  
      $allpages = floor(($cnt-1)/$rows)+1;
      if ($p>$allpages) $p = 1;

      $s_row = ($p-1) * $rows;
      $e_row = $p * $rows - 1;
      if ($e_row>$cnt-1) {$e_row = $cnt-1;}
      if ($cnt-1>$e_row) {$nextpage = true;}
    } else {
      $allpages = 1;
    }

    //テーブル出力
    $pagetext .= "<CENTER>
<TABLE BORDER=0>
";
    $pagetext .= "<TR><TD>";

    $pagetext .= "<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0><TR>";
    $pagetext .= "<TD>".$cnt."件中 ".($s_row+1)."〜".($e_row+1)."件目の表示&nbsp;&nbsp;</TD>";
    if ($admin_sign){
      $pagetext .= "<TD ALIGN=RIGHT>&nbsp;&nbsp;<A HREF=\"./edit.phtml?p=$p\">追加する <IMG SRC=\"../../image/entrysadd.gif\" BORDER=0 ALT=\"追加する\"></A></TD>";
    }
    $pagetext .= "</TD></TR></TABLE>";

    $pagetext .= "</TD></TR>\n";

    $pagetext .= "
<TR><TD>
<TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 BGCOLOR=#666666>
<TR BGCOLOR=#999999>
<TH><FONT COLOR=#FFFFFF>日付</TH>
<TH><FONT COLOR=#FFFFFF>名称</TH>
</TR>
";
    if ($cnt<1) {  
      $pagetext .= "<TR BGCOLOR=#FFFFFF><TD ALIGN=CENTER COLSPAN=6>データ未登録</TD></TR>";
    } else {
      for ($i=$s_row;$i<=$e_row;$i++) {
        $row = pg_fetch_array($res, $i);  

        if ($i % 2 == 0){
          $tdcolor = $bg_dark;
        } else {
          $tdcolor = $bg_light;
        }
        $pagetext .= "<TR BGCOLOR=".$tdcolor.">\n";

        // データ
        $pagetext .= "<TD NOWRAP ALIGN=LEFT>&nbsp;<A HREF=\"./edit.phtml?holiday=".date("Y-m-d",date2timestamp($row["holiday"]))."&p=$p\">".date("Y-m-d",date2timestamp($row["holiday"]))." <IMG SRC=\"../../image/entrysadd.gif\" BORDER=0 ALT=\"編集する\"></A>&nbsp;</TD>\n";

        $pagetext .= "<TD NOWRAP ALIGN=LEFT>".$row["name"]."&nbsp;</TD>\n";

        $pagetext .= "</TR>\n";
      }
    }

    $pagetext .= "</TABLE>\n";
    $pagetext .= "</CENTER>\n";

    // ページ情報の表示
    if ($allpages>1) {
      $pagetext .= "<BR>";
      $pagetext .= "<CENTER>";

      $r = 0;
      $s_p = $p - 4;
      $e_p = $p + 4;
      if ($s_p<1) {
        $r = 1-$s_p;
        $s_p = $s_p + $r;
        $e_p = $e_p + $r;
      } elseif ($e_p>$allpages) {
        $r = $e_p - $allpages;
        $s_p = $s_p - $r;
        $e_p = $e_p - $r;
      }
      if ($s_p < 1) $s_p = 1;
      if ($e_p > $allpages) $e_p = $allpages;

      if ($p>1) {
        $pagetext .= "<A HREF=\"./?p=".($p-1)."\">";
        $pagetext .= "前のページ";
        $pagetext .= "</A>";
      } else {
        $pagetext .= "<FONT COLOR=#999999>前のページ</FONT>";
      }

      $pagetext .= "&nbsp;&nbsp;";

      if ($s_p != 1) {
        $pagetext .= "<A HREF=\"./p=".($s_p-1)."\">&lt;</A>&nbsp;";
      }

      for ($i=$s_p;$i<=$e_p;$i++){
        if ($p!=$i) {
          $pagetext .= "[<A HREF=\"./?p=".$i."\">".$i."</A>]";
        } else {
          $pagetext .= "[".$i."]";
        }
        $pagetext .= "&nbsp;";
      }

      if ($e_p != $allpages) {
        $pagetext .= "<A HREF=\"./?p=".($e_p+1)."\">&gt;</A>";
      }

      $pagetext .= "&nbsp;";

      if ($nextpage) {
        $pagetext .= "<A HREF=\"./?p=".($p+1)."\">";
        $pagetext .= "次のページ";
        $pagetext .= "</A>";
      } else {
        $pagetext .= "<FONT COLOR=#999999>次のページ</FONT>";
      }

      $pagetext .= "&nbsp;";
      $pagetext .= "</CENTER>\n";
    }

    $pagetext .= "</TD></TR></TABLE>\n";

    print "-->\n";
  }

  include "../../detail.inc.php";
  include "../../footer.inc.php";
?>
