<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">伝言メモ</A> &gt; ";
  if (empty($n)) {
    $linktext .= "<FONT COLOR=#FFFF00>メモの登録</FONT>";
  } else {
    $linktext .= "<FONT COLOR=#FFFF00>メモの表示</FONT>";
  }
  include "../../header.inc.php";

  if ($login && sizeof($MES)==0) {
    if (empty($sendtype)) { $sendtype = 1; }

    //登録ページからの戻り判定
    if (eregi("mail\/add\/add\.phtml",$referer)){
      if ($to_back!="") {
        $to = $to_back;
      }
    } elseif (eregi("\/schedule\/",$referer)) {
      // スケジュールからの呼び出し時
      $sch_flag = true;
      $tos = $id;
    } else {
      if (!empty($n) && is_numeric($n)){
        $sql = "SELECT * FROM mail where seqno=".$n;
        $res = pg_query($conn,$sql);
        $cnt = pg_num_rows($res);
        if ($cnt>0) {
          $row = pg_fetch_array($res,0);
          $seqno         = $res["seqno"];
          $a             = $res["address_seqno"];
          $priority      = $res["priority"];
          $from          = $res["from"];
          $to            = $res["to"];
          $body          = $res["body"];
          $createstamp   = $res["createstamp"];
        } else {
          $DMES[] = "指定されたメモは既に削除されています";
        }
      }
    }

    if (sizeof($DMES)>0) {
      $pagetext .= "<BR>";
      $pagetext .= "<TABLE BORDER=0 WIDTH=100%><FORM><TR><TD ALIGN=CENTER><FONT COLOR=#FF0000>";
      $pagetext .= "<BR>";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>\n";
      }
      $pagetext .= "<BR>";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" ONCLICK=\"history.back()\">";

      $pagetext .= "</TD></TR></FORM></TABLE>\n";
    } else {
      // 正常処理
      $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 ALIGN=CENTER><TR><TD ALIGN=CENTER>";

      if (empty($n)) {
        //------------
        // メモの登録
        //------------
        if ($s != "") {
          // 返信モード
          $sql_mail = "SELECT * FROM mail where seqno=".$s;
          $res_mail = pg_query($conn,$sql_mail);
          $cnt_mail = pg_num_rows($res_mail);

          if ($cnt_mail>0) {
            $row_mail = pg_fetch_array($res_mail,0);

            $bodys = split("\n",textsafe($row_mail["body"]));
            if (sizeof($bodys)>0) {
              while(list($key,$val)=each($bodys)) {
                $body .= "> ".$val."\n";
              }
            }

            $to = $row_mail["from"];

            if ($mode=="D") {
              // 返信モード削除時
              $sql_mail = "DELETE FROM mail where seqno=".$s;
              pg_query($conn,$sql_mail);
            }
          }
        }

        $pagetext .= "<SCRIPT LANGUAGE=\"JavaScript\">\n";
        $pagetext .= "<!--\n";
        $pagetext .= "my = \"$login_id\";\n";
        $pagetext .= "dat_groups = new Array();\n";

        $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
        $res_group = pg_query($conn,$sql_group);
        $cnt_group = pg_num_rows($res_group);
        $pagetext .= "cnt_groups = ".$cnt_group."\n";
        if ($cnt_group>0) {
          for ($i=0;$i<$cnt_group;$i++) {
          $row_group = pg_fetch_array($res_group,$i);
            $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
            $cnt_entry = pg_num_rows($res_entry);

            if ($res_entry>0) {
              $users_entry = "";
              for ($j=0;$j<$cnt_entry;$j++) {
                $row_entry = pg_fetch_array($res_entry,$j);
                if ($users_entry != "") $users_entry .= ",";
                $users_entry .= $row_entry["user_id"];
              }
            }
            if ($users_entry!="") {
              $pagetext .= "dat_groups[\"".$row_group["id"]."\"] = \"".$users_entry."\";\n";
            }
          }
        }

        $pagetext .= "dat_users = new Array();\n";

        $all_users = "";

        $sql_user = "SELECT id,name FROM users ORDER BY seqno";
        $res_user = pg_query($conn,$sql_user);
        $cnt_user = pg_num_rows($res_user);
        $pagetext .= "cnt_users = ".$cnt_user."\n";
        if ($cnt_user>0) {
          for ($i=0;$i<$cnt_user;$i++) {
            $row_user = pg_fetch_array($res_user,$i);
            $pagetext .= "dat_users[\"".$row_user["id"]."\"] = \"".$row_user["name"]."\";\n";
            if ($i!=0) $all_users .= ",";
            $all_users .= $row_user["id"];
          }
        }

        $pagetext .= "dat_groups[\"all\"] = \"".$all_users."\";\n";

        $pagetext .= "
function selectGroup(t) {
  group_id = t.groups[t.groups.selectedIndex].value;
  tos = new Array();

  t.users.length = 0;

  if (group_id == '') {
    tos = dat_groups['all'].split(',');
  } else {
    if (dat_groups[group_id] != null) {
      tos = dat_groups[group_id].split(',');
    }
  }
  if (tos.length>0) {
    c = 0;
    for (i=0;i<tos.length;i++) {
      if (tos[i] != my) {
        t.users.length = t.users.length + 1;
        t.users.options[c].value = tos[i];
        t.users.options[c].text  = dat_users[tos[i]];
        c++;
      }
    }
  }
}

function clearAllUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  o.length = 0;
  t.to.value = '';
}

function selectAllUser(t) {
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      t.users.options[i].selected = true;
    }
  }
  t.allcheck.checked = false;
}

function addUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"tos[]\") {
      var p = i;
      break;
    }
  }
  var o = t.elements[p];

  s = t.to.value;
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      if (t.users.options[i].selected) {
        t.users.options[i].selected = false;
        var id = t.users.options[i].value;
        var c = false;
        for(j=0;j<o.length;j++) {
          if (o.options[j].value == id) {
            c = true;
            break;
          }
        }
        if (!c) {
          if (o.length>0) s = s + ',';
          o.length = o.length + 1;
          o.options[o.length-1].value = id;
          o.options[o.length-1].text = dat_users[id];
          s = s + id;
        }
      }
    }
  }
  t.to.value = s;
}

function removeUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  var val = new Array();
  var txt = new Array();
  var c = 0;
  
  if (o.length>0) {
    for (i=0;i<o.length;i++) {
      if (!o.options[i].selected) {
        val[c] = o.options[i].value;
        txt[c] = o.options[i].text;
        c++;
      }
    }

    o.length = 0;
    s = '';
    if (c>0) {
      o.length = c;
      for (i=0;i<c;i++) {
        if (i>0) s = s + ',';
        o.options[i].value = val[i];
        o.options[i].text  = txt[i];
        s = s + val[i];
      }
    }
    t.to.value = s;
  }
}
//-->
</SCRIPT>
";
        $pagetext .= "<BR>内容を入力して送信先を選択してから、送信ボタンを押してください<BR>\n";
        $pagetext .= "<DIV ALIGN=LEFT><TABLE><TR><TD><A HREF=\"../../address/search/\"><IMG SRC=\"../../image/address.gif\" BORDER=0 ALIGN=ABSMIDDLE>住所録検索へ</A></TD></TR></TABLE></DIV>\n";

        $pagetext .= "<INPUT TYPE=\"HIDDEN\" NAME=\"p\" VALUE=\"".$p."\">\n";

        $pagetext .= "<TR>";
        $pagetext .= "<FORM ACTION=\"./add.phtml\" METHOD=POST>";
        $pagetext .= "<TD VALIGN=TOP ALIGN=CENTER>";
        $pagetext .= "<TABLE border=0 cellspacing=1 cellpadding=4 BGCOLOR=#666666>";
        if ($a != ""){
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"address_seqno\" VALUE=\"$a\">";
        }

        $pagetext .= "<TR BGCOLOR=CCCCCC>";
        $pagetext .= "<TD ALIGN=RIGHT NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;内容&nbsp;</TD>";
        $pagetext .= "<TD ALIGN=LEFT NOWRAP BGCOLOR=$td_back>";

        if ($a != "") {
          $sql_addr = "SELECT * FROM address WHERE seqno=".$a;
          $res_addr = pg_query($conn,$sql_addr);
          $cnt_addr = pg_num_rows($res_addr);
          if ($cnt_addr>0) {
            $row_addr = pg_fetch_array($res_addr,0);
            $corp_name = $row_addr["corp_name"];
            $corp_name = ereg_replace("株式会社","",$corp_name);
            $corp_name = ereg_replace("有限会社","",$corp_name);
            $corp_name = ereg_replace("合資会社","",$corp_name);
            $corp_name = ereg_replace("合名会社","",$corp_name);
            $corp_name = ereg_replace("財団法人","",$corp_name);
            $corp_name = ereg_replace("社団法人","",$corp_name);
            $corp_name = ereg_replace("学校法人","",$corp_name);
            $corp_name = ereg_replace("宗教法人","",$corp_name);
            $corp_name = ereg_replace("特定非営利活動法人","",$corp_name);
            $corp_name = ereg_replace("NPO法人","",$corp_name);
            $corp_name = ereg_replace("社会福祉法人","",$corp_name);
            $corp_name = ereg_replace("公益法人","",$corp_name);
            $corp_name = ereg_replace("医療法人","",$corp_name);
            $corp_name = ereg_replace("事業協同組合","",$corp_name);
            $corp_name = ereg_replace("協同組合連合会","",$corp_name);
            $corp_name = ereg_replace("企業組合","",$corp_name);
            $corp_name = ereg_replace("協業組合","",$corp_name);
            $corp_name = ereg_replace("振興組合","",$corp_name);
            $corp_name = trim($corp_name);
            $corp_name = mberegi_replace("　","",$corp_name);

            $pagetext .= "<FONT COLOR=#555555><B>";
            $pagetext .= $corp_name." ";
            $pagetext .= $row_addr["person_name"];
            $pagetext .= "</B></FONT> 様より<BR>\n";

            $pagetext .= "<script language=\"JavaScript\">\n";
            $pagetext .= "<!--\n";
            $pagetext .= "  function insorg(f,v) {\n";
            $pagetext .= "    f.body.value = v;\n";
            $pagetext .= "    f.body.focus();\n";
            $pagetext .= "  }\n";
            $pagetext .= "//-->\n";
            $pagetext .= "</script>\n";

            $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"伝言\" STYLE=\"width:40px\" ONCLICK=\"insorg(this.form,'お電話がありました')\">";
            $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"電話\" STYLE=\"width:40px\" ONCLICK=\"insorg(this.form,'また、お電話ください')\">";
            $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"至急\" STYLE=\"width:40px\" ONCLICK=\"insorg(this.form,'至急、ご連絡ください')\">";
            $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"来訪\" STYLE=\"width:40px\" ONCLICK=\"insorg(this.form,'○月○日 ○時に来訪します')\">";
            $pagetext .= "<BR>\n";
          }
        }

        $pagetext .= "<TEXTAREA NAME=\"body\" COLS=46 ROWS=6 style=\"ime-mode:active\">$body</TEXTAREA>";
        $pagetext .= "<TABLE CELLPADDING=0 CELLPADDING=0 BORDER=0>";
        $pagetext .= "<TR><TD NOWRAP WIDTH=10%>優先度:</TD>";

        for($i=3;$i>0;$i--) {
          $pagetext .= "<TD WIDTH=26% BGCOLOR=".$priority_color[$i-1]." ALIGN=CENTER>";
          $pagetext .= "<INPUT TYPE=\"RADIO\" NAME=\"priority\" VALUE=\"".$i."\"";
          if ($priority == $i) {
             $pagetext .= " checked";
          }
          if (empty($priority) and $i == 3){
            $pagetext .= " checked";
          }
          $pagetext .= ">";
          $pagetext .= "".$priority_name[$i-1]."";
          $pagetext .= "</TD>";
        }
        $pagetext .= "</TR></TABLE>";
        $pagetext .= "</TD></TR>";

        $pagetext .= "<TR bgcolor=#FFFFFF>";
        $pagetext .= "<TD ALIGN=RIGHT NOWRAP VALIGN=TOP bgcolor=$td_back_left>&nbsp;送信方法&nbsp;</TD>";
        $pagetext .= "<TD BGCOLOR=$td_back>";

        $pagetext .= "<INPUT TYPE=RADIO NAME=send VALUE=\"0\"";
        if ($send == 0) $pagetext .= " checked";
        $pagetext .= ">メモ";
        $pagetext .= "<INPUT TYPE=RADIO NAME=send VALUE=\"1\"";
        if ($send == 1) $pagetext .= " checked";
        $pagetext .= ">メモ/一般メール";
        $pagetext .= "<INPUT TYPE=RADIO NAME=send VALUE=\"2\"";
        if ($send == 2) $pagetext .= " checked";
        $pagetext .= ">メモ/携帯メール";

        $pagetext .= "
<BR>
<FONT COLOR=#555555 STYLE=\"font-size:7pt\">
&nbsp;&nbsp;携帯メールが登録されていない場合、一般メール宛に送信が行われます。<BR>
&nbsp;&nbsp;一般メールも登録されていない場合、メール送信は行われません。<BR>
";
        $pagetext .= "</TD></TR>";

        $pagetext .= "<TR bgcolor=#FFFFFF>";
        $pagetext .= "<TD ALIGN=RIGHT NOWRAP VALIGN=TOP bgcolor=$td_back_left>&nbsp;相手先&nbsp;</TD>";
        $pagetext .= "<TD BGCOLOR=$td_back>";

        $pagetext .= "<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=2>";
        $pagetext .= "<TR><TD COLSPAN=2>&nbsp;</TD><TD>";
        $pagetext .= "<SELECT NAME=\"groups\" ONCHANGE=\"selectGroup(this.form)\" STYLE=\"width:120px\">\n";
        $pagetext .= "<OPTION VALUE=\"\" SELECTED>(全て)\n";

        $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
        $res_group = pg_query($conn,$sql_group);
        $cnt_group = pg_num_rows($res_group);
        if ($cnt_group>0) {
          for ($i=0;$i<$cnt_group;$i++) {
            $row_group = pg_fetch_array($res_group,$i);
            $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
            if (pg_num_rows($res_entry)>0) {
              $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\">".$row_group["name"];
              $pagetext .= "\n";
            }
          }
        }

        $pagetext .= "</SELECT>";
        $pagetext .= "</TD></TR>";

        $pagetext .= "<TR><TD VALIGN=TOP>";
        $pagetext .= "<SELECT NAME=\"tos[]\" SIZE=8 STYLE=\"width:140px\">\n";
        $tos = split(",",$to);

        if (sizeof($tos)>0) {
          for ($i=0;$i<sizeof($tos);$i++) {
            if ($tos[$i]!="") {
              $pagetext .= "<OPTION VALUE=\"".$tos[$i]."\">";
              $pagetext .= get_first("users","name","id='".$tos[$i]."'","");
              $pagetext .= "\n";
            }
          }
        }
        $pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allclear\" VALUE=\"全て消去\" ONCLICK=\"clearAllUser(this.form)\">
</TD>
<TD ALIGN=CENTER VALIGN=MIDDLE>
<INPUT TYPE=BUTTON VALUE=\"&lt; 追加\" ONCLICK=\"addUser(this.form)\"><BR><BR>
<INPUT TYPE=BUTTON VALUE=\"削除 &gt;\" ONCLICK=\"removeUser(this.form)\"><BR><BR><BR>
</TD>
<TD VALIGN=TOP><SELECT NAME=\"users\" MULTIPLE SIZE=8 STYLE=\"width:140px\">
";

        $sql_user = "SELECT id,depa,post,name FROM users ORDER BY seqno";
        $res_user = pg_query($conn,$sql_user);
        $cnt_user = pg_num_rows($res_user);
        if ($cnt_user>0) {
          for ($i=0;$i<$cnt_user;$i++) {
            $row_user = pg_fetch_array($res_user,$i);
            if ($login_id != $row_user["id"]) { //自身を除外
              $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\" ";
              if ($send=="P" && preg_match("/(^|,)".$row_user["id"]."(,|$)/",$senddata)){
                $pagetext .= "selected";
              }
              $pagetext .= ">".$row_user["name"];
              $pagetext .= "</OPTION>\n";
            }
          }
        }

        $pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allcheck\" VALUE=\"全て選択\" ONCLICK=\"selectAllUser(this.form)\">
<INPUT TYPE=HIDDEN NAME=\"to\" VALUE=\"$to\">
</TD>
</TR>
</TABLE>
";
        $pagetext .= "</TD></TR></TABLE>";

        $pagetext .= "<BR>
<CENTER><INPUT TYPE=SUBMIT VALUE=\"メモの送信\" style=\"width:100px\"></CENTER>
</FORM>
";

      } else {
        //------------
        // メモの表示
        //------------
        if (get_first("mail_res","seqno","seqno=$n AND user_id='$login_id'",0)==0) {
          $sql = "INSERT INTO mail_res (seqno,user_id,createstamp) VALUES ($n,'$login_id','now')";
          pg_query($conn,$sql); // 既読処理
        }

        $sql_mail = "SELECT * FROM mail where seqno=".$n;
        $res_mail = pg_query($conn,$sql_mail);
        $cnt_mail = pg_num_rows($res_mail);

        if ($cnt_mail>0) {
          $row_mail = pg_fetch_array($res_mail,0);

          $bodys = split("\n",textsafe($row_mail["body"]));
          if (sizeof($bodys)>0) {
            while(list($key,$val)=each($bodys)) {
              $body .= "> ".$val."\n";
            }
          }
        }

        $pagetext .= "
<SCRIPT Language=\"JavaScript\">
<!--
function DelConf(seq) {
  if (seq>0) {
    if (confirm(\"削除しますか？\\n\\n注:一度削除した伝言を戻すことはできません\")) {
      window.open(\"/mail/del/?n=\"+seq,\"_self\");
    }
  }
}
function Send(seq,mode) {
  if (seq>0) {
    if (mode=='' || mode=='D' && confirm(\"削除しますか？\\n\\n注:一度削除した伝言を戻すことはできません\")) {
      window.open(\"./?tousers=".$row_mail["from"]."&s=\"+seq+\"&mode=\"+mode,\"_self\");
    }
  }
}
// -->
</SCRIPT>";

        $pagetext .= "<TR><TD VALIGN=TOP ALIGN=CENTER>";

        $pagetext .= "<DIV ALIGN=LEFT>";
        $pagetext .= "<FONT COLOR=#555555>発信者 : ";
        $pagetext .= "<A HREF=\"../../member/?id=".$row_mail["from"]."\">";
        $pagetext .= get_first("users","name_ryaku","id='".$row_mail["from"]."'","不明");
        $pagetext .= "<IMG SRC=\"../../image/clip.gif\" BORDER=0 WIDTH=10 HEIGHT=11 ALIGN=ABSMIDDLE>";
        $pagetext .= "</A>";
        $pagetext .= "</DIV>";

        $pagetext .= "<TABLE border=0 cellspacing=1 cellpadding=4 BGCOLOR=#666666 WIDTH=445>";

        $pagetext .= "<TR BGCOLOR=CCCCCC>
<TD ALIGN=RIGHT WIDTH=60 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;送信先&nbsp;</TD>
<TD ALIGN=LEFT NOWRAP BGCOLOR=$td_back>";

        $tos = split(",",$row_mail["to"]);
        if (sizeof($tos)>0) {;
          for ($i=0;$i<sizeof($tos);$i++) {;
            if ($tos[$i]!="") {
              $to_name = get_first("users","name_ryaku","id='".$tos[$i]."'","");
              if ($to_name!="") {
                $pagetext .= "<A HREF=\"../../member/?id=".$tos[$i]."\">$to_name</A><BR>\n";
              }
            }
          }
        }

        $pagetext .= "</TD></TR>";

        $pagetext .= "<TR BGCOLOR=CCCCCC>
<TD ALIGN=RIGHT WIDTH=60 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;優先度&nbsp;</TD>
<TD ALIGN=LEFT NOWRAP BGCOLOR=$td_back>
";
        if ($row_mail["priority"]==3) {
          $pagetext .= "<FONT COLOR=#FFEE00>●</FONT>&nbsp;普通";
        } elseif ($row_mail["priority"]==2) {
          $pagetext .= "<FONT COLOR=#FF6600>●</FONT>&nbsp;やや高";
        } else {
          $pagetext .= "<FONT COLOR=#FF0000>●</FONT>&nbsp;高";
        }

        $pagetext .= "</TD></TR>";

        $pagetext .= "<TR BGCOLOR=CCCCCC>
<TD ALIGN=RIGHT WIDTH=60 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;内容&nbsp;</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
";

        if ($row_mail["address_seqno"]>0) {
          $sql_addr = "SELECT * FROM address WHERE seqno=".$row_mail["address_seqno"];
          $res_addr = pg_query($conn,$sql_addr);
          $cnt_addr = pg_num_rows($res_addr);
          if ($cnt_addr>0) {
            $row_addr = pg_fetch_array($res_addr,0);
            $pagetext .= "<A HREF=\"../../address/edit/?s=".$row_mail["address_seqno"]."\">";
            $corp_name = $row_addr["corp_name"];
            $corp_name = ereg_replace("株式会社","",$corp_name);
            $corp_name = ereg_replace("有限会社","",$corp_name);
            $corp_name = ereg_replace("合資会社","",$corp_name);
            $corp_name = ereg_replace("合名会社","",$corp_name);
            $corp_name = ereg_replace("財団法人","",$corp_name);
            $corp_name = ereg_replace("社団法人","",$corp_name);
            $corp_name = ereg_replace("学校法人","",$corp_name);
            $corp_name = ereg_replace("宗教法人","",$corp_name);
            $corp_name = ereg_replace("特定非営利活動法人","",$corp_name);
            $corp_name = ereg_replace("NPO法人","",$corp_name);
            $corp_name = ereg_replace("社会福祉法人","",$corp_name);
            $corp_name = ereg_replace("公益法人","",$corp_name);
            $corp_name = ereg_replace("医療法人","",$corp_name);
            $corp_name = ereg_replace("事業協同組合","",$corp_name);
            $corp_name = ereg_replace("協同組合連合会","",$corp_name);
            $corp_name = ereg_replace("企業組合","",$corp_name);
            $corp_name = ereg_replace("協業組合","",$corp_name);
            $corp_name = ereg_replace("振興組合","",$corp_name);
            $corp_name = trim($corp_name);
            $corp_name = eregi_replace("　","",$corp_name);
            $pagetext .= $corp_name." ";
            $pagetext .= $row_addr["person_name"];
            $pagetext .= "</A> 様より<BR>";
          }
        }

        $w_body = str_link($row_mail["body"]);
        if ($mail_keyword!="") $w_body = str_highlight($mail_keyword,$w_body);
        $bodys = split("\r\n",$w_body);

        while (list($key,$text)=each($bodys)) {
          $pagetext .= $text."<BR>";
        }

        $pagetext .= "</TD></TR></TABLE>";

        $pagetext .= "<DIV ALIGN=RIGHT>";
        $pagetext .= "<FONT COLOR=#555555>発信日時 : ";
        $pagetext .= date("Y年m月d日 H時i分",datetime2timestamp($row_mail["createstamp"]));
        $pagetext .= "</DIV>";

        $pagetext .= "<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR><FORM>";

        if ($row_mail["from"] != $login_id) {
          $pagetext .= "
<TD><INPUT TYPE=button VALUE=\"返信\" onclick=\"Send($n,'')\" style=\"width:100px;background-color:#CCCCFF\"></TD>
<TD><INPUT TYPE=button VALUE=\"返信+削除\" onclick=\"Send($n,'D')\" style=\"width:100px;background-color:#FFCCFF\"></TD>";
        }

        $pagetext .= "
<TD><INPUT TYPE=button VALUE=\"削除\" onclick=\"DelConf($n)\" style=\"width:60px;background-color:#FFCCCC\"></TD>
</FORM></TR></TABLE>";

#      $pagetext .= "</TD></TR></TABLE>";
#      $pagetext .= "</TD></TR></TABLE>";

      }
      $pagetext .= "</TD></TR></TABLE>";
    }
  }
  include "../../detail.inc.php";
  include "../../footer.inc.php";
?>
