<?php
  include("../../config.inc.php"); include("../../lib.inc.php");
  include("../../login_check.inc.php");

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">メンバー一覧</A> &gt; ";
  $linktext .= "<A HREF=\"./\" CLASS=\"BAR\">プロフィール変更</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>マイグループ</FONT>";

  include "../../header.inc.php";
  flush();

  include "../menu.inc.php";

  if ($login && sizeof($MES)==0) {
    $pagetext .= "<CENTER><BR>\n";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><TD>\n";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR>\n";
    $pagetext .= "<TD ALIGN=CENTER WIDTH=100>\n";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 BGCOLOR=#999999 WIDTH=100 HEIGHT=19><TR>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=LEFT><IMG SRC=\"../../image/wr-l_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "<TD ALIGN=CENTER><A HREF=\"./\">個人情報</A>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=RIGHT><IMG SRC=\"../../image/wr-r_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "</TR></TABLE>\n";
    $pagetext .= "</TD>\n";
    $pagetext .= "<TD WIDTH=1></TD>\n";

    ## マイグループ
    $pagetext .= "<TD ALIGN=CENTER WIDTH=100>\n";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 BGCOLOR=#CCCCCC WIDTH=100 HEIGHT=19><TR>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=LEFT><IMG SRC=\"../../image/wr-l_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "<TD ALIGN=CENTER><FONT COLOR=".$bodyLinkColor."><B>マイグループ</B></FONT>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=RIGHT><IMG SRC=\"../../image/wr-r_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "</TR></TABLE>";
    $pagetext .= "</TD>";
    $pagetext .= "<TD WIDTH=1></TD>";

    ## パスワード
    $pagetext .= "<TD ALIGN=CENTER WIDTH=100>";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 BGCOLOR=#999999 WIDTH=100 HEIGHT=19><TR>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=LEFT><IMG SRC=\"../../image/wr-l_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "<TD ALIGN=CENTER><A HREF=\"./passwd.phtml\">パスワード</A>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=RIGHT><IMG SRC=\"../../image/wr-r_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "</TR></TABLE>";
    $pagetext .= "</TD>";
    $pagetext .= "<TD WIDTH=1></TD>";

    ## 表示変更
    $pagetext .= "<TD ALIGN=CENTER WIDTH=100>";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 BGCOLOR=#999999 WIDTH=100 HEIGHT=19><TR>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=LEFT><IMG SRC=\"../../image/wr-l_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "<TD ALIGN=CENTER><A HREF=\"./display.phtml\">表示変更</A>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=RIGHT><IMG SRC=\"../../image/wr-r_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "</TR></TABLE>";
    $pagetext .= "</TD>";
    $pagetext .= "<TD WIDTH=1></TD>";

    ## CSV出力
    $pagetext .= "<TD ALIGN=CENTER WIDTH=100>";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 BGCOLOR=#999999 WIDTH=100 HEIGHT=19><TR>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=LEFT><IMG SRC=\"../../image/wr-l_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "<TD ALIGN=CENTER><A HREF=\"./csv.phtml\">CSV出力</A>";
    $pagetext .= "<TD WIDTH=7 VALIGN=TOP ALIGN=RIGHT><IMG SRC=\"../../image/wr-r_t.gif\" WIDTH=7 HEIGHT=7></TD>";
    $pagetext .= "</TR></TABLE>";
    $pagetext .= "</TD>";
    $pagetext .= "</TR></TABLE>";

    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=504>";
    $pagetext .= "<TR><TD ALIGN=CENTER VALIGN=TOP BGCOLOR=#CCCCCC>";
    $pagetext .= "<FORM NAME=\"dialog\" ACTION=\"./update_mygroup.phtml\" METHOD=POST>";
    $pagetext .= "<BR>";

    $mygroup_ids = get_first("users","mygroup","id='".$login_id."'","");
    if ($mygroup_ids == ",") $mygroup_ids = "";
    $mygroup_ids = str_replace(",,",",",$mygroup_ids);
    $mygroup_ids_to = split(",",$mygroup_ids);

    ## ユーザー選択用JavaScript
    $pagetext .= "<SCRIPT LANGUAGE=\"JavaScript\">\n";
    $pagetext .= "<!--\n";
    $pagetext .= "//my = \"$login_id\";\n";
    $pagetext .= "dat_groups = new Array();\n";

    $sql_group = "SELECT id,name FROM groups LEFT JOIN (SELECT group_id FROM users_entry WHERE user_id='".$login_id."') as users_entry ON users_entry.group_id=groups.id WHERE NOT users_entry.group_id IS NULL OR viewsign='t' ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    $pagetext .= "cnt_groups = ".$cnt_group."\n";
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $sql_entry = "SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'";
        $res_entry = pg_query($conn,$sql_entry);
        $cnt_entry = pg_num_rows($res_entry);
        if ($res_entry>0) {
          $users_entry = "";
          for ($j=0;$j<$cnt_entry;$j++) {
            $row_entry = pg_fetch_array($res_entry,$j);
            if ($users_entry != "") $users_entry .= ",";
            $users_entry .= $row_entry["user_id"];
          }
        }
        if ($users_entry!="") {
          $pagetext .= "dat_groups[\"".$row_group["id"]."\"] = \"".$users_entry."\";\n";
        }
      }
    }
    $pagetext .= "dat_users = new Array();\n";
    $all_users = "";
    $sql_user = "SELECT id,name FROM users WHERE id<>'$login_id' ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);
    $pagetext .= "cnt_users = ".$cnt_user."\n";
    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        $pagetext .= "dat_users[\"".$row_user["id"]."\"] = \"".$row_user["name"]."\";\n";
        if ($i!=0) $all_users .= ",";
        $all_users .= $row_user["id"];
      }
    }
    $pagetext .= "dat_groups[\"all\"] = \"".$all_users."\";\n";
    $pagetext .= "function selectGroup(t) {\n";
    $pagetext .= "  group_id = t.selgroups[t.selgroups.selectedIndex].value;\n";
    $pagetext .= "  mygroup_ids = new Array();\n";
    $pagetext .= "\n";
    $pagetext .= "  t.users.length = 0;\n";
    $pagetext .= "\n";
    $pagetext .= "  if (group_id == '') {\n";
    $pagetext .= "  } else {\n";
    $pagetext .= "    if (dat_groups[group_id] != null) {\n";
    $pagetext .= "      mygroup_ids = dat_groups[group_id].split(',');\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  if (mygroup_ids.length>0) {\n";
    $pagetext .= "    c = 0;\n";
    $pagetext .= "    for (i=0;i<mygroup_ids.length;i++) {\n";
    $pagetext .= "//      if (mygroup_ids[i] != my) {\n";
    $pagetext .= "        t.users.length = t.users.length + 1;\n";
    $pagetext .= "        t.users.options[c].value = mygroup_ids[i];\n";
    $pagetext .= "        t.users.options[c].text  = dat_users[mygroup_ids[i]];\n";
    $pagetext .= "        c++;\n";
    $pagetext .= "//      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "\n";
    $pagetext .= "function clearAllUser(t) {\n";
    $pagetext .= "  for (i=0;i<t.elements.length;i++) {\n";
    $pagetext .= "    if (t.elements[i].name == \"mygroup_ids_to[]\") {\n";
    $pagetext .= "      var p = i;\n";
    $pagetext .= "      break;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  var o = t.elements[p];\n";
    $pagetext .= "  o.length = 0;\n";
    $pagetext .= "  t.mygroup_id_to.value = '';\n";
    $pagetext .= "}\n";
    $pagetext .= "\n";
    $pagetext .= "function selectAllUser(t) {\n";
    $pagetext .= "  if (t.users.length>0) {\n";
    $pagetext .= "    for (i=0;i<t.users.length;i++) {\n";
    $pagetext .= "      t.users.options[i].selected = true;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  t.allcheck.checked = false;\n";
    $pagetext .= "}\n";
    $pagetext .= "\n";
    $pagetext .= "function addUser(t) {\n";
    $pagetext .= "  for (i=0;i<t.elements.length;i++) {\n";
    $pagetext .= "    if (t.elements[i].name == \"mygroup_ids_to[]\") {\n";
    $pagetext .= "      var p = i;\n";
    $pagetext .= "      break;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  var o = t.elements[p];\n";
    $pagetext .= "\n";
    $pagetext .= "  s = t.mygroup_id_to.value;\n";
    $pagetext .= "  if (t.users.length>0) {\n";
    $pagetext .= "    for (i=0;i<t.users.length;i++) {\n";
    $pagetext .= "      if (t.users.options[i].selected) {\n";
    $pagetext .= "        t.users.options[i].selected = false;\n";
    $pagetext .= "        var id = t.users.options[i].value;\n";
    $pagetext .= "        var c = false;\n";
    $pagetext .= "        for(j=0;j<o.length;j++) {\n";
    $pagetext .= "          if (o.options[j].value == id) {\n";
    $pagetext .= "            c = true;\n";
    $pagetext .= "            break;\n";
    $pagetext .= "          }\n";
    $pagetext .= "        }\n";
    $pagetext .= "        if (!c) {\n";
    $pagetext .= "          if (o.length>0) s = s + ',';\n";
    $pagetext .= "          o.length = o.length + 1;\n";
    $pagetext .= "          o.options[o.length-1].value = id;\n";
    $pagetext .= "          o.options[o.length-1].text = dat_users[id];\n";
    $pagetext .= "          s = s + id;\n";
    $pagetext .= "        }\n";
    $pagetext .= "      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  t.mygroup_id_to.value = s;\n";
    $pagetext .= "}\n";
    $pagetext .= "\n";
    $pagetext .= "function removeUser(t) {\n";
    $pagetext .= "  for (i=0;i<t.elements.length;i++) {\n";
    $pagetext .= "    if (t.elements[i].name == \"mygroup_ids_to[]\") {\n";
    $pagetext .= "      var p = i;\n";
    $pagetext .= "      break;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  var o = t.elements[p];\n";
    $pagetext .= "  var val = new Array();\n";
    $pagetext .= "  var txt = new Array();\n";
    $pagetext .= "  var c = 0;\n";
    $pagetext .= "\n";
    $pagetext .= "  if (o.length>0) {\n";
    $pagetext .= "    for (i=0;i<o.length;i++) {\n";
    $pagetext .= "      if (!o.options[i].selected) {\n";
    $pagetext .= "        val[c] = o.options[i].value;\n";
    $pagetext .= "        txt[c] = o.options[i].text;\n";
    $pagetext .= "        c++;\n";
    $pagetext .= "      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "\n";
    $pagetext .= "    o.length = 0;\n";
    $pagetext .= "    s = '';\n";
    $pagetext .= "    if (c>0) {\n";
    $pagetext .= "      o.length = c;\n";
    $pagetext .= "      for (i=0;i<c;i++) {\n";
    $pagetext .= "        if (i>0) s = s + ',';\n";
    $pagetext .= "        o.options[i].value = val[i];\n";
    $pagetext .= "        o.options[i].text  = txt[i];\n";
    $pagetext .= "        s = s + val[i];\n";
    $pagetext .= "      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "    t.mygroup_id_to.value = s;\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";

    // Up/Down
    $pagetext .= "function UpUser(t) {\n";
    $pagetext .= "  for (i=0;i<t.elements.length;i++) {\n";
    $pagetext .= "    if (t.elements[i].name == \"mygroup_ids_to[]\") {\n";
    $pagetext .= "      var p = i;\n";
    $pagetext .= "      break;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  var o = t.elements[p];\n";
    $pagetext .= "  if ((o.length>1) && (0!=o.selectedIndex)) {\n";
    $pagetext .= "    var i = o.selectedIndex;\n";
    $pagetext .= "    var w_value = o.options[i].value;\n";
    $pagetext .= "    var w_text  = o.options[i].text\n";
    $pagetext .= "    o.options[i].value = o.options[i-1].value;\n";
    $pagetext .= "    o.options[i].text  = o.options[i-1].text\n";
    $pagetext .= "    o.options[i-1].value = w_value;\n";
    $pagetext .= "    o.options[i-1].text  = w_text\n";
    $pagetext .= "    o.selectedIndex = i-1\n";
    $pagetext .= "    s = '';\n";
    $pagetext .= "    for (i=0;i<o.length;i++) {\n";
    $pagetext .= "      if (i>0) s = s + ',';\n";
    $pagetext .= "      s = s + o.options[i].value;\n";
    $pagetext .= "    }\n";
    $pagetext .= "    t.mygroup_id_to.value = s;\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";

    $pagetext .= "function DownUser(t) {\n";
    $pagetext .= "  for (i=0;i<t.elements.length;i++) {\n";
    $pagetext .= "    if (t.elements[i].name == \"mygroup_ids_to[]\") {\n";
    $pagetext .= "      var p = i;\n";
    $pagetext .= "      break;\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "  var o = t.elements[p];\n";
    $pagetext .= "  if ((o.length>1) && (o.length-1!=o.selectedIndex)) {\n";
    $pagetext .= "    var i = o.selectedIndex;\n";
    $pagetext .= "    var w_value = o.options[i].value;\n";
    $pagetext .= "    var w_text  = o.options[i].text\n";
    $pagetext .= "    o.options[i].value = o.options[i+1].value;\n";
    $pagetext .= "    o.options[i].text  = o.options[i+1].text\n";
    $pagetext .= "    o.options[i+1].value = w_value;\n";
    $pagetext .= "    o.options[i+1].text  = w_text\n";
    $pagetext .= "    o.selectedIndex = i+1\n";
    $pagetext .= "    s = '';\n";
    $pagetext .= "    for (i=0;i<o.length;i++) {\n";
    $pagetext .= "      if (i>0) s = s + ',';\n";
    $pagetext .= "      s = s + o.options[i].value;\n";
    $pagetext .= "    }\n";
    $pagetext .= "    t.mygroup_id_to.value = s;\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "//-->\n";
    $pagetext .= "</SCRIPT>\n";

    $pagetext .= "<SCRIPT LANGUAGE=\"JavaScript\">\n";
    $pagetext .= "<!--\n";
    $pagetext .= "function selectfrom_h(t) {\n";
    $pagetext .= "  if (t.from_h[0].selected) {\n";
    $pagetext .= "    t.from_m[0].selected = true;\n";
    $pagetext .= "  } else {\n";
    $pagetext .= "    if (t.from_m[0].selected == true) t.from_m[1].selected = true;\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "function selectto_h(t) {\n";
    $pagetext .= "  if (t.to_h[0].selected) {\n";
    $pagetext .= "    t.to_m[0].selected = true;\n";
    $pagetext .= "  } else {\n";
    $pagetext .= "    if (t.to_m[0].selected == true) t.to_m[1].selected = true;\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "// -->\n";
    $pagetext .= "</SCRIPT>\n";

    $pagetext .= "<SCRIPT LANGUAGE=\"JavaScript\">\n";
    $pagetext .= "<!--\n";
    $pagetext .= "function selectuser(f,o) {\n";
    $pagetext .= "  if (o.options[o.selectedIndex].value != \"\") {\n";
    $pagetext .= "    var c = 0;\n";
    $pagetext .= "    var k = new Array(o.length-1);\n";
    $pagetext .= "    var v = new Array(o.length-1);\n";
    $pagetext .= "    for (i=0;i<o.length;i++) {\n";
    $pagetext .= "      if (i != o.selectedIndex) {\n";
    $pagetext .= "        k[c] = o.options[i].value;\n";
    $pagetext .= "        v[c] = o.options[i].text;\n";
    $pagetext .= "        c++;\n";
    $pagetext .= "      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "    o.length = o.length-1;\n";
    $pagetext .= "    f.tousers.value = \"\";\n";
    $pagetext .= "    for (i=0;i<c;i++) {\n";
    $pagetext .= "      o.options[i].value = k[i];\n";
    $pagetext .= "      o.options[i].text  = v[i];\n";
    $pagetext .= "      if (f.tousers.value==\"\") {\n";
    $pagetext .= "        f.tousers.value = k[i];\n";
    $pagetext .= "      } else {\n";
    $pagetext .= "        f.tousers.value = f.tousers.value+\"\t\"+k[i];\n";
    $pagetext .= "      }\n";
    $pagetext .= "    }\n";
    $pagetext .= "  }\n";
    $pagetext .= "}\n";
    $pagetext .= "//-->\n";
    $pagetext .= "</SCRIPT>\n";

    $pagetext .= "<TABLE BORDER=0 CELLPADDING=5><TR><TD>\n";
    $pagetext .= "<FONT STYLE=\"font-size:8pt\">";
    $pagetext .= "ユーザーリストを修正して「更新の実行」ボタンを押してください。<BR>\n";
    $pagetext .= "</TD></TR></TABLE>\n";

    $pagetext .= "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 BGCOLOR=#999999>\n";
    ## マイグループの表示
    $pagetext .= "<TR STYLE=\"LINE-HEIGHT:16pt\">\n";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back_left ALIGN=CENTER>マイグループメンバー<BR>";
    $pagetext .= "<FONT STYLE=\"FONT-SIZE:7pt;COLOR:#555555;LINE-HEIGHT:10pt\">";
    $pagetext .= "&nbsp;マイグループは予定表の表示で利用されるあなた専用のリストです。<BR>";
    $pagetext .= "</TD></TR>\n";
    $pagetext .= "<TR STYLE=\"LINE-HEIGHT:16pt\">\n";
    $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>";
    $pagetext .= "<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0>";
    $pagetext .= "<TR><TD COLSPAN=5>&nbsp;</TD><TD>";
    $pagetext .= "<SELECT NAME=\"selgroups\" ONCHANGE=\"selectGroup(this.form)\" STYLE=\"width:120px\">\n";
    $pagetext .= "<OPTION VALUE=\"\" SELECTED>グループ未選択\n";
    $pagetext .= "<OPTION VALUE=\"\">--------------\n";
    $sql_group = "SELECT id,name FROM groups LEFT JOIN (SELECT group_id FROM users_entry WHERE user_id='".$login_id."') as users_entry ON users_entry.group_id=groups.id WHERE NOT users_entry.group_id IS NULL OR viewsign='t' ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
        if (pg_num_rows($res_entry)>0) {
          $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\">".$row_group["name"];
          $pagetext .= "\n";
        }
      }
    }
    $pagetext .= "</SELECT>\n";
    $pagetext .= "</TD>\n";
    $pagetext .= "</TR>\n";
    $pagetext .= "<TR><TD>";
    $pagetext .= "<INPUT TYPE=BUTTON NAME=\"up\" VALUE=\"↑\" ONCLICK=\"UpUser(this.form)\"><BR>";
    $pagetext .= "<INPUT TYPE=BUTTON NAME=\"down\" VALUE=\"↓\" ONCLICK=\"DownUser(this.form)\"><BR><BR><BR>";
    $pagetext .= "</TD><TD VALIGN=MIDDLE>";
    $pagetext .= "<SELECT NAME=\"mygroup_ids_to[]\" SIZE=8 STYLE=\"width:140px\">\n";
    if (sizeof($mygroup_ids_to)>0) {
      for ($i=0;$i<sizeof($mygroup_ids_to);$i++) {
        if ($mygroup_ids_to[$i]!="" && get_count("users","id='".$mygroup_ids_to[$i]."'")>0) {
          $pagetext .= "<OPTION VALUE=\"".$mygroup_ids_to[$i]."\">";
          $pagetext .= get_first("users","name","id='".$mygroup_ids_to[$i]."'","");
          $pagetext .= "\n";
        }
      }
    }
    $pagetext .= "</SELECT><BR>";
    $pagetext .= "<INPUT TYPE=BUTTON NAME=\"allclear\" VALUE=\"全て消去\" ONCLICK=\"clearAllUser(this.form)\">";
    $pagetext .= "</TD>";
    $pagetext .= "<TD>&nbsp</TD>";
    $pagetext .= "<TD ALIGN=CENTER VALIGN=MIDDLE>";
    $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"&lt; 追加\" ONCLICK=\"addUser(this.form)\"><BR><BR>";
    $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"削除 &gt;\" ONCLICK=\"removeUser(this.form)\"><BR><BR><BR>";
    $pagetext .= "</TD>";
    $pagetext .= "<TD>&nbsp</TD>";
    $pagetext .= "<TD VALIGN=TOP><SELECT NAME=\"users\" MULTIPLE SIZE=8 STYLE=\"width:140px\">\n";
#    $sql_user = "SELECT id,depa,post,name FROM users ORDER BY seqno";
#    $res_user = pg_query($conn,$sql_user);
#    $cnt_user = pg_num_rows($res_user);
#    if ($cnt_user>0) {
#      for ($i=0;$i<$cnt_user;$i++) {
#        $row_user = pg_fetch_array($res_user,$i);
#        if ($login_id != $row_user["id"]) { //自身を除外
#          $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\" ";
#          if ($sendtype=="P" && preg_match("/(^|,)".$row_user["id"]."(,|$)/",$senddata)){
#            $pagetext .= "selected";
#          }
#          $pagetext .= ">".$row_user["name"];
#          $pagetext .= "</OPTION>\n";
#        }
#      }
#    }
    $pagetext .= "</SELECT><BR>";
    $pagetext .= "<INPUT TYPE=BUTTON NAME=\"allcheck\" VALUE=\"全て選択\" ONCLICK=\"selectAllUser(this.form)\">";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"mygroup_id_to\" VALUE=\"".$mygroup_ids."\">";
    $pagetext .= "</TD></TR></TABLE>\n";
    $pagetext .= "</TD>\n";
    $pagetext .= "</TR>\n";
    $pagetext .= "</TABLE>\n";

    $pagetext .= "<BR>\n";
    $pagetext .= "<INPUT TYPE=CHECKBOX NAME=\"topsign\" VALUE=\"t\"";
    $topsign = get_first("users","mygrouptopsign","id='".$login_id."'","f");
    if ($topsign=="t") $pagetext .= " CHECKED";
    $pagetext .= ">トップページの予定表にマイグループメンバー分も表示する<BR>\n";
    $pagetext .= "<BR>\n";
    $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"更新の実行\">\n";
    $pagetext .= "</FORM>";
    $pagetext .= "</TD></TR></TABLE>\n";
    $pagetext .= "<BR></CENTER>";
  }
  include "../../detail.inc.php";
  include "../../footer.inc.php";
?>