<?php
  include("../../config.inc.php"); include("../../lib.inc.php");
  include("../../login_check.inc.php");

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">メンバー一覧</A> &gt; ";
  $linktext .= "<A HREF=\"./\" CLASS=\"BAR\">プロフィール変更</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>パスワード変更</FONT>";

  if ($login && sizeof($MES)==0) {
    $old_passwd = trim($old_passwd);
    $old_chkpw  = trim($old_chkpw);
    $new_passwd = trim($new_passwd);
    $new_chkpw  = trim($new_chkpw);

    // ユーザー確認
    $sql = "select * from users where id='".$login_id."'";
    $res = pg_query($conn,$sql);
    if (pg_num_rows($res)==0) {
      $DMES[] = "ユーザー情報の確認失敗しました";
    }
    // エラーチェック
    if (empty($old_passwd)) {
      $DMES[] = "古いパスワードが入力されていません";
    } else {
      $old_pwd_cr = crypt(textsafe($old_passwd),substr(textsafe($old_passwd),1,2));
      if ($old_pwd_cr != $old_chkpw){
        $DMES[] = "古いパスワードが正しくありません";
      }
    }
    if ($new_passwd == ""){
      $DMES[] = "パスワードが入力されていません";
    } elseif(strlen($new_passwd)<6) {
      $DMES[] = "パスワードの入力が短すぎます";
    } elseif(strlen($new_passwd)>12) {
      $DMES[] = "パスワードの入力が長すぎます";
    } elseif(!preg_match("/^[\w\|]+$/i",$new_passwd)) {
      $DMES[] = "パスワードは英字または数字で指定してください";
    }
    if ($new_chkpw == ""){
      $DMES[] = "パスワード(確認用) が入力されていません";
    }
    if (sizeof($DMES)==0) {
      if ($new_passwd <> $new_chkpw){
        $DMES[] = "新しいパスワードと確認用のパスワードが一致しません";
      }
    }

    // 更新
    if (sizeof($DMES)==0) {
      $pwd_cr = crypt(db_textsafe($new_passwd),substr(db_textsafe($new_passwd),1,2));

      $sql  = "UPDATE users SET ";
      $sql .= "passwd ='".$pwd_cr."',";
      $sql .= "passwd_updatestamp ='now',";
      $sql .= "updatestamp ='now'";
      $sql .= " WHERE seqno=$seqno AND id='$login_id'";
      // SQL実行
      $res = pg_query($conn, $sql);
      if ($res==false || pg_affected_rows($res)==0) {
        $DMES[] = "パスワードの更新に失敗しました";
      }
    }
  }

  // 表示or戻り
  if (sizeof($DMES)>0) {
    // エラーメッセージ出力
    include("../../header.inc.php");
    include("../menu.inc.php");
    $pagetext .= "<TABLE BORDER=0 WIDTH=100%><FORM><TR><TD ALIGN=CENTER><FONT COLOR=#FF0000>";
    $pagetext .= "<BR>";
    while (list($key,$val)=each($DMES)) {
      $pagetext .= $val."<BR>\n";
    }
    $pagetext .= "<BR>";
    $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" ONCLICK=\"history.back()\">";
    $pagetext .= "</TD></TR></FORM></TABLE>\n";
    include("../../detail.inc.php");
    include("../../footer.inc.php");
  } else {
    // 正常時
    header("Location: ./passwd.phtml");
  }
?>