<?
  include "../../config.inc.php";
  include "../../lib.inc.php";

  $linktext  = "<A HREF=\"/\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"/member/\" CLASS=\"BAR\">メンバー一覧</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>行き先登録</FONT>";

  include "../../header.inc.php";

  if ($login) {
    // 登録ページからの戻り判定
    if (eregi("update\.phtml",$referer)){
      $code = $_POST["code"];
      $text = $_POST["text"];
    } else {
      $sql = "SELECT * FROM users_location WHERE user_id='".$login_id."' ORDER BY updatestamp DESC";
      $res = pg_query($conn,$sql);
      $cnt = pg_num_rows($res);
      if ($cnt==0) {
        $code = "1";
        $text = "在席";
      } else {
        $row = pg_fetch_array($res,0);
        $code = $row["code"];
        $text = $row["text"];
      }
      $codetext = get_first("locations","name","id='$code'","");
      if ($codetext==$text) {
        $text = "";
      }
    }

    if (sizeof($DMES)>0) {
      // エラーメッセージ出力
      $pagetext .= "<TABLE WIDTH=100% HEIGHT=350 BORDER=0><TR><TD ALIGN=CENTER VALIGN=TOP>\n";
      $pagetext .= "<FORM>\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
      $pagetext .= "<FONT COLOR=#FF0000>\n";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>\n";
      }
      $pagetext .= "</FONT><BR><BR>\n";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" onClick=\"history.back()\">\n";
      $pagetext .= "</FORM>\n";
      $pagetext .= "</TD></TR></TABLE>\n";
    } else {
      $pagetext .= "<BR>
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=0 ALIGN=CENTER WIDTH=420>
<FORM ACTION=\"./update.phtml\" METHOD=POST>
";
      // 正常処理
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
      $pagetext .= "<TR><TD COLSPAN=2 ALIGN=CENTER>";
      $pagetext .= "各項目を入力して登録ボタンを押してください";
      $pagetext .= "</TD></TR>\n";
      $pagetext .= "<TR><TD ALIGN=RIGHT ALIGN=RIGHT>\n";
      $pagetext .= "</TD></TR>\n";

      $pagetext .= "<TR><TD VALIGN=TOP ALIGN=CENTER COLSPAN=2>\n";
      $pagetext .= "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 WIDTH=100% BGCOLOR=#999999>\n";

      ## 行き先
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>行き先</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";

      $sql_loc = "SELECT * FROM locations ORDER BY seqno";
      $res_loc = pg_query($conn,$sql_loc);
      $cnt_loc = pg_num_rows($res_loc);
      if ($cnt_loc>0) {
        for($i=0;$i<$cnt_loc;$i++) {
          $row_loc = pg_fetch_array($res_loc,$i);
          $pagetext .= "<INPUT TYPE=RADIO NAME=\"code\" VALUE=\"".$row_loc["id"]."\"";
          if ($row_loc["id"]==$code) {
            $pagetext .= " CHECKED";
          }
          $pagetext .= ">";
          $pagetext .= $row_loc["name"];
          $pagetext .= "<BR>";
//          $pagetext .= "</OPTION>";
        }
      }
      $pagetext .= "<INPUT TYPE=RADIO NAME=\"code\" VALUE=\"-1\"";
      if ($text!="") $pagetext .= " CHECKED";
      $pagetext .= ">";
      $pagetext .= "その他(手入力) ";
#      $pagetext .= "</SELECT> ";

      $pagetext .= "\n<SCRIPT LANGUAGE=\"JavaScript\">\n";
      $pagetext .= "<!--\n";
      $pagetext .= "function inputtext(f) {\n";
      $pagetext .= "  f.code[f.code.length-1].checked = true;\n";
      $pagetext .= "}\n";
      $pagetext .= "//-->\n";
      $pagetext .= "</SCRIPT>\n";

      $pagetext .= "<INPUT TYPE=TEXT NAME=\"text\" SIZE=34 VALUE=\"$text\" STYLE=\"ime-mode:active\" ONCLICK=\"inputtext(this.form)\">\n";
      $pagetext .= "</TD></TR>\n";

      ## ボタン関連
      $pagetext .= "<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR>\n";
      $pagetext .= "<TD><INPUT TYPE=SUBMIT VALUE=\"登録\" STYLE=\"WIDTH:140px\"></TD>\n";
    }
    $pagetext .= "</TR></TABLE>\n";
    $pagetext .= "</FORM>\n";
  }

  include "../../detail.inc.php";
  include "../../footer.inc.php";
?>
