<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";

  if (!empty($_REQUEST["p"]))     $p     = $_REQUEST["p"];
  if (!empty($_REQUEST["id"]))    $id    = $_REQUEST["id"];
  if (!empty($_REQUEST["seqno"])) $seqno = $_REQUEST["seqno"];

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>グループ設定</FONT> ";

  include "../../header.inc.php";
  flush();

  include "../menu.inc.php";

  if ($login && $admin_sign=="t") {
    print "<!--";
    $pagetext = "";
    $pagetext .= "
<SCRIPT LANGUAGE=\"JavaScript\">
<!--
dat_groups = new Array();
";
    $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    $pagetext .= "cnt_groups = ".$cnt_group."\n";
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."'");
        $cnt_entry = pg_num_rows($res_entry);

        if ($res_entry>0) {
          $users_entry = "";
          for ($j=0;$j<$cnt_entry;$j++) {
            $row_entry = pg_fetch_array($res_entry,$j);

            if ($users_entry != "") $users_entry .= ",";
            $users_entry .= $row_entry["user_id"];
          }
        }
        if ($users_entry!="") {
          $pagetext .= "dat_groups[\"".$row_group["id"]."\"] = \"".$users_entry."\";\n";
        }
      }
    }

    $pagetext .= "
dat_users = new Array();
";
    $all_users = "";

    $sql_user = "SELECT id,name FROM users ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);
    $pagetext .= "cnt_users = ".$cnt_user."\n";
    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        $pagetext .= "dat_users[\"".$row_user["id"]."\"] = \"".$row_user["name"]."\";\n";
        if ($i!=0) $all_users .= ",";
        $all_users .= $row_user["id"];
      }
    }

    $pagetext .= "dat_groups[\"all\"] = \"".$all_users."\";\n";

    $pagetext .= "
function delConfirm(seqno,id) {
  if (confirm(\"このグループ情報を削除しますか？\\n注:一度削除したグループ情報は元に戻すことはできません\")) {
    window.open('./delete.phtml?seqno='+seqno+'&id='+id+'&p=".$p."','_self');
  }
}

function selectGroup(t) {
  group_id = t.groups[t.groups.selectedIndex].value;
  user_ids = new Array();

  t.users.length = 0;

  if (group_id == '') {
    user_ids = dat_groups['all'].split(',');
  } else {
    if (dat_groups[group_id] != null) {
      user_ids = dat_groups[group_id].split(',');
    }
  }
  if (user_ids.length>0) {
    for (i=0;i<user_ids.length;i++) {
      t.users.length = t.users.length + 1;
      t.users.options[i].value = user_ids[i];
      t.users.options[i].text  = dat_users[user_ids[i]];
    }
  }
}

function selectAllUser(t) {
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      t.users.options[i].selected = true;
    }
  }
  t.allcheck.checked = false;
}

function addUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"users_entry[]\") {
      var p = i;
      break;
    }
  }
  var o = t.elements[p];

  s = t.user_entry.value;
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      if (t.users.options[i].selected) {
        t.users.options[i].selected = false;
        var id = t.users.options[i].value;
        var c = false;
        for (j=0;j<o.length;j++) {
          if (o.options[j].value == id) {
            c = true;
            break;
          }
        }
        if (!c) {
          if (o.length>0) s = s + ',';
          o.length = o.length + 1;
          o.options[o.length-1].value = id;
          o.options[o.length-1].text = dat_users[id];
          s = s + id;
        }
      }
    }
  }
  t.user_entry.value = s;
}

function removeUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"users_entry[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  var val = new Array();
  var txt = new Array();
  var c = 0;
  
  if (o.length>0) {
    for (i=0;i<o.length;i++) {
      if (!o.options[i].selected) {
        val[c] = o.options[i].value;
        txt[c] = o.options[i].text;
        c++;
      }
    }

    o.length = 0;
    s = '';
    if (c>0) {
      o.length = c;
      for (i=0;i<c;i++) {
        if (i>0) s = s + ',';
        o.options[i].value = val[i];
        o.options[i].text  = txt[i];
        s = s + val[i];
      }
    }
    t.user_entry.value = s;
  }
}
//-->
</SCRIPT>

<BR><CENTER>
";

    if (!empty($_POST["back"]) && $_POST["back"] == "t") {
      // 更新ページからの戻り(エラー)時
      $seqno    = stripslashes($_POST["seqno"]);
      $id       = stripslashes($_POST["id"]);
      $old_id   = stripslashes($_POST["old_id"]);
      $name     = stripslashes($_POST["name"]);
      $viewsign = stripslashes($_POST["viewsign"]);
    } else {
      // SELECT条件の指定
      if ((!empty($_REQUEST["seqno"]) && is_numeric($_REQUEST["seqno"])) && !empty($_REQUEST["id"]))  {
        $sql = "SELECT * FROM groups WHERE seqno=".$_REQUEST["seqno"]." AND id='".$_REQUEST["id"]."'";
        $res = pg_query($conn, $sql);
        $cnt = pg_num_rows($res);
      } else {
        $cnt = 0;
      }

      if ($cnt>0) {
        $row      = pg_fetch_array($res, 0);
        $seqno    = $row["seqno"];
        $id       = $row["id"];
        $old_id   = $row["id"];
        $name     = $row["name"];
        $viewsign = $row["viewsign"];
      } else {
        $seqno    = "";
        $id       = "";
        $passwd   = "";
        $name     = "";
        $viewsign = "t";
      }

    }

    if ($_POST["user_entry"] != "") {
      $user_entry = $_POST["user_entry"];
      $entrys = split(",",$user_entry);
    } else {
      if ($id != "") {
        $sql_entry = "SELECT users.id FROM users_entry LEFT JOIN users ON users_entry.user_id = users.id WHERE users_entry.group_id='$id' ORDER BY users.seqno";
        $res_entry = pg_query($conn,$sql_entry);
        $cnt_entry = pg_num_rows($res_entry);

        if ($cnt_entry>0) {
          for ($i=0;$i<$cnt_entry;$i++) {
            $row_entry = pg_fetch_array($res_entry,$i);
            $entrys[] = $row_entry["id"];

            if ($user_entry != "") $user_entry .= ",";
            $user_entry .= $row_entry["id"];
          }
        }
      } else {
        $entrys = array();
        $cnt_entry = 0;
      }
    }

    //テーブル出力
    $pagetext .= "<TABLE BGCOLOR=#999999 BORDER=0 CELLPADDING=3 CELLSPACING=1>\n";
    $pagetext .= "<FORM ACTION=\"./update.phtml\" METHOD=POST>\n";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">\n";
    if (!empty($seqno)) {
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$seqno\">\n";
    }
    ## グループID
    $pagetext .= "<TR><TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;ＩＤ&nbsp;</TH>";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"old_id\" VALUE=\"$old_id\">\n";
    $pagetext .= "<INPUT TYPE=TEXT NAME=\"id\" SIZE=11 MAXLENGTH=10 VALUE=\"$id\" STYLE=\"ime-mode:disabled\">";
    $pagetext .= "<BR><FONT STYLE=\"font-size:7pt;COLOR:#555555\">半角英数字2〜10文字\n";
    $pagetext .= "</TD></TR>\n";

    ## グループ名
    $pagetext .= "<TR><TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;グループ名&nbsp;</TH>";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    $pagetext .= "<INPUT TYPE=TEXT NAME=\"name\" SIZE=41 MAXLENGTH=30 VALUE=\"$name\">\n";
    $pagetext .= "<BR><FONT STYLE=\"font-size:7pt;COLOR:#555555\">全角15文字（半角30文字）以内\n";
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "<TR><TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;公開&nbsp;</TH>";
    $pagetext .= "<TD NOWRAP BGCOLOR=$td_back>";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"viewsign\" VALUE=\"t\"";
    if ($viewsign=="t") $pagetext .= " CHECKED";
    $pagetext .= ">する\n";
    $pagetext .= "<INPUT TYPE=RADIO NAME=\"viewsign\" VALUE=\"f\"";
    if ($viewsign=="f") $pagetext .= " CHECKED";
    $pagetext .= ">しない\n";
    $pagetext .= "<BR><FONT STYLE=\"font-size:7pt;COLOR:#555555\">公開グループに参加している利用者は、予定が全員から閲覧可能となります。<BR>但し、予定の内容非公開・日時非公開は登録時に選択可能です。\n";
    $pagetext .= "</TD></TR>\n";

    $pagetext .= "
<TR>
<TH ALIGN=RIGHT NOWRAP BGCOLOR=$td_back_left>&nbsp;参加者&nbsp;</TH>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=2>
<TR>
<TD COLSPAN=2>&nbsp;</TD>
<TD><SELECT NAME=\"groups\" ONCHANGE=\"selectGroup(this.form)\" STYLE=\"width:120px\">\n";
    $pagetext .= "<OPTION VALUE=\"\" SELECTED>全て\n";
    $pagetext .= "<OPTION VALUE=\"\">------------\n";

    $sql_group = "SELECT id,name FROM groups ORDER BY seqno";
    $res_group = pg_query($conn,$sql_group);
    $cnt_group = pg_num_rows($res_group);
    if ($cnt_group>0) {
      for ($i=0;$i<$cnt_group;$i++) {
        $row_group = pg_fetch_array($res_group,$i);
        $res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."'");
        if (pg_num_rows($res_entry)>0) {
          $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\">".$row_group["name"];
          $pagetext .= "\n";
        }
      }
    }

    $pagetext .= "</SELECT>
</TD>
</TR>";

    $pagetext .= "
<TR>
<TD VALIGN=TOP><SELECT NAME=\"users_entry[]\" SIZE=8 STYLE=\"width:140px\">\n";
    if (sizeof($entrys)>0) {
      for ($i=0;$i<sizeof($entrys);$i++) {
        if ($entrys[$i]!="") {
          $pagetext .= "<OPTION VALUE=\"".$entrys[$i]."\">";
          $pagetext .= get_first("users","name","id='".$entrys[$i]."'","");
          $pagetext .= "\n";
        }
      }
    }
    $pagetext .= "</SELECT>
</TD>
<TD ALIGN=CENTER VALIGN=MIDDLE>
<INPUT TYPE=BUTTON VALUE=\"&lt; 追加\" ONCLICK=\"addUser(this.form)\"><BR><BR>
<INPUT TYPE=BUTTON VALUE=\"削除 &gt;\" ONCLICK=\"removeUser(this.form)\"><BR><BR><BR>
</TD>
<TD VALIGN=TOP><SELECT NAME=\"users\" MULTIPLE SIZE=8 STYLE=\"width:140px\">\n";

    $sql_user = "SELECT id,depa,post,name FROM users ORDER BY seqno";
    $res_user = pg_query($conn,$sql_user);
    $cnt_user = pg_num_rows($res_user);

    if ($cnt_user>0) {
      for ($i=0;$i<$cnt_user;$i++) {
        $row_user = pg_fetch_array($res_user,$i);
        $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\" ";
        if ($sendtype=="P" && preg_match("/(^|,)".$row_user["id"]."(,|$)/",$senddata)){
          $pagetext .= "selected";
        }
        $pagetext .= ">".$row_user["name"];
        $pagetext .= "</OPTION>\n";
      }
    }
    $pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allcheck\" VALUE=\"全て選択\" ONCLICK=\"selectAllUser(this.form)\">
<INPUT TYPE=HIDDEN NAME=\"user_entry\" VALUE=\"$user_entry\">
</TD></TR>

</TABLE>
</TD></TR>";

    $pagetext .= "</TABLE>\n";

    $pagetext .= "<BR>\n";

    if (!empty($_REQUEST["seqno"])) {
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"更新する\" STYLE=\"width:80px\">&nbsp;";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"削除\" onclick=\"delConfirm(".$_REQUEST["seqno"].",'".$id."')\">\n";
    } else {
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"登録する\" STYLE=\"width:80px\">";
    }
    $pagetext .= "</FORM>\n";

    $pagetext .= "</CENTER>\n";
    print "-->";
  }
  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>