<?php
  include ("../../config.inc.php"); include ("../../lib.inc.php");

  include ("../template.inc.php");

  $kwd = stripslashes(urldecode($_COOKIE["workflow_kwd"]));

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">ワークフロー</A> &gt; ";
  if (empty($no)) {
    $linktext .= "<FONT COLOR=#FFFF00>新しい案件</FONT> ";
  } else {
    $linktext .= "<FONT COLOR=#FFFF00>案件の表示</FONT> ";
  }

  include ("../../login_check.inc.php");

  if ($login && sizeof($MES)==0) {
    // 前処理
    $no = $_POST["no"];

    if (empty($no)) {
#      $DMES[] = "案件が選択されていません";
#      if ($_POST["error"]=="t") {
        $subject  = textsafe($_POST["subject"]);
        $body1    = textsafe($_POST["body1"]);
        $body2    = textsafe($_POST["body2"]);
        $body3    = textsafe($_POST["body3"]);
        $body4    = textsafe($_POST["body4"]);
        $body5    = textsafe($_POST["body5"]);
        $flow_pat = $_POST["flow_pat"];
#        $flow_ids = $_POST["flow_ids"];
#      }
    } else {
      $sql = "SELECT * FROM workflow WHERE user_id='$login_id' AND seqno=$no";
      $res = pg_query($conn,$sql);
      $cnt = pg_num_rows($res);
      if ($cnt==0) {
        // 案件なし
        $DMES[] = "指定された案件は登録されていないか既に削除されています";
      } else {
        // 案件の取得
        $row = pg_fetch_array($res,0);
        $subject  = textsafe($row["subject"]);
        $body1    = textsafe($row["body1"]);
        $body2    = textsafe($row["body2"]);
        $body3    = textsafe($row["body3"]);
        $body4    = textsafe($row["body4"]);
        $body5    = textsafe($row["body5"]);
        $flow_pat = $row["flow_pat"];
        $flow_ids = $row["flow_ids"];
      }
    }

    $check = $_POST["check"];

    if ($check=="t") {
      if (trim($subject)=="") {
        $WMES[] = "件名が入力されていません";
      } elseif(strlen($subject)>80) {
        $WMES[] = "件名が長すぎます。全角40文字までで入力してください";
        $subject = mb_strcut($subject,0,80);
      }

      if ($input1) {
        if (trim($body1)=="") {
          if ($sign1) $WMES[] = $title1."が入力されていません";
        } elseif(strlen($body1)>10000) {
          $WMES[] = $title1."が長すぎます。全角5000文字までで入力してください";
          $body1 = mb_strcut($body1,0,10000);
        }
      }
      if ($input2) {
        if (trim($body2)=="") {
          if ($sign2) $WMES[] = $title2."が入力されていません";
        } elseif(strlen($body2)>200) {
          $WMES[] = $title2."が長すぎます。全角100文字までで入力してください";
          $body2 = mb_strcut($body2,0,100);
        }
      }
      if ($input3) {
        $body3 = mb_convert_kana($body3,"aKV","EUC-JP");
        if (trim($body3)=="") {
          if ($sign3) $WMES[] = $title3."が入力されていません";
        } elseif (!is_numeric($body3)) {
          if ($sign3) $WMES[] = $title3."は数字で入力してください";
        } elseif(strlen($body3)>20) {
          $WMES[] = $title3."が長すぎます。半角数字で20文字までで入力してください";
          $body3 = mb_strcut($body3,0,10000);
        }
      }
      if ($input4) {
        if (trim($body4)=="") {
          if ($sign4) $WMES[] = $title4."が入力されていません";
        } elseif(strlen($body4)>10000) {
          $WMES[] = $title4."が長すぎます。全角5000文字までで入力してください";
          $body4 = mb_strcut($body4,0,10000);
        }
      }
#      if ($input5) {
#        if (trim($body5)=="") {
#          if ($sign5) $WMES[] = $title5."が入力されていません";
#        } elseif(strlen($body5)>10000) {
#          $WMES[] = $title5."が長すぎます。全角5000文字までで入力してください";
#          $body5 = mb_strcut($body5,0,10000);
#        }
#      }

      if ($flow_pat=="") {
        $WMES[] = "フロータイプが選択されていません";
      } else {
        if (get_first("flows","seqno","seqno=$flow_pat",0)<1) {
          $DMES[] = "フロータイプが正しく選択されていません";
        } else {
          $flow_ids = get_first("flows","user_ids","id=$flow_pat","");
          if ($flow_ids=="") {
            $DMES[] = "フロータイプの設定が正しくないため現在利用できません";
          }
        }
      }
    }

    if($_FILES["file1"]["size"]==0) {
#      $DMES[] = "アップロードファイルが設定されていません。<br>";
    } else {
      if($_FILES["file1"]["size"] > $upload_max) { //
        $DMES[] = "アップロードファイルのサイズが大きすぎます（アップロードするファイルは".floor($upload_max/1024/1000)."MB以内に調整して下さい）";
      } else {
        $filename = stripslashes($_FILES["file1"]["name"]);

        $pos_sepa = strrpos($filename, "\\");
        $pos_dot  = strrpos($filename, ".");
        if ($pos_sepa>0 || $pos_dot>0) {
          if ($pos_sepa>0) {
            $file1_orgname = substr($filename,$pos_sepa + 1);
          } else {
            $file1_orgname = $filename;
          }
          if ($pos_dot>0) {
            $file1_orgext  = substr($filename,$pos_dot + 1);
          } else {
            $file1_orgext  = "";
          }
        } else {
          $file1_orgname = $filename;
          $file1_orgext  = "";
        }
      }

      if ($file1_orgname != sjis2euc(euc2sjis($file1_orgname))) {
        $DMES[] = "添付ファイル[1]のファイル名が正しくありません<BR>（ファイル名に利用できない文字が使用されているか漢字コードの変換に失敗しました）";
      } elseif (substr($file1_orgname,0,1)==".") {
        $DMES[] = "添付ファイル[1]のファイル名が正しくありません<BR>（.[ドット]ではじまるファイル名が使用されているか、漢字コードの変換に失敗しました）";
      } else {
        $p = strrpos($file1_orgname,".");
        if ($p==0) { // 拡張子あり？
          $DMES[] = "添付ファイル[1]は拡張子が正しく指定されていません";
        }
      }
    }

    if($_FILES["file2"]["size"]==0) {
#      $DMES[] = "アップロードファイルが設定されていません。<br>";
    } else {
      if($_FILES["file2"]["size"]>$upload_max) { //
        $DMES[] = "アップロードファイルのサイズが大きすぎます<BR>（アップロードするファイルは".floor($upload_max/1024/1000)."MB以内に調整して下さい）";
      } else {
        $filename = stripslashes($_FILES["file2"]["name"]);

        $pos_sepa = strrpos($filename, "\\");
        $pos_dot  = strrpos($filename, ".");
        if ($pos_sepa>0 || $pos_dot>0) {
          if ($pos_sepa>0) {
            $file2_orgname = substr($filename,$pos_sepa + 1);
          } else {
            $file2_orgname = $filename;
          }
          if ($pos_dot>0) {
            $file2_orgext  = substr($filename,$pos_dot + 1);
          } else {
            $file2_orgext  = "";
          }
        } else {
          $file2_orgname = $filename;
          $file2_orgext  = "";
        }
      }
      if ($file2_orgname != sjis2euc(euc2sjis($file2_orgname))) {
        $DMES[] = "添付ファイル[2]のファイル名が正しくありません<BR>（ファイル名に利用できない文字が使用されているか漢字コードの変換に失敗しました）";
      } elseif (substr($file2_orgname,0,1)==".") {
        $DMES[] = "添付ファイル[2]のファイル名が正しくありません<BR>（.[ドット]ではじまるファイル名が使用されているか、漢字コードの変換に失敗しました）";
      } else {
        $p = strrpos($file2_orgname,".");
        if ($p==0) { // 拡張子あり？
          $DMES[] = "添付ファイル[2]は拡張子が正しく指定されていません";
        }
      }

      if (sizeof($DMES)==0) {
        if ($file1_orgname != "" && $file2_orgname != "" && $file1_orgname == $file2_orgname) {
          $DMES[] = "添付ファイル[1]と[2]に同名のファイルが指定されています";
        }
      }
    }

    if (sizeof($DMES)==0 && sizeof($WMES)==0 && $check=="t") {
      $retry=0;
      while (true) {
        $seqno      = get_last("workflow","seqno","",0)+1; // seqno取得
        $user_seqno = get_last("workflow","user_seqno","user_id='$login_id'",0)+1; // seqno取得2

        // データ書込み
        $sql  = "INSERT INTO workflow (";
        $sql .= "seqno, user_id, user_seqno, flow_ids, flow_pat, result_seqno, result_sign, subject, body1, body2, body3, body4, body5, createstamp, updatestamp ";
        $sql .= ") VALUES (";
        $sql .=      $seqno    .",";
        $sql .= "'". $login_id ."',";
        $sql .=      $user_seqno .",";
        $sql .= "'". $flow_ids ."',";
        $sql .= "'". $flow_pat ."',";
        $sql .= "null,";
        $sql .= "null,";
        $sql .= "'".db_textsafe($subject)."',";
        $sql .= "'".db_textsafe($body1)  ."',";
        $sql .= "'".db_textsafe($body2)  ."',";
        $sql .= "'".db_textsafe($body3)  ."',";
        $sql .= "'".db_textsafe($body4)  ."',";
        $sql .= "'".db_textsafe($body5)  ."',";
        $sql .= "'now()',";
        $sql .= "'now()'";
        $sql .= ")";
        $res = pg_query($conn, $sql);
        if ($res != false) {
          $cnt = pg_affected_rows($res);
        } else {
          $cnt = 0;
        }

        if ($cnt==0) {
          if ($retry>10) {
            $DMES[] = "案件の登録処理に失敗しました";
            break;
          }
          $retry++;
        }

        break; // ループアウト
      }

      // 添付ファイルのコピー
      $dirno = sprintf("%08d",$seqno);
      if (!file_exists($workflowpath ."/".$dirno."/")) {
        mkdir($workflowpath ."/".$dirno."/",0755);
      }
      $ret = exec($cmd_rm." ".$workflowpath."/".$dirno."/*");

      // 一発アップロード時
      if ($_FILES["file1"]["size"]>0 && $_FILES['file1']['tmp_name']!="") {
        copy($_FILES['file1']['tmp_name'],$workflowpath."/".$dirno."/".$file1_orgname);
#        unlink($_FILES['file1']['tmp_name']);
      }
      if ($_FILES["file2"]["size"]>0 && $_FILES['file2']['tmp_name']!="") {
        copy($_FILES['file2']['tmp_name'],$workflowpath."/".$dirno."/".$file2_orgname);
#        unlink($_FILES['file2']['tmp_name']);
      }

      // 一発アップロードじゃない時
      if ($_POST["file1_size"]>0 && $_POST['file1_name']!="") {
        copy($_POST['file1'],$workflowpath."/".$dirno."/".$_POST['file1_name']);
        unlink($_POST['file1']);
      }
      if ($_POST["file2_size"]>0 && $_POST['file2_name']!="") {
        copy($_POST['file2'],$workflowpath."/".$dirno."/".$_POST['file2_name']);
        unlink($_POST['file2']);
      }
    }

    if (sizeof($DMES)>0) {
      // 入力エラー時
		  include ("../../header.inc.php");

      $pagetext .= "<BR><BR>";
      $pagetext .= "<CENTER>";
      $pagetext .= "<FONT COLOR=#FF0000>";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>";
      }
      $pagetext .= "<BR><FORM ACTION=\"./\" METHOD=POST>";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"error\" VALUE=\"t\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"subject\" VALUE=\"$subject\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"body1\" VALUE=\"$body1\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"body2\" VALUE=\"$body2\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"body3\" VALUE=\"$body3\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"body4\" VALUE=\"$body4\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"body5\" VALUE=\"$body5\">";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"flow_pat\" VALUE=\"$flow_pat\">";
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"戻る\">";
      $pagetext .= "</FORM>";
      $pagetext .= "</FONT>";
      $pagetext .= "</CENTER>";

		  include("../../detail.inc.php");
		  include("../../footer.inc.php");

    } elseif (sizeof($WMES)>0 || $check!="t") {
      // ワーニングエラー時
		  include ("../../header.inc.php");

      $pagetext .= "
<BR>
<CENTER>
";
      if (sizeof($WMES)==0) {
        $pagetext .= "内容を入力してから、登録ボタンをクリックしてください。<BR>";
      } else {
        $pagetext .= "<FONT COLOR=#FF0099>";
        while (list($key,$val)=each($WMES)) {
          $pagetext .= $val."<BR>";
        }
        $pagetext .= "</FONT>";
      }
      $pagetext .= "<BR>";

      $pagetext .= "
<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 width=480 BGCOLOR=#999999>
<FORM ACTION=\"./\" METHOD=POST ENCTYPE=\"multipart/form-data\" ONSUBMIT=\"return confirm('案件を登録しますか？\\n注：一旦登録された案件を取り消すことはできません');\">
<INPUT TYPE=HIDDEN NAME=\"MAX_FILE_SIZE\" VALUE=\"$upload_max\">
<INPUT TYPE=HIDDEN NAME=\"check\" VALUE=\"t\">

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>件名</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<INPUT TYPE=TEXT SIZE=46 NAME=\"subject\" VALUE=\"$subject\"></TD>
</TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>$title1</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<TEXTAREA NAME=\"body1\" COLS=52 ROWS=9 STYLE=\"width:380px;height:132px\">$body1</TEXTAREA>
</TD></TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>$title2</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<INPUT TYPE=TEXT NAME=\"body2\" SIZE=42 STYLE=\"width:280px\" VALUE=\"$body2\">
</TD></TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>$title3</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<INPUT TYPE=TEXT NAME=\"body3\" SIZE=25 STYLE=\"width:120px;text-align:right;ime-mode:disabled\" VALUE=\"$body3\"> 円
</TD></TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>$title4</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<TEXTAREA NAME=\"body4\" COLS=52 ROWS=2 STYLE=\"width:380px;\">$body4</TEXTAREA>
</TD></TR>

";

    $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>フロータイプ</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
";
    $pagetext .= "
<SELECT NAME=\"flow_pat\" SIZE=6 STYLE=\"width:140px\">\n";

    $sql_flow = "SELECT seqno,id,name FROM flows ORDER BY seqno";
    $res_flow = pg_query($conn,$sql_flow);
    $cnt_flow = pg_num_rows($res_flow);

    if ($cnt_flow>0) {
      for ($i=0;$i<$cnt_flow;$i++) {
        $row_flow = pg_fetch_array($res_flow,$i);
        $pagetext .= "<OPTION VALUE=\"".$row_flow["id"]."\"";
        if ($row_flow["id"]==$flow_pat) {
          $pagetext .= " SELECTED";
        }
        $pagetext .= ">";
        $pagetext .= $row_flow["name"];
        $pagetext .= "</OPTION>\n";
      }
    }

    $pagetext .= "</SELECT>
";
    $pagetext .= "
</TD></TR>

";
    if (sizeof($_FILES)==0 || ($_POST["file1_name"]=="" && $_POST["file2_name"]=="")) {
      $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=80 NOWRAP BGCOLOR=$td_back_left VALIGN=TOP>添付ファイル<BR><FONT COLOR=#666666>※2つまで</FONT></TD>
<TD ALIGN=LEFT WIDTH=400 NOWRAP BGCOLOR=$td_back>

<INPUT TYPE=FILE NAME=\"file1\" STYLE=\"width:260px\" STYLE=\"ime-mode:disabled\"><BR>
<INPUT TYPE=FILE NAME=\"file2\" STYLE=\"width:260px\" STYLE=\"ime-mode:disabled\"><BR>

</TD>
</TR>";
    } else {
      $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=80 NOWRAP BGCOLOR=$td_back_left VALIGN=TOP>添付ファイル</TD>
<TD ALIGN=LEFT WIDTH=400 NOWRAP BGCOLOR=$td_back>";

      if ($_FILES["file1"]["name"]=="" && $_FILES["file2"]["name"]!="") {
        $pagetext .= "添付ファイルなし";
      } else {
        if ($_FILES["file1"]["name"]!="") {
          $tempfilename =  tempnam($tmppath,"cur1");
          $pagetext .= "<!--";
          copy ($_FILES['file1']['tmp_name'],$tempfilename);
          $pagetext .= "-->";

          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file1_name\" VALUE=\"".$_FILES["file1"]["name"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file1_size\" VALUE=\"".$_FILES["file1"]["size"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file1_type\" VALUE=\"".$_FILES["file1"]["type"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file1\" VALUE=\"$tempfilename\">";

          $imageicon = ext_check($_FILES["file1"]["name"]);
          $pagetext .= "<IMG SRC=\"".$imageicon."\" BORDER=0 ALT=\"".$_FILES["file1"]["name"]."\" ALIGN=ABSMIDDLE WIDTH=32 HEIGHT=32 VSPACE=2 HSPACE=2>";
          $pagetext .= $_FILES["file1"]["name"];

        }

        if ($_FILES["file2"]["name"]!="") {
          $tempfilename =  tempnam($tmppath,"cur2");
          $pagetext .= "<!--";
          copy ($_FILES['file2']['tmp_name'],$tempfilename);
          $pagetext .= "-->";

          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file2_name\" VALUE=\"".$_FILES["file2"]["name"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file2_size\" VALUE=\"".$_FILES["file2"]["size"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file2_type\" VALUE=\"".$_FILES["file2"]["type"]."\">";
          $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"file2\" VALUE=\"$tempfilename\">";

          $imageicon = ext_check($_FILES["file2"]["name"]);
          $pagetext .= "<IMG SRC=\"".$imageicon."\" BORDER=0 ALT=\"".$_FILES["file2"]["name"]."\" ALIGN=ABSMIDDLE WIDTH=32 HEIGHT=32 VSPACE=2 HSPACE=2>";
          $pagetext .= $_FILES["file2"]["name"];
        }
      }
    }

    $pagetext .= "
</TD>
</TR>
</TABLE>

<BR>
<INPUT TYPE=SUBMIT VALUE=\"案件の登録\" style=\"width:140px\">
</FORM>
</CENTER>
\n";

		  include("../../detail.inc.php");
		  include("../../footer.inc.php");

    } else {
      // 正常時
     	$returl = "../";
      Header("Location: ".$returl);
    }
  }
?>