<?php

  include ("./config.inc.php");
  include ("./lib.inc.php");


?>
<TABLE WIDTH=320><TR><TD>
<BR>
指定されたページがみつかりませんでした。<BR>
<BR>
お手数ですが、このページが表示される前に行われた操作内容と、ブラウザに表示されているアドレスをコピー＆ペーストしてサポート宛にお送りください。<BR>
<BR>
<A HREF="#" ONCLICK="window.open('/support.phtml', 'SupportWin', 'directories=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=500,height=550')">サポートページ</A><BR>

<BR>
お手数おかけしますが、よろしくお願い致します。
</TD></TR></TABLE>
<?

?>
