<?
  include "../../config.inc.php";
  include "../../lib.inc.php";
  include "../../language.inc.php";

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">住所録</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>住所の登録</FONT>";
  include "../../header.inc.php";
  flush();

  // エラー判定
  if ($login==false) {
    $MES[] = "先に、ログインしてください ⇒ <A HREF=\"$toppath/\">ログインページへ</A>";
  } else {
    if (trim($login_id) == "") {
      $MES[] = "ユーザーＩＤが正しくありません";
    } else {
      $sql = "select * from users where id='".$login_id."'";
      print "<!--";
      $res = pg_query($conn, $sql);

      if (pg_num_rows($res)<1) {
        $MES[] = "ユーザーＩＤが正しくありません";
      }
      print "-->\n";
    }
  }

  // 前処理
  $corp_name   = textsafe(stripslashes($corp_name));
  $corp_kana   = textsafe(stripslashes($corp_kana));
  $corp_zip    = textsafe(stripslashes($corp_zip));
  $corp_city   = textsafe(stripslashes($corp_city));
  $corp_street = textsafe(stripslashes($corp_street));
  $corp_build  = textsafe(stripslashes($corp_build));
  $corp_tel    = textsafe(stripslashes($corp_tel));
  $corp_fax    = textsafe(stripslashes($corp_fax));
  $corp_url    = textsafe(stripslashes($corp_url));
  $corp_email  = textsafe(stripslashes($corp_email));

  $person_name     = textsafe($person_name);
  $person_kana     = mb_convert_kana(textsafe($person_kana),"CKV");
#  $person_sex
  $person_depa     = textsafe($person_depa);
  $person_post     = textsafe($person_post);
  $person_dialin   = mb_convert_kana(textsafe($person_dialin),"a");
  $person_email    = mb_convert_kana(textsafe($person_email),"a");
  $person_email2   = mb_convert_kana(textsafe($person_email2),"a");
#  $person_birthday =;
  $person_handy    = mb_convert_kana(textsafe($person_handy),"a");
  $person_zip      = mb_convert_kana(textsafe($person_zip),"a");
  $person_state    = textsafe($person_state);
  $person_city     = textsafe($person_city);
  $person_street   = textsafe($person_street);
  $person_build    = textsafe($person_build);
  $person_tel      = mb_convert_kana(textsafe($person_tel),"a");
  $person_fax      = mb_convert_kana(textsafe($person_fax),"a");

  if ($person_email == "@") { $person_email = ""; }
  if ($person_email2 == "@") { $person_email2 = ""; }

  // エラーチェック
  if ($person_name == "") {
    $MES[]="氏名が入力されていません ";
  } else {
    if (strlen($person_name)>80) {
      $MES[]="氏名が長すぎます 40文字以内(半角80文字)で指定してください";
    }
  }

  if ($person_kana != "") {
    if (strlen($person_kana)>80) {
      $MES[]="氏名のカナヨミが長すぎます 40文字以内(半角80文字)で指定してください";
    }
  }

  if ($person_depa != "") {
    if (strlen($person_depa)>120) {
      $MES[]="所属部署が長すぎます 60文字以内(半角120文字)で指定してください";
    }
  }

  if ($person_post != "") {
    if (strlen($person_post)>120) {
      $MES[]="肩書き・役職が長すぎます 60文字以内(半角120文字)で指定してください";
    }
  }

  if ($person_dialin != "") {
    if (strlen($person_dialin)>20) {
      $MES[]="内線・ダイヤルインが長すぎます 20文字以内で指定してください";
    } else {
      if (!is_tel($person_dialin)) {
        $MES[]="内線・ダイヤルインは半角数字とハイフン[-]で指定してください";
      }
    }
  }

  if ($person_email != "") {
    if (strlen($person_email)>100) {
      $MES[]="電子メール(通常)が長すぎます 100文字以内で指定してください";
    } else {
      if (!is_email($person_email)) {
        $MES[]="電子メール(通常)の指定が正しくありません";
      }
    }
  }

  if ($person_email2 != "") {
    if (strlen($person_email2)>100) {
      $MES[]="電子メール(ケータイ)が長すぎます 100文字以内で指定してください";
    } else {
      if (!is_email($person_email2)) {
        $MES[]="電子メール(ケータイ)の指定が正しくありません";
      }
    }
  }

  $person_birthday = "";
  if ($person_birthday_Y>0 && $person_birthday_M>0 && $person_birthday_D>0) {
    if (!checkdate($person_birthday_M,$person_birthday_D,$person_birthday_Y)) {
      $MES[]="生年月日の指定が正しくありません";
    } else {
      $person_birthday = $person_birthday_Y."-".$person_birthday_M."-".$person_birthday_D;
    }
  }

  if ($person_handy != "") {
    if (strlen($person_handy)>100) {
      $MES[]="携帯電話番号が長すぎます 100文字以内で指定してください";
    } else {
      if (!is_tel($person_handy)) {
        $MES[]="携帯電話番号の指定が正しくありません";
      }
    }
  }

  if ($person_zip != "") {
    if (strlen($person_zip)>8) {
      $MES[]="郵便番号が長すぎます 8文字以内で指定してください";
    }
  }

  if ($person_city != "") {
    if (strlen($person_city)>100) {
      $MES[]="住所(市区郡)が長すぎます 50文字以内(半角100文字)で指定してください";
    }
  }

  if ($person_street != "") {
    if (strlen($person_street)>100) {
      $MES[]="住所(町村・番地)が長すぎます 50文字以内(半角100文字)で指定してください";
    }
  }

  if ($person_build != "") {
    if (strlen($person_build)>100) {
      $MES[]="住所(ビル・マンション)が長すぎます 50文字以内(半角100文字)で指定してください";
    }
  }

  if ($person_tel != "") {
    if (strlen($person_tel)>80) {
      $MES[]="電話番号が長すぎます 20文字以内で指定してください";
    }
  }

  if ($person_fax != "") {
    if (strlen($person_fax)>80) {
      $MES[]="FAX番号が長すぎます 20文字以内で指定してください";
    }
  }

  // エラー無し = DBチェック
  if (sizeof($MES)==0) {
    $sql_address = "SELECT seqno,corp_name,person_name FROM address WHERE ";
    if ($corp_name != "") {
      $corp_name0 = trim(str_replace("　"," ",$corp_name));
      $corp_name1 = str_replace(" ","　",$corp_name0);
      $corp_name2 = str_replace(" "," ",$corp_name0);
      $corp_name3 = str_replace(" ","",$corp_name0);

      $sql_address .= "(corp_name='".db_textsafe($corp_name1)."' or corp_name='".db_textsafe($corp_name2)."' or corp_name='".db_textsafe($corp_name3)."') and ";
    }
    $person_name0 = trim(str_replace("　"," ",$person_name));
    $person_name1 = str_replace(" ","　",$person_name0);
    $person_name2 = str_replace(" "," ",$person_name0);
    $person_name3 = str_replace(" ","",$person_name0);
    $sql_address .= "(person_name='".db_textsafe($person_name1)."' or person_name='".db_textsafe($person_name2)."' or person_name='".db_textsafe($person_name3)."')";

    $res_address = pg_query($conn,$sql_address);
    $cnt_address = pg_num_rows($res_address);
    if ($cnt_address>0) {
      $row_address = pg_fetch_array($res_address,0);

      $TempMES = "<TABLE>";

      if ($row_address["corp_name"]!="") {
        $TempMES .= "<TR><TD>会社名:</TD><TD>".$row_address["corp_name"]."</TD></TR>\n";
      }
      $TempMES .= "<TR><TD>氏名:</TD><TD>".$row_address["person_name"]."</TD></TR>\n";
      $TempMES .= "</TABLE>";

      $WMES[] = "同じ名前の登録が見つかりました<BR>\n".$TempMES;
    }
  }

?>
<BR>

<CENTER>
<TABLE HEIGHT=445><TR><TD VALIGN=TOP ALIGN=CENTER>
<?
  // 前処理
  if (sizeof($MES)>0 || (sizeof($WMES)>0 && $errorthrou != "true")) {
    // エラーメッセージ出力
    print "<BR>";
    print "<CENTER><DIV ALIGN=CENTER>";

    if (sizeof($MES)>0) {
      print "<FONT COLOR=#FF0000><B>";
      // エラーメッセージ出力
      while (list($key,$val)=each($MES)) {
        print $val."<BR>\n";
      }
      print "</FONT>\n";
    }

    if (sizeof($WMES)>0) {
      // エラーメッセージ出力
      print "<FONT COLOR=#FF0066><B>";
      // エラーメッセージ出力
      while (list($key,$val)=each($WMES)) {
        print $val."<BR>\n";
      }
      print "</FONT></DIV></CENTER>\n";
    }

    print "<TABLE><TR>\n";

    print "<FORM NAME=\"error\" ACTION=\"./person.phtml\" METHOD=POST>\n";
    print "<TD>";

    print "<INPUT TYPE=HIDDEN name=\"corp_name\" value=\"".$corp_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_kana\" value=\"".$corp_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_zip\" value=\"".$corp_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_state\" value=\"".$corp_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_city\" value=\"".$corp_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_street\" value=\"".$corp_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_build\" value=\"".$corp_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_tel\" value=\"".$corp_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_fax\" value=\"".$corp_fax."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_url\" value=\"".$corp_url."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_email\" value=\"".$corp_email."\">\n";

    print "<INPUT TYPE=HIDDEN name=\"person_name\" value=\"".$person_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_kana\" value=\"".$person_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_sex\" value=\"".$person_sex."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_depa\" value=\"".$person_depa."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_post\" value=\"".$person_post."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_dialin\" value=\"".$person_dialin."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email\" value=\"".$person_email."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email2\" value=\"".$person_email2."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_Y\" value=\"".$person_birthday_Y."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_M\" value=\"".$person_birthday_M."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_D\" value=\"".$person_birthday_D."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_handy\" value=\"".$person_handy."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_zip\" value=\"".$person_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_state\" value=\"".$person_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_city\" value=\"".$person_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_street\" value=\"".$person_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_build\" value=\"".$person_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_tel\" value=\"".$person_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_fax\" value=\"".$person_fax."\">\n";

    print "<INPUT TYPE=SUBMIT value=\"戻る\" style=\"width:120px\">\n";
    print "</TD>\n";
    print "</FORM>\n";

    if (sizeof($MES)==0) {
    print "<FORM NAME=\"error\" ACTION=\"./other.phtml\" METHOD=POST>\n";
    print "<TD>\n";
    print "<INPUT TYPE=HIDDEN name=\"errorthrou\" value=\"true\">\n";

    print "<INPUT TYPE=HIDDEN name=\"corp_name\" value=\"".$corp_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_kana\" value=\"".$corp_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_zip\" value=\"".$corp_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_state\" value=\"".$corp_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_city\" value=\"".$corp_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_street\" value=\"".$corp_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_build\" value=\"".$corp_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_tel\" value=\"".$corp_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_fax\" value=\"".$corp_fax."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_url\" value=\"".$corp_url."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_email\" value=\"".$corp_email."\">\n";

    print "<INPUT TYPE=HIDDEN name=\"person_name\" value=\"".$person_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_kana\" value=\"".$person_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_sex\" value=\"".$person_sex."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_depa\" value=\"".$person_depa."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_post\" value=\"".$person_post."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_dialin\" value=\"".$person_dialin."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email\" value=\"".$person_email."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email2\" value=\"".$person_email2."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_Y\" value=\"".$person_birthday_Y."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_M\" value=\"".$person_birthday_M."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_D\" value=\"".$person_birthday_D."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_handy\" value=\"".$person_handy."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_zip\" value=\"".$person_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_state\" value=\"".$person_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_city\" value=\"".$person_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_street\" value=\"".$person_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_build\" value=\"".$person_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_tel\" value=\"".$person_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_fax\" value=\"".$person_fax."\">\n";

    print "<INPUT TYPE=SUBMIT value=\"続ける\" style=\"width:120px\">\n";
    print "</TD>\n";
    print "</FORM>\n";

    }
    print "</TR></TABLE>\n";

    print "</DIV></CENTER>\n";

    print "</td></tr></table>\n";
  }

  if (sizeof($MES)==0 && (sizeof($WMES)==0 || (sizeof($WMES)>0 && $errorthrou=="true"))) {
?>
<FORM NAME="other" ACTION="./add.phtml" METHOD=POST>
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=0 ALIGN=CENTER><TR><TD VALIGN=TOP ALIGN=CENTER>
<?
    // 正常処理
    print "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 BGCOLOR=#999999>\n";
?>

<INPUT TYPE=HIDDEN name="corp_name" value="<? echo $corp_name; ?>">
<INPUT TYPE=HIDDEN name="corp_kana" value="<? echo $corp_kana; ?>">
<INPUT TYPE=HIDDEN name="corp_zip" value="<? echo $corp_zip; ?>">
<INPUT TYPE=HIDDEN name="corp_state" value="<? echo $corp_state; ?>">
<INPUT TYPE=HIDDEN name="corp_city" value="<? echo $corp_city; ?>">
<INPUT TYPE=HIDDEN name="corp_street" value="<? echo $corp_street; ?>">
<INPUT TYPE=HIDDEN name="corp_build" value="<? echo $corp_build; ?>">
<INPUT TYPE=HIDDEN name="corp_tel" value="<? echo $corp_tel; ?>">
<INPUT TYPE=HIDDEN name="corp_fax" value="<? echo $corp_fax; ?>">
<INPUT TYPE=HIDDEN name="corp_url" value="<? echo $corp_url; ?>">
<INPUT TYPE=HIDDEN name="corp_email" value="<? echo $corp_email; ?>">

<INPUT TYPE=HIDDEN name="person_name" value="<? echo $person_name; ?>">
<INPUT TYPE=HIDDEN name="person_kana" value="<? echo $person_kana; ?>">
<INPUT TYPE=HIDDEN name="person_sex" value="<? echo $person_sex; ?>">
<INPUT TYPE=HIDDEN name="person_depa" value="<? echo $person_depa; ?>">
<INPUT TYPE=HIDDEN name="person_post" value="<? echo $person_post; ?>">
<INPUT TYPE=HIDDEN name="person_dialin" value="<? echo $person_dialin; ?>">
<INPUT TYPE=HIDDEN name="person_email" value="<? echo $person_email; ?>">
<INPUT TYPE=HIDDEN name="person_email2" value="<? echo $person_email2; ?>">
<INPUT TYPE=HIDDEN name="person_birthday" value="<? echo $person_birthday; ?>">
<INPUT TYPE=HIDDEN name="person_handy" value="<? echo $person_handy; ?>">
<INPUT TYPE=HIDDEN name="person_zip" value="<? echo $person_zip; ?>">
<INPUT TYPE=HIDDEN name="person_state" value="<? echo $person_state; ?>">
<INPUT TYPE=HIDDEN name="person_city" value="<? echo $person_city; ?>">
<INPUT TYPE=HIDDEN name="person_street" value="<? echo $person_street; ?>">
<INPUT TYPE=HIDDEN name="person_build" value="<? echo $person_build; ?>">
<INPUT TYPE=HIDDEN name="person_tel" value="<? echo $person_tel; ?>">
<INPUT TYPE=HIDDEN name="person_fax" value="<? echo $person_fax; ?>">

<?
    ## 分類項目
    $sql_kind = "SELECT * FROM address_kind ORDER BY seqno;";
    $res_kind = pg_query($conn,$sql_kind);
    $cnt_kind = pg_num_rows($res_kind);
    if ($cnt_kind>0) {
      print "<TR>\n";
      print "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;分類項目&nbsp;</TD>\n";
      print "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
      print "<TABLE CELLPADDING=1 CELLSPACING=0>\n";
      if ($kind_list != "") {
        $kinds = split("(,|\t)",$kind_list);
      }
      $p = 1;
      $tr_sign = false;
      for ($i=0;$i<$cnt_kind;$i++) {
        $row_kind = pg_fetch_array($res_kind,$i);
        if ($p==1) {
          print "<TR>\n";
          $tr_sign=true;
        }
        print "<TD WIDTH=33% NOWRAP>";
        print "<INPUT TYPE=CHECKBOX NAME=\"kind[]\" VALUE=\"".$row_kind["key"]."\"";
        if (sizeof($kinds)>0) {
          reset($kinds);
          while (list($key,$val)=each($kinds)) {
            if ($val==$row_kind["key"]) {
              print " checked";
              break;
            }
          }
        }
        print ">".$row_kind["value"];
        print "</TD>\n";
        if ($p==3) {
          print "</TR>\n";
          $p=1;
        } else {
          $p++;
        }
      }
      if ($tr_sign) {
        print "</TR>\n";
      }
      print "</TABLE>\n";
    }
    print "</TD>\n";
    print "</TR>\n";

    ## コメント
    print "<TR>\n";
    print "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;コメント&nbsp;</TD>\n";
    print "<TD ALIGN=LEFT BGCOLOR=$td_back>";
    print "<TEXTAREA NAME=\"comment\" COLS=42 ROWS=4 style=\"background-color:#EEEEEE;ime-mode:active\">";
    print $comment;
    print "</TEXTAREA>";
    print "</TD>\n";
    print "</TR>\n";
?>

</TD></TR></TABLE>

<CENTER><DIV ALIGN=CENTER>
<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR>
<?php
  print "<TD><INPUT TYPE=SUBMIT VALUE=\"登録\" style=\"width:120px\"></TD>\n";
  print "</FORM>\n";

  print "<FORM NAME=\"back\" ACTION=\"./person.phtml\" METHOD=POST>\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_name\" value=\"".$corp_name."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_kana\" value=\"".$corp_kana."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_zip\" value=\"".$corp_zip."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_state\" value=\"".$corp_state."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_city\" value=\"".$corp_city."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_street\" value=\"".$corp_street."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_build\" value=\"".$corp_build."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_tel\" value=\"".$corp_tel."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_fax\" value=\"".$corp_fax."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_url\" value=\"".$corp_url."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_email\" value=\"".$corp_email."\">\n";

  print "<INPUT TYPE=HIDDEN name=\"person_name\" value=\"".$person_name."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_kana\" value=\"".$person_kana."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_sex\" value=\"".$person_sex."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_depa\" value=\"".$person_depa."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_post\" value=\"".$person_post."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_dialin\" value=\"".$person_dialin."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_email\" value=\"".$person_email."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_email2\" value=\"".$person_email2."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_Y\" value=\"".$person_birthday_Y."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_M\" value=\"".$person_birthday_M."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_D\" value=\"".$person_birthday_D."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_handy\" value=\"".$person_handy."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_zip\" value=\"".$person_zip."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_state\" value=\"".$person_state."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_city\" value=\"".$person_city."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_street\" value=\"".$person_street."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_build\" value=\"".$person_build."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_tel\" value=\"".$person_tel."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_fax\" value=\"".$person_fax."\">\n";

  print "<TD>";
  print "<INPUT TYPE=SUBMIT value=\"戻る\" style=\"width:120px\">\n";
  print "</TD>";
  print "</FORM>\n";
?>
</TR></TABLE>

<TABLE WIDTH=360 ALIGN=CENTER><TR><TD>
分類項目は管理者のみが追加・変更することができます。<BR>
追加・変更は管理者に依頼してください。分類項目をうまく使いこなして顧客管理や事務処理の軽減にお役立てください。<BR>
</TD></TR></TABLE>

</DIV></CENTER>

</TD></TR></TABLE>
</CENTER>
<?
  }
  // フッタ表示
  include "../../footer.inc.php";
?>
