<?php
  include "../../config.inc.php";
  include "../../lib.inc.php";
  include "../../language.inc.php";

  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">住所録</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>住所の登録</FONT>";
  include "../../header.inc.php";
  flush();

  // エラー判定
  if ($login==false) {
    $MES[] = "先に、ログインしてください ⇒ <A HREF=\"$toppath/\">ログインページへ</A>";
  } else {
    if (trim($login_id) == "") {
      $MES[] = "ユーザーＩＤが正しくありません";
    } else {
      $sql = "select * from users where id='".$login_id."'";
      print "<!--";
      $res = pg_query($conn, $sql);

      if (pg_num_rows($res)<1) {
        $MES[] = "ユーザーＩＤが正しくありません";
      } else {
        $row = pg_fetch_array($res,0);

        $sql_secret = "select * from users where secretary_id='".$login_id."'";
        $res_secret = pg_query($conn, $sql_secret);
        $cnt_secret = pg_num_rows($res_secret);
        if ($cnt_secret>0) {
          for ($i=0;$i<$cnt_secret;$i++) {
            $row_secret = pg_fetch_array($res_secret,$i);
            $master_ids[] = $row_secret["id"];
            if ($master_checkid != "") { $master_checkid .= "|"; }
            $master_checkid .= $row_secret["id"];
          }
        }
      }
      print "-->\n";
    }
  }

  // 前処理
  $comment = trim(arrange_kana($comment));
  $kind_list = "";
  if (sizeof($kind)>0) {
    while (list($key,$val)=each($kind)) {
      if ($kind_list != "") { $kind_list .= ","; }
      $kind_list .= $val;
    }
  }
  // エラーチェック
  if ($comment != "") {
    if (strlen($comment)>1000) {
      $MES[]="コメントが長すぎます。500文字以内(半角1000文字)で指定してください";
    }
  }
?>
<BR>

<TABLE WIDTH=<? echo $tablewidth ?> HEIGHT=445><TR><TD VALIGN=TOP ALIGN=CENTER>
<?
  // 前処理
  if (sizeof($MES)>0) {
    // エラーメッセージ出力
    print "<BR>";
    print "<CENTER><DIV ALIGN=CENTER><FONT COLOR=#FF0000><B>";
    // エラーメッセージ出力
    while (list($key,$val)=each($MES)) {
      print $val."<BR>\n";
    }
    print "</FONT></DIV></CENTER>\n";

    print "<FORM NAME=\"error\" ACTION=\"./other.phtml\" METHOD=POST>\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_name\" value=\"".$corp_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_kana\" value=\"".$corp_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_zip\" value=\"".$corp_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_state\" value=\"".$corp_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_city\" value=\"".$corp_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_street\" value=\"".$corp_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_build\" value=\"".$corp_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_tel\" value=\"".$corp_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_fax\" value=\"".$corp_fax."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_url\" value=\"".$corp_url."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"corp_email\" value=\"".$corp_email."\">\n";

    print "<INPUT TYPE=HIDDEN name=\"person_name\" value=\"".$person_name."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_kana\" value=\"".$person_kana."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_sex\" value=\"".$person_sex."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_depa\" value=\"".$person_depa."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_post\" value=\"".$person_post."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_dialin\" value=\"".$person_dialin."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email\" value=\"".$person_email."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_email2\" value=\"".$person_email2."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_Y\" value=\"".$person_birthday_Y."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_M\" value=\"".$person_birthday_M."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_birthday_D\" value=\"".$person_birthday_D."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_handy\" value=\"".$person_handy."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_zip\" value=\"".$person_zip."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_state\" value=\"".$person_state."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_city\" value=\"".$person_city."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_street\" value=\"".$person_street."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_build\" value=\"".$person_build."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_tel\" value=\"".$person_tel."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"person_fax\" value=\"".$person_fax."\">\n";

    print "<INPUT TYPE=HIDDEN name=\"kind_list\" value=\"".$kind_list."\">\n";
    print "<INPUT TYPE=HIDDEN name=\"comment\" value=\"".$comment."\">\n";

    print "<INPUT TYPE=SUBMIT value=\"戻る\" style=\"width:120px\">\n";
    print "</FORM>\n";

    print "</td></tr></table>\n";
  } else {
?>
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=0 ALIGN=CENTER><TR><TD VALIGN=TOP ALIGN=CENTER>
<?
    // 正常処理
?>
<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=4 WIDTH=100% BGCOLOR=#CCCCCC>

<INPUT TYPE=HIDDEN name="corp_name" value="<? echo $corp_name; ?>">
<INPUT TYPE=HIDDEN name="corp_kana" value="<? echo $corp_kana; ?>">
<INPUT TYPE=HIDDEN name="corp_zip" value="<? echo $corp_zip; ?>">
<INPUT TYPE=HIDDEN name="corp_state" value="<? echo $corp_state; ?>">
<INPUT TYPE=HIDDEN name="corp_city" value="<? echo $corp_city; ?>">
<INPUT TYPE=HIDDEN name="corp_street" value="<? echo $corp_street; ?>">
<INPUT TYPE=HIDDEN name="corp_build" value="<? echo $corp_build; ?>">
<INPUT TYPE=HIDDEN name="corp_tel" value="<? echo $corp_tel; ?>">
<INPUT TYPE=HIDDEN name="corp_fax" value="<? echo $corp_fax; ?>">
<INPUT TYPE=HIDDEN name="corp_url" value="<? echo $corp_url; ?>">
<INPUT TYPE=HIDDEN name="corp_email" value="<? echo $corp_email; ?>">

<INPUT TYPE=HIDDEN name="person_name" value="<? echo $person_name; ?>">
<INPUT TYPE=HIDDEN name="person_kana" value="<? echo $person_kana; ?>">
<INPUT TYPE=HIDDEN name="person_sex" value="<? echo $person_sex; ?>">
<INPUT TYPE=HIDDEN name="person_depa" value="<? echo $person_depa; ?>">
<INPUT TYPE=HIDDEN name="person_post" value="<? echo $person_post; ?>">
<INPUT TYPE=HIDDEN name="person_dialin" value="<? echo $person_dialin; ?>">
<INPUT TYPE=HIDDEN name="person_email" value="<? echo $person_email; ?>">
<INPUT TYPE=HIDDEN name="person_email2" value="<? echo $person_email2; ?>">
<INPUT TYPE=HIDDEN name="person_birthday" value="<? echo $person_birthday; ?>">
<INPUT TYPE=HIDDEN name="person_handy" value="<? echo $person_handy; ?>">
<INPUT TYPE=HIDDEN name="person_zip" value="<? echo $person_zip; ?>">
<INPUT TYPE=HIDDEN name="person_state" value="<? echo $person_state; ?>">
<INPUT TYPE=HIDDEN name="person_city" value="<? echo $person_city; ?>">
<INPUT TYPE=HIDDEN name="person_street" value="<? echo $person_street; ?>">
<INPUT TYPE=HIDDEN name="person_build" value="<? echo $person_build; ?>">
<INPUT TYPE=HIDDEN name="person_tel" value="<? echo $person_tel; ?>">
<INPUT TYPE=HIDDEN name="person_fax" value="<? echo $person_fax; ?>">

<INPUT TYPE=HIDDEN name="kind_list" value="<? echo $kind_list; ?>">
<INPUT TYPE=HIDDEN name="comment" value="<? echo $comment; ?>">

<TR bgcolor="#CCCCCC">
<TD ALIGN=right width=12% nowrap VALIGN=TOP>&nbsp;表示&nbsp;</TD>
<TD ALIGN=left width=88% nowrap bgcolor=#FFFFFF>
<?
?>
</TD></TR>

<TR bgcolor="#CCCCCC">
<TD ALIGN=right width=12% nowrap VALIGN=TOP>&nbsp;編集&nbsp;</TD>
<TD ALIGN=left width=88% nowrap bgcolor=#FFFFFF>
<?
?>
</TD></TR>

</TABLE>

<CENTER><DIV ALIGN=CENTER>
<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR>
<?php
  print "<TD><INPUT TYPE=SUBMIT VALUE=\"次へ\" style=\"width:120px\"></TD>\n";
  print "</FORM>\n";

  print "<FORM NAME=\"back\" ACTION=\"./person.phtml\" METHOD=POST>\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_name\" value=\"".$corp_name."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_kana\" value=\"".$corp_kana."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_zip\" value=\"".$corp_zip."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_state\" value=\"".$corp_state."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_city\" value=\"".$corp_city."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_street\" value=\"".$corp_street."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_build\" value=\"".$corp_build."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_tel\" value=\"".$corp_tel."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_fax\" value=\"".$corp_fax."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_url\" value=\"".$corp_url."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"corp_email\" value=\"".$corp_email."\">\n";

  print "<INPUT TYPE=HIDDEN name=\"person_name\" value=\"".$person_name."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_kana\" value=\"".$person_kana."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_sex\" value=\"".$person_sex."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_depa\" value=\"".$person_depa."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_post\" value=\"".$person_post."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_dialin\" value=\"".$person_dialin."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_email\" value=\"".$person_email."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_email2\" value=\"".$person_email2."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_Y\" value=\"".$person_birthday_Y."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_M\" value=\"".$person_birthday_M."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_birthday_D\" value=\"".$person_birthday_D."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_handy\" value=\"".$person_handy."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_zip\" value=\"".$person_zip."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_state\" value=\"".$person_state."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_city\" value=\"".$person_city."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_street\" value=\"".$person_street."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_build\" value=\"".$person_build."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_tel\" value=\"".$person_tel."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"person_fax\" value=\"".$person_fax."\">\n";

  print "<INPUT TYPE=HIDDEN name=\"kind_list\" value=\"".$kind_list."\">\n";
  print "<INPUT TYPE=HIDDEN name=\"comment\" value=\"".$comment."\">\n";

  print "<TD>";
  print "<INPUT TYPE=SUBMIT value=\"戻る\" style=\"width:120px\">\n";
  print "</TD>";
  print "</FORM>\n";
?>
</TR></TABLE>

<TABLE WIDTH=360 ALIGN=CENTER><TR><TD>
権限には「表示」と「編集」の２種類があります。<BR>
それぞれ、個人・グループ単位で割り当てることが可能です。<BR>
</TD></TR></TABLE>

</DIV></CENTER>

</TD></TR></TABLE>
<?
  }
  include "../../footer.inc.php";
?>
