<?php
  include ("../../config.inc.php");
  include ("../../lib.inc.php");

  $board = $_COOKIE["board_id"];
  $kwd   = stripslashes(urldecode($_COOKIE["board_kwd"]));

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" ALT=\"トップページ\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" ALT=\"掲示板\" CLASS=\"BAR\">掲示板</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>新しい発言</FONT> ";

  // 検索機能の使用?
  $search = true;
  $searchuri = "/bulletin/";

  // ヘッダ表示
  include ("../../header.inc.php");

  if ($login && sizeof($MES)==0) {
    // 前処理
    $subject = trim(textsafe($_POST["subject"]));
    $body    = trim(textsafe($_POST["body"]));

echo $body;
    $sql_board = "SELECT * FROM boards ORDER BY seqno";
    $res_board = pg_query($conn,$sql_board);
    $cnt_board = pg_num_rows($res_board);
    if ($cnt_board==0) $DMES[] = "掲示板が作成されていません";

    $pagetext  = "";
    if (sizeof($DMES)==0) {
      $pagetext .= "<BR>\n";
      $pagetext .= "<CENTER>\n";
      $pagetext .= "タイトルと本文を入力して、投稿ボタンをクリックしてください。<BR><BR>\n";
      $pagetext .= "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 width=480 BGCOLOR=#999999>\n";
      $pagetext .= "<FORM ACTION=\"./check.phtml\" METHOD=POST>\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"".$p."\">\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"parent\" VALUE=\"".$parent."\">\n";

      ## 投稿が許可されている掲示板表示
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>掲示板</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
      $pagetext .= "<SELECT NAME=\"board\">\n";
      if ($cnt_board>0) {
        for ($i=0;$i<$cnt_board;$i++) {
          $use = false;
          $row_board = pg_fetch_array($res_board,$i);
          $manage_id  = $row_board["admin_id"];
          $boardsid   = $row_board["id"];
          $boardsname = $row_board["name"];
          $group_ids  = $row_board["view_group_ids"];
          $user_ids   = $row_board["view_user_ids"];
          if ($manage_id==$login_id || ($group_ids=="" && $user_ids=="")) {
            ## 管理者 or 掲示板管理者 or 制約のない掲示板
            $use = true;
          } else {
            if ($group_ids!="") {
              $view_group_id = split(",",$group_ids);
              if (sizeof($view_group_id)>0) while (list($seq,$id)=each($view_group_id)) {
                $chkcnt = get_count("users_entry","user_id='$login_id' AND group_id='$id'");
                if ($chkcnt>0) { $use = true; break; }
              }
            }
            if ($user_ids!="") {
              $view_user_id = split(",",$user_ids);
              if (sizeof($view_user_id)>0) while (list($seq,$id)=each($view_user_id)) {
                if ($login_id==$id) { $use = true; break; }
              }
            }
          }
          if ($use) {
            $pagetext .= "<OPTION VALUE=\"".$boardsid."\"";
            if ((empty($board) && $i==0) || (!empty($board) && $board == $boardsid)) $pagetext .= " SELECTED";
            $pagetext .= ">";
            $pagetext .= $boardsname;
            $pagetext .= "</OPTION>\n";
          }
        }
      }
      $pagetext .= "</SELECT>\n";
      $pagetext .= "</TD>\n";
      $pagetext .= "</TR>\n";

      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>タイトル</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
      $pagetext .= "<INPUT TYPE=TEXT SIZE=46 NAME=\"subject\" VALUE=\"$subject\"></TD>\n";
      $pagetext .= "</TR>\n";

      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>本文</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
      $pagetext .= "<TEXTAREA NAME=\"body\" COLS=52 ROWS=15 STYLE=\"width:380px;height:200px\">".$body."</TEXTAREA>\n";
      $pagetext .= "</TD></TR>\n";

      ## 返信通知
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>返信通知</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
      if ($replysign=="t") {
        $pagetext .= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"t\" CHECKED><FONT COLOR=#3333FF>あり</FONT>\n";
        $pagetext .= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"f\"><FONT COLOR=#FF3333>なし</FONT><BR>\n";
      } else {
        $pagetext .= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"t\"><FONT COLOR=#3333FF>あり</FONT>\n";
        $pagetext .= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"f\" CHECKED><FONT COLOR=#FF3333>なし</FONT><BR>\n";
      }
      $pagetext .= "<FONT STYLE=\"FONT-SIZE:7pt\">※ この投稿に対する返信があった場合、メールにて通知されます</FONT>";
      $pagetext .= "</TD></TR>\n";
      $pagetext .= "</TABLE>\n";

      $pagetext .= "<BR>\n";
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"発言を確認する\" STYLE=\"width:140px\">\n";
      $pagetext .= "</FORM>\n";

      $pagetext .= "</CENTER>\n";

    } else {
      // エラー時
      $pagetext .= "<BR><BR>\n";
      $pagetext .= "<CENTER>\n";
      $pagetext .= "<FONT COLOR=#FF0000>\n";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>\n";
      }
      $pagetext .= "</FONT>\n";
      $pagetext .= "<BR><FORM ACTION=\"./\" METHOD=POST>\n";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" ONCLICK=\"history.back()\">\n";
      $pagetext .= "</FORM>\n";
      $pagetext .= "</CENTER>\n";
    }
  }

  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>