<?
include "../../config.inc.php"; include "../../lib.inc.php";

$linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
$linktext .= "<A HREF=\"../../schedule/\" CLASS=\"BAR\">予定表</A> &gt; ";
if(!empty($q)) {
	$linktext .= "<FONT COLOR=#FFFF00>イベントのコピー</FONT>";
} elseif (empty($s)) {
	$linktext .= "<FONT COLOR=#FFFF00>イベントの登録</FONT>";
} else {
	$linktext .= "<FONT COLOR=#FFFF00>イベントの確認</FONT>";
}

include "../../header.inc.php";

// エラー判定
if (!$login) {
	$DMES[] = "先に、ログインしてください ⇒ <A HREF=\"$toppath/\">ログインページへ</A>";
}

// 前処理
$sql = "SELECT count(*) as allrecords FROM users";
$res = pg_query($conn, $sql);
$row = pg_fetch_array($res,0);
$user_count = $row["allrecords"];

if ($login) {
	// 登録ページからの戻り判定
	if (eregi("event\/add\/add\.phtml",$referer)){
		if (!empty($s)) {
			$updatestamp = get_first("events","updatestamp","seqno=$s",NULL);
		}
	} else {
		if ($s <> ""){
			// 編集時
			$sql = "SELECT * FROM events WHERE seqno=".$s;
			$res = pg_query($conn,$sql);
			if (pg_num_rows($res)==0) {
				$DMES[] = "指定された予定情報は既に削除されています";
			} else {
				$row = pg_fetch_array($res,0);
				$user_id = $row["user_id"];
				$sendto  = $row["shareflag"];
				$id_to   = $row["sharelist"];
				
				$title = $row["title"];
				$note = $row["note"];
				$from_stamp = date2timestamp($row["datefrom"]);
				$from_y = date("Y",$from_stamp);
				$from_m = date("m",$from_stamp);
				$from_d = date("d",$from_stamp);
				$to_stamp = date2timestamp($row["dateto"]);
				$to_y = date("Y",$to_stamp);
				$to_m = date("m",$to_stamp);
				$to_d = date("d",$to_stamp);
				if ($row["timefrom"]==""){
					$from_hour   = -1;
					$from_minuts = -1;
				} else {
					$from        = split(" ",$row["timefrom"]);
					$from_time   = split(":",$from[1]);
					$from_hour   = $from_time[0];
					$from_minuts = $from_time[1];
				}
				if ($row["timeto"]==""){
					$to_hour     = -1;
					$to_minuts   = -1;
				} else {
					$to        = split(" ",$row["timeto"]);
					$to_time   = split(":",$to[1]);
					$to_hour   = $to_time[0];
					$to_minuts = $to_time[1];
				}
				$disclosesign = $row["disclosesign"];
				$updatestamp  = $row["updatestamp"];
			}
		} else {
			$user_id = $login_id;
			if ($q <> "") {
				// コピー時
				$sql = "SELECT * FROM events WHERE seqno=".$q;
				$res = pg_query($conn,$sql);
				if (pg_num_rows($res)==0) {
					$DMES[] = "指定された予定情報は既に削除されています";
				} else {
					$row = pg_fetch_array($res,0);
					$user_id = $login_id;
					$sendto  = $row["shareflag"];
					$id_to = $row["sharelist"];
					$title = $row["title"];
					$note = $row["note"];
					$from_stamp = date2timestamp($row["datefrom"]);
					$from_y = date("Y",$from_stamp);
					$from_m = date("m",$from_stamp);
					$from_d = date("d",$from_stamp);
					$to_stamp = date2timestamp($row["dateto"]);
					$to_y = date("Y",$to_stamp);
					$to_m = date("m",$to_stamp);
					$to_d = date("d",$to_stamp);
					if ($row["timefrom"]==""){
						$from_hour   = -1;
						$from_minuts = -1;
					} else {
						$from        = split(" ",$row["timefrom"]);
						$from_time   = split(":",$from[1]);
						$from_hour   = $from_time[0];
						$from_minuts = $from_time[1];
					}
					if ($row["timeto"]==""){
						$to_hour     = -1;
						$to_minuts   = -1;
					} else {
						$to        = split(" ",$row["timeto"]);
						$to_time   = split(":",$to[1]);
						$to_hour   = $to_time[0];
						$to_minuts = $to_time[1];
					}
					$disclosesign = $row["disclosesign"];
					$updatestamp  = $row["updatestamp"];
				}
			} else {
				// 通常時
				$title = "";
				$note = "";
				$sql = "SELECT from_h,from_m,to_h,to_m FROM users WHERE id='$login_id'";
				$res = pg_query($conn,$sql);
				$row = pg_fetch_array($res,0);
				if ($row["from_h"]<>""){
					$from_hour   = $row["from_h"];
					$from_minuts = $row["from_m"];
					$to_hour     = $row["to_h"];;
					$to_minuts   = $row["to_m"];
				} else {
					$from_hour   = 9;
					$from_minuts = 0;
					$to_hour     = -1;
					$to_minuts   = -1;
				}
				if ($ey=="" or $em=="" or $ed==""){
					$from_y = date("Y",time());
					$from_m = date("m",time());
					$from_d = date("d",time());
					$to_y = date("Y",time());
					$to_m = date("m",time());
					$to_d = date("d",time());
				} else {
					$from_y = $ey;
					$from_m = $em;
					$from_d = $ed;
					$to_y = $ey;
					$to_m = $em;
					$to_d = $ed;
				}
			}
		}
	}
	if ($id_to != "") {
		$userids = split(",|\t",$id_to);
		if (sizeof($userids)>0) {
			while (list($key,$val)=each($userids)) {
				$idfind = false;
				if (sizeof($new_userids)>0) {
					while (list($new_key,$new_val)=each($new_userids)) {
						if ($new_val==$val) {
							$idfind = true;
							break;
						}
					}
				}
				if (!$idfind) {
					$sql_user = "SELECT * FROM users WHERE id='$val'";
					$res_user = pg_query($conn, $sql_user);
					$cnt_user = pg_num_rows($res_user);
					if ($cnt_user>0) {
						$row_user = pg_fetch_array($res_user,0);
						$new_userids[$row_user["seqno"]] = $val;
					}
				}
			}
		}
	}
	if (sizeof($new_userids)>0) {
		ksort($new_userids);
		reset($new_userids);
		$id_to = "";
		while (list($key,$val)=each($new_userids)) {
			if ($id_to != "") { $id_to .= ","; }
			$id_to .= $val;
		}
	}
	
	// 曜日のセット(初期表示用)
	$from_weekno = date("w",date2timestamp($from_y."-".$from_m."-".$from_d));
	$to_weekno   = date("w",date2timestamp($to_y.  "-".$to_m.  "-".$to_d));
	
	if (sizeof($DMES)==0) {
		// user名の取得
		$sql_user = "SELECT * FROM users WHERE id='".$user_id."'";
		$res_user = pg_query($conn,$sql_user);
		$cnt_user = pg_num_rows($res_user);
		if ($cnt_user==0) {
			$DMES[] = "予定情報に該当するユーザーが見つかりませんでした";
		} else {
			$row_user = pg_fetch_array($res_user,0);
			$user_name = $row_user["name_ryaku"];
		}
	}
	
	if (sizeof($DMES)>0) {
		// エラーメッセージ出力
		$pagetext .= "<TABLE WIDTH=100% HEIGHT=350 BORDER=0><TR><TD ALIGN=CENTER VALIGN=TOP>\n";
		$pagetext .= "<FORM>\n";
		$pagetext .= "<FONT COLOR=#FF0000>\n";
		while (list($key,$val)=each($DMES)) {
			$pagetext .= $val."<BR>\n";
		}
		$pagetext .= "</FONT><BR><BR>\n";
		$pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" onClick=\"history.back()\">\n";
		$pagetext .= "</FORM>\n";
		$pagetext .= "</TD></TR></TABLE>\n";
	} else {
		$pagetext .= "
<SCRIPT LANGUAGE=\"JavaScript\">
<!--
my = \"$login_id\";
dat_groups = new Array();
";
		$sql_group = "SELECT id,name FROM groups ORDER BY seqno";
		$res_group = pg_query($conn,$sql_group);
		$cnt_group = pg_num_rows($res_group);
		$pagetext .= "cnt_groups = ".$cnt_group."\n";
		if ($cnt_group>0) {
			for ($i=0;$i<$cnt_group;$i++) {
				$row_group = pg_fetch_array($res_group,$i);
				$res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
				$cnt_entry = pg_num_rows($res_entry);
				
				if ($res_entry>0) {
					$users_entry = "";
					for ($j=0;$j<$cnt_entry;$j++) {
						$row_entry = pg_fetch_array($res_entry,$j);
						if ($users_entry != "") $users_entry .= ",";
						$users_entry .= $row_entry["user_id"];
					}
				}
				if ($users_entry!="") {
					$pagetext .= "dat_groups[\"".$row_group["id"]."\"] = \"".$users_entry."\";\n";
				}
			}
		}
		
		$pagetext .= "
dat_users = new Array();
";
		$all_users = "";
		
		$sql_user = "SELECT id,name FROM users ORDER BY seqno";
		$res_user = pg_query($conn,$sql_user);
		$cnt_user = pg_num_rows($res_user);
		$pagetext .= "cnt_users = ".$cnt_user."\n";
		if ($cnt_user>0) {
			for ($i=0;$i<$cnt_user;$i++) {
				$row_user = pg_fetch_array($res_user,$i);
				$pagetext .= "dat_users[\"".$row_user["id"]."\"] = \"".$row_user["name"]."\";\n";
				if ($i!=0) $all_users .= ",";
				$all_users .= $row_user["id"];
			}
		}
		
		$pagetext .= "dat_groups[\"all\"] = \"".$all_users."\";\n";
		
		$pagetext .= "
function delwin(seqno,id,date) {
  if(confirm('このイベントを削除しますか？\\n注:一度削除したイベントを戻すことはできません。')) {
    window.location.href = '../del/?p=$p&seqno='+seqno+'&p=$p';
  }
}
function disablewin(seqno) {
  if(confirm('このイベントへの参加を辞退しますか？\\n注:一度辞退したイベントへ参加するには、担当者に参加登録を再び依頼する必要があります。')) {
    window.location.href = '../disable/?p=$p&s='+seqno;
  }
}

function changefromday(t) {
  document.images['from_weekday'].src = '/image/w-.gif';
  y = parseInt(t.from_y.value);
  m = t.from_m.options[t.from_m.selectedIndex].value;
  d = t.from_d.options[t.from_d.selectedIndex].value;
  if (!(isNaN(y)) && (y>0) && !(isNaN(m)) && (m>0) && !(isNaN(d)) && (d>0)) {
    w = new Date();
    w.setYear(y); w.setMonth(m-1); w.setDate(d);
    document.images['from_weekday'].src = '/image/w'+ w.getDay() +'.gif';

    to_y = parseInt(t.to_y.value);
    to_m = t.to_m.options[t.to_m.selectedIndex].value;
    to_d = t.to_d.options[t.to_d.selectedIndex].value;
    if (!(isNaN(to_y)) && (to_y>0) && !(isNaN(to_m)) && (to_m>0) && !(isNaN(to_d)) && (to_d>0)) {
      if ((to_y*10000 + to_m*100 + to_d) < (y*10000 + m*100 + d)) {
        t.to_y.value = y;
        t.to_m.selectedIndex = t.from_m.selectedIndex;
        t.to_d.selectedIndex = t.from_d.selectedIndex;
        changetoday(t); // 一緒に変更
      }
    }
  }
}

function changetoday(t) {
  document.images['to_weekday'].src = '/image/w-.gif';
  y = parseInt(t.to_y.value);
  m = t.to_m.options[t.to_m.selectedIndex].value;
  d = t.to_d.options[t.to_d.selectedIndex].value;
  if (!(isNaN(y)) && (y>0) && !(isNaN(m)) && (m>0) && !(isNaN(d)) && (d>0)) {
    w = new Date();
    w.setYear(y); w.setMonth(m-1); w.setDate(d);
    document.images['to_weekday'].src = '/image/w'+ w.getDay() +'.gif';
  }
}

function selectfromhour(t) {
  if (t.from_hour[0].selected) {
    t.from_minuts[0].selected = true;
  } else {
    if (t.from_minuts[0].selected == true) t.from_minuts[1].selected = true;
  }
}

function selecttohour(t) {
  if (t.to_hour[0].selected) {
    t.to_minuts[0].selected = true;
  } else {
    if (t.to_minuts[0].selected == true) t.to_minuts[1].selected = true;
  }
}

function selectGroup(t) {
  group_id = t.groups[t.groups.selectedIndex].value;
  id_tos = new Array();

  t.users.length = 0;

  if (group_id == '') {
    id_tos = dat_groups['all'].split(',');
  } else {
    if (dat_groups[group_id] != null) {
      id_tos = dat_groups[group_id].split(',');
    }
  }
  if (id_tos.length>0) {
    c = 0;
    for (i=0;i<id_tos.length;i++) {
      if (id_tos[i] != my) {
        t.users.length = t.users.length + 1;
        t.users.options[c].value = id_tos[i];
        t.users.options[c].text  = dat_users[id_tos[i]];
        c++;
      }
    }
  }
}

function clearAllUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  o.length = 0;
  t.id_to.value = '';
}

function selectAllUser(t) {
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      t.users.options[i].selected = true;
    }
  }
  t.allcheck.checked = false;
}

function addUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }
  var o = t.elements[p];

  s = t.id_to.value;
  if (t.users.length>0) {
    for (i=0;i<t.users.length;i++) {
      if (t.users.options[i].selected) {
        t.users.options[i].selected = false;
        var id = t.users.options[i].value;
        var c = false;
        for(j=0;j<o.length;j++) {
          if (o.options[j].value == id) {
            c = true;
            break;
          }
        }
        if (!c) {
          if (o.length>0) s = s + ',';
          o.length = o.length + 1;
          o.options[o.length-1].value = id;
          o.options[o.length-1].text = dat_users[id];
          s = s + id;
        }
      }
    }
  }
  t.id_to.value = s;
}

function removeUser(t) {
  for (i=0;i<t.elements.length;i++) {
    if (t.elements[i].name == \"id_tos[]\") {
      var p = i;
      break;
    }
  }

  var o = t.elements[p];

  var val = new Array();
  var txt = new Array();
  var c = 0;
  
  if (o.length>0) {
    for (i=0;i<o.length;i++) {
      if (!o.options[i].selected) {
        val[c] = o.options[i].value;
        txt[c] = o.options[i].text;
        c++;
      }
    }

    o.length = 0;
    s = '';
    if (c>0) {
      o.length = c;
      for (i=0;i<c;i++) {
        if (i>0) s = s + ',';
        o.options[i].value = val[i];
        o.options[i].text  = txt[i];
        s = s + val[i];
      }
    }
    t.id_to.value = s;
  }
}
//-->
</SCRIPT>
<BR>
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=0 ALIGN=CENTER WIDTH=420>
<FORM ACTION=\"./add.phtml\" METHOD=POST>
";
		// 正常処理
		if (empty($s)) {
			$pagetext .= "<TR><TD COLSPAN=2 ALIGN=CENTER>";
			$pagetext .= "イベントの各項目を入力してから、登録ボタンを押してください";
			$pagetext .= "</TD></TR>\n";
			$pagetext .= "<TR><TD ALIGN=RIGHT ALIGN=RIGHT>\n";
			$pagetext .= "<A HREF=\"../../schedule/add/?p=$p&ey=$ey&em=$em&ed=$ed\"><IMG SRC=\"../../image/entrysadd.gif\" WIDTH=10 HEIGHT=9 BORDER=0 ALT=\"スケジュール登録\">スケジュール登録</A>&nbsp;\n";
			$pagetext .= "</TD></TR>\n";
		}
		if (!empty($s)){
			$pagetext .= "<TR><TD ALIGN=LEFT COLSPAN=2>";
			$pagetext .= "登録者 : <A HREF=\"../../member/?id=$user_id\">$user_name</A>";
			$pagetext .= "<IMG SRC=\"../../image/clip.gif\" BORDER=0 WIDTH=10 HEIGHT=11 ALIGN=ABSMIDDLE>";
			$pagetext .= "</TD></TR>\n";
		}
		
		$pagetext .= "<TR><TD VALIGN=TOP ALIGN=CENTER COLSPAN=2>\n";
		$pagetext .= "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 WIDTH=100% BGCOLOR=#999999>\n";
		$pagetext .= "<INPUT TYPE=HIDDEN NAME=\"seqno\"   VALUE=\"$s\">\n";
		$pagetext .= "<INPUT TYPE=HIDDEN NAME=\"p\"       VALUE=\"$p\">\n";
		$pagetext .= "<INPUT TYPE=HIDDEN NAME=\"user_id\" VALUE=\"$user_id\">\n";
		## 開始日時
		$pagetext .= "<TR>\n";
		$pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;開始日時&nbsp;</TD>\n";
		$pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>";
		if ($user_id == $login_id) {
			// 開始日時【年】
			$pagetext .= "<INPUT TYPE=TEXT NAME=\"from_y\" VALUE=\"$from_y\" SIZE=5 MAXLENGTH=4 onchange=\"changefromday(this.form)\" STYLE=\"ime-mode:disabled\">年\n";
			// 開始日時【月】
			$pagetext .= "<SELECT NAME=\"from_m\" onchange=\"changefromday(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			for ($i=1;$i<=12;$i++){
				$pagetext .= "<OPTION VALUE=\"$i\"";
				if ($i == $from_m) { $pagetext .= " SELECTED "; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>月\n";
			// 開始日時【日】
			$pagetext .= "<SELECT NAME=\"from_d\" onchange=\"changefromday(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			for ($i=1;$i<=31;$i++){
				$pagetext .= "<OPTION VALUE=\"$i\"";
				if ($i == $from_d){ $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>日&nbsp;<IMG NAME=\"from_weekday\" SRC=\"/image/w$to_weekno.gif\">&nbsp;";
			// 開始日時【時】
			$pagetext .= "<SELECT NAME=\"from_hour\" ONCHANGE=\"selectfromhour(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			$pagetext .= "<OPTION VALUE=\"-1\"";
			if ($from_hour==-1){ $pagetext .= " selected "; }
			$pagetext .= ">--</OPTION>\n";
			for ($i=0;$i<=23;$i++){
				$pagetext .= "<OPTION VALUE=\"$i\"";
				if ($i == $from_hour){ $pagetext .= " selected "; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>：";
			// 開始日時【分】
			$pagetext .= "<SELECT NAME=\"from_minuts\" STYLE=\"ime-mode:disabled\">\n";
			$pagetext .= "<OPTION VALUE=\"-1\"";
			if ($from_minuts==-1){ $pagetext .= " SELECTED"; }
			$pagetext .= ">--</OPTION>\n";
			for ($i=0;$i<60;$i=$i+$interval){
				$pagetext .= "<OPTION value=\"$i\"";
				if ($i <= $from_minuts){ $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>\n";
		} else {
			$pagetext .= $from_y."年".$from_m."月".$from_d."日 ";
			if ($from_hour<0) { $pagetext .= ""; } else { $pagetext .= $from_hour."時"; }
			if ($from_minuts<0) { $pagetext .= ""; } else { $pagetext .= $from_minuts."分"; }
		}
		$pagetext .= "</TD></TR>\n";
		
		## 終了日時
		$pagetext .= "<TR>\n";
		$pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;終了日時&nbsp;</TD>\n";
		$pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>";
		if ($user_id == $login_id) {
			// 終了日時【年】
			$pagetext .= "<INPUT TYPE=TEXT NAME=\"to_y\" VALUE=\"$to_y\" SIZE=5 MAXLENGTH=4 ONCHANGE=\"changetoday(this.form)\" STYLE=\"ime-mode:disabled\">年\n";
			// 終了日時【月】
			// 月
			$pagetext .= "<SELECT NAME=\"to_m\" ONCHANGE=\"changetoday(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			for ($i=1;$i<=12;$i++){
				$pagetext .= "<OPTION VALUE=\"$i\"";
				if ($i == $to_m) { $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>月\n";
			// 終了日時【日】
			$pagetext .= "<SELECT NAME=\"to_d\" ONCHANGE=\"changetoday(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			for ($i=1;$i<=31;$i++){
				$pagetext .= "<OPTION value=\"$i\"";
				if ($i == $to_d){ $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>日&nbsp;<IMG NAME=\"to_weekday\" SRC=\"/image/w$to_weekno.gif\">&nbsp;";
			// 終了日時【時】
			$pagetext .= "<SELECT NAME=\"to_hour\" ONCHANGE=\"selecttohour(this.form)\" STYLE=\"ime-mode:disabled\">\n";
			$pagetext .= "<OPTION value=\"-1\"";
			if ($to_hour==-1){ $pagetext .= " SELECTED"; }
			$pagetext .= ">--</OPTION>\n";
			for ($i=0;$i<=23;$i++){
				$pagetext .= "<OPTION value=\"$i\"";
				if ($i == $to_hour){ $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)==1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>：";
			// 終了日時【分】
			$pagetext .= "<SELECT NAME=\"to_minuts\" STYLE=\"ime-mode:disabled\">\n";
			$pagetext .= "<OPTION value=\"-1\"";
			if ($to_minuts==-1){ $pagetext .= " SELECTED"; }
			$pagetext .= ">--</OPTION>\n";
			for ($i=0;$i<60;$i=$i+$interval){
				$pagetext .= "<OPTION value=\"$i\"";
				if ($i == $to_minuts){ $pagetext .= " SELECTED"; }
				$pagetext .= ">";
				if (strlen($i)<=1) $pagetext .= "0";
				$pagetext .= $i."</OPTION>\n";
			}
			$pagetext .= "</SELECT>\n";
		} else {
			$pagetext .= $to_y."年".$to_m."月".$to_d."日 ";
			if ($to_hour<0) { $pagetext .= ""; } else { $pagetext .= $to_hour."時"; }
			if ($to_minuts<0) { $pagetext .= ""; } else { $pagetext .= $to_minuts."分"; }
		}
		$pagetext .= "</TD></TR>\n";
		
		## タイトル
		$pagetext .= "<TR>\n";
		$pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;タイトル&nbsp;</TD>\n";
		$pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
		if ($user_id == $login_id) {
			$pagetext .= "<INPUT TYPE=TEXT NAME=\"title\" SIZE=46 VALUE=\"$title\" STYLE=\"ime-mode:active\">\n";
		} else {
			$pagetext .= $title;
		}
		$pagetext .= "</TD></TR>\n";
		
		## 内容
		$pagetext .= "<TR>\n";
		$pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;内容&nbsp;</TD>\n";
		$pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
		if ($user_id == $login_id) {
			$pagetext .= "<TEXTAREA NAME=\"note\" COLS=46 ROWS=5 STYLE=\"ime-mode:active\">".$note."</TEXTAREA>";
		} else {
			$notes = split("\r\n",str_link($note));
			while (list($key,$text)=each($notes)) {
				$pagetext .= $text;
			}
		}
		$pagetext .= "</TD></TR>\n";
		$pagetext .= "<INPUT TYPE=HIDDEN NAME=\"disclosesign\" VALUE=\"f\">\n";
		
		## 参加者関連
		$pagetext .= "<TR>\n";
		$pagetext .= "<TD ALIGN=RIGHT WIDTH=80 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>&nbsp;参加者&nbsp;</TD>\n";
		$pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
		if ($user_id == $login_id) {
			// 入力可(登録者のみ)
			// 共有選択
			$pagetext .= "
<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=2>
<TR>
<TD COLSPAN=2>&nbsp;</TD>
<TD><SELECT NAME=\"groups\" ONCHANGE=\"selectGroup(this.form)\" STYLE=\"width:120px\">\n";
			$pagetext .= "<OPTION VALUE=\"\" SELECTED>(全て)\n";
			$sql_group = "SELECT id,name FROM groups ORDER BY seqno";
			$res_group = pg_query($conn,$sql_group);
			$cnt_group = pg_num_rows($res_group);
			if ($cnt_group>0) {
				for ($i=0;$i<$cnt_group;$i++) {
					$row_group = pg_fetch_array($res_group,$i);
					$res_entry = pg_query($conn,"SELECT user_id FROM users_entry WHERE group_id='".$row_group["id"]."' AND user_id<>'$login_id'");
					if (pg_num_rows($res_entry)>0) {
						$pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\">".$row_group["name"];
						$pagetext .= "\n";
					}
				}
			}
			
			$pagetext .= "</SELECT>\n";
			$pagetext .= "</TD></TR>\n";
			
			$pagetext .= "<TR>
<TD VALIGN=TOP><SELECT NAME=\"id_tos[]\" SIZE=8 STYLE=\"width:140px\">\n";
			$id_tos = split(",",$id_to);
			
			if (sizeof($id_tos)>0) {
				for ($i=0;$i<sizeof($id_tos);$i++) {
					if ($id_tos[$i]!="") {
						$pagetext .= "<OPTION VALUE=\"".$id_tos[$i]."\">";
						$pagetext .= get_first("users","name","id='".$id_tos[$i]."'","");
						$pagetext .= "\n";
					}
				}
			}
			$pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allclear\" VALUE=\"全て消去\" ONCLICK=\"clearAllUser(this.form)\">
</TD>
<TD ALIGN=CENTER VALIGN=MIDDLE>
<INPUT TYPE=BUTTON VALUE=\"&lt; 追加\" ONCLICK=\"addUser(this.form)\"><BR><BR>
<INPUT TYPE=BUTTON VALUE=\"削除 &gt;\" ONCLICK=\"removeUser(this.form)\"><BR><BR><BR>
</TD>
<TD VALIGN=TOP><SELECT NAME=\"users\" MULTIPLE SIZE=8 STYLE=\"width:140px\">
";
			
			$sql_user = "SELECT id,depa,post,name FROM users ORDER BY seqno";
			$res_user = pg_query($conn,$sql_user);
			$cnt_user = pg_num_rows($res_user);
			
			if ($cnt_user>0) {
				for ($i=0;$i<$cnt_user;$i++) {
					$row_user = pg_fetch_array($res_user,$i);
					if ($user_id != $row_user["id"]) { //自身を除外
					$pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\" ";
					if ($send=="P" && preg_match("/(^|,)".$row_user["id"]."(,|$)/",$senddata)){
						$pagetext .= "selected";
					}
					$pagetext .= ">".$row_user["name"];
					$pagetext .= "</OPTION>\n";
					}
				}
			}
			$pagetext .= "</SELECT><BR>
<INPUT TYPE=BUTTON NAME=\"allcheck\" VALUE=\"全て選択\" ONCLICK=\"selectAllUser(this.form)\">
<INPUT TYPE=HIDDEN NAME=\"id_to\" VALUE=\"$id_to\">";
			
			
			$pagetext .= "</TD></TR></TABLE>";

			$pagetext .= "<INPUT TYPE=CHECKBOX NAME=\"sendmailusers\" VALUE=\"t\"";
			if (empty($s)) $pagetext .= " CHECKED";
			$pagetext .= "><FONT COLOR=#666666>共有者にメールで通知する<BR>\n";
			$pagetext .= "&nbsp;※<FONT STYLE=\"font-size:85%\">アドレス間違いや受信制限などメールが届かない場合はエラーメールが返ってきます</FONT><BR>";
			
		} else {
			// 入力不可
			if ($id_to != "") {
				$arr_users = split(",|\t",$id_to);
				while(list($key,$val)=each($arr_users)) {
					$sql = "select * from users where id='".$val."'";
					$res = pg_query($conn, $sql);
					$cnt = pg_num_rows($res);
					if ($cnt>0) {
						$row = pg_fetch_array($res,0);
						$pagetext .= $row["name_ryaku"];
						if ($val == $login_id) {
							$pagetext .= "&nbsp;<A HREF=\"#\" ONCLICK=\"disablewin($s)\">⇒ 参加しない</A>";
						}
						$pagetext .= "<BR>\n";
					}
				}
			}
		}
		$pagetext .= "</TD></TR>\n";
		$pagetext .= "</TABLE>\n";
		
		if (!empty($s)){
			$pagetext .= "<TR><TD ALIGN=RIGHT COLSPAN=2>";
			$pagetext .= "更新日 : ".date("Y年m月d日 H:i",datetime2timestamp($updatestamp));
			$pagetext .= "</TD></TR>\n";
		}
		
		
		## ボタン関連
		$pagetext .= "<TABLE BORDER=0 CELLPADDING=5 CELLSPACING=0 ALIGN=CENTER><TR>\n";
		if (!empty($s)){
			if ($user_id == $login_id) {
				$pagetext .= "<TD><INPUT TYPE=SUBMIT VALUE=\"更新\" STYLE=\"WIDTH:140px\"></TD>\n";
			}
			$pagetext .= "<TD><INPUT TYPE=BUTTON VALUE=\"コピー\" onClick=\"location.href='./?p=$p&q=$s&target=$target&y=$y&m=$m&d=$d'\" STYLE=\"WIDTH:70px\"></TD>\n";
			
			if ($user_id == $login_id) {
				$pagetext .= "<TD><INPUT TYPE=BUTTON VALUE=\"削除\" onclick=\"delwin('$s','$room_id','$date')\" STYLE=\"WIDTH:70px;BACKGROUND-COLOR:#FFCCCC\"></TD>\n";
			}
		} else {
			$pagetext .= "<TD><INPUT TYPE=SUBMIT VALUE=\"登録\" STYLE=\"WIDTH:140px\"></TD>\n";
		}
	}
	$pagetext .= "</TR></TABLE>\n";
	$pagetext .= "</FORM>\n";
}

include "../../detail.inc.php";
include "../../footer.inc.php";
?>
