<?
  include ("../../config.inc.php");
  include ("../../lib.inc.php");

  $kwd = stripslashes(urldecode($_COOKIE["workflow_kwd"]));

  $no   = $_REQUEST["no"];
  $body1 = textsafe($_POST["body1"]);
  $body4 = textsafe($_POST["body4"]);

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" ALT=\"トップページ\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" ALT=\"ワークフロー\" CLASS=\"BAR\">ワークフロー</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>案件の再稟議</FONT> ";

  // 検索機能の使用?
  $search = true;
  $searchuri = "/workflow/";

  // ヘッダ表示
  include ("../../header.inc.php");

#  // 機能別メニュー内容の取得
#  include ("../menu.inc.php");

  include ("../template.inc.php");

  if ($login && sizeof($MES)==0) {
    echo "<!--";
    // エラーチェック
    if (empty($no)) {
      $DMES[] = "案件が選択されていません";
    } else {
      $sql = "SELECT * FROM workflow WHERE user_id='$login_id' AND seqno=$no AND result_sign='f'";
      $res = pg_query($conn,$sql);
      $cnt = pg_num_rows($res);
      if ($cnt==0) {
        // 案件なし
        $DMES[] = "指定された案件は登録されていないか既に削除されています";
      } else {
        // 案件の取得
        $row = pg_fetch_array($res,0);

        $seqno    = $row["seqno"];
        $dirno    = strval($seqno); if (strlen($dirno)<8) $dirno = str_repeat("0",8-strlen($dirno)).$dirno;
        $user_id  = $row["user_id"];
        $user_no  = $row["user_seqno"];

        if (empty($subject1)) $subject = str_highlight($kwd,textsafe($row["subject"]));

        if (empty($body1)) $body1 = str_highlight($kwd,textsafe($row["body1"]));
        if (empty($body2)) $body2 = str_highlight($kwd,textsafe($row["body2"]));
        if (empty($body3)) $body3 = str_highlight($kwd,textsafe($row["body3"]));
        if (empty($body4)) $body4 = str_highlight($kwd,textsafe($row["body4"]));
//
        if ($user_id==$login_id) {
          $user_name = $login_name;
        } else {
          $user_name = get_first("users","name","id='$user_id'","");
        }

        $result_sign = $row["result_sign"];

        $create_datetime = date("n月j日 H:i",datetime2timestamp($row["createstamp"]));
      }
    }

    // ページ内容作成
    $pagetext  = "";
    if (sizeof($DMES)==0) {
      $pagetext .= "
<BR>
<CENTER>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 width=480 BGCOLOR=#999999>
<FORM ACTION=\"./update.phtml\" METHOD=POST ONSUBMIT=\"return confirm('登録しますか？\\n注：一旦登録された案件を取り消すことはできません');\">
<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$seqno\">
</TD>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>立案No</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
$seqno
</TD></TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>決裁事項</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
$subject
</TD></TR>

<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>".$title1."<BR><FONT COLOR=#666655>[追記]</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back NOWRAP>
<TEXTAREA NAME=\"body1\" COLS=52 ROWS=9 STYLE=\"width:380px;height:132px\">$body1</TEXTAREA>
</TD></TR>
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>".$title2."</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back NOWRAP>
$body2
</TD></TR>
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>".$title3."</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back NOWRAP>
".number_format($body3)." 円
</TD></TR>
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>".$title4."<BR><FONT COLOR=#666655>[追記]</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back NOWRAP>
<TEXTAREA NAME=\"body4\" COLS=52 ROWS=5 STYLE=\"width:380px;\">$body4</TEXTAREA>
</TD></TR>
";
      // 添付ファイル情報
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>添付ファイル</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";

      if (file_exists($workflowpath."/".$dirno)) {
        $handle = opendir($workflowpath."/".$dirno);
        while(false !== ($file = readdir($handle))){
          if(!preg_match("/^\./", $file)){
            if(is_dir($file)){
              $dirs[]  = $file;
            } else {
              $files[] = $file;
            }
          }
        }
        if (sizeof($files)==0) {
          // ファイルなし
          $pagetext .= "<FONT COLOR=#666655>なし\n";
        } else {
          // ファイルあり
          $pagetext .= "<TABLE BORDER=0><TR>\n";
          for ($i=0;$i<sizeof($files);$i++) {
            $pagetext .= "<TD ALIGN=CENTER>";
            $imageicon = ext_check($files[$i]);
            $tmpsize   = filesize($workflowpath."/".$dirno."/".$files[$i]);
            if ($tmpsize<1024) {
              $filesize = number_format($tmpsize)."Byte";
            } elseif ($tmpsize<1024000) {
              $filesize = number_format(ceil($tmpsize/1024))."KB";
            } else {
              if ($tmpsize % 1024000 == 0) {
                $filesize = number_format(floor($tmpsize/1024000))."MB";
              } else {
                $filesize = number_format(floor($tmpsize/1024000)).".".str_pad(floor(($tmpsize % 1024000)/10000),2,"00",STR_PAD_LEFT)."MB";
              }
            }
            $pagetext .= "<A HREF=\"../download/?no=$seqno&file=".urlencode($files[$i])."\">";
            $pagetext .= "<IMG SRC=\"".$imageicon."\" BORDER=0 ALT=\"".$files[$i]."\nサイズ:".$filesize."\" WIDTH=32 HEIGHT=32 VSPACE=2 HSPACE=2>";

            $pagetext .= "<BR>";
            $pagetext .= "<FONT STYLE=\"font-size:8pt\">".$files[$i];
            $pagetext .= "</FONT></A></TD>\n";
          }
          $pagetext .= "</TR></TABLE>\n";
        }
      } else {
        // ファイルなし
        $pagetext .= "<FONT COLOR=#666655>なし\n";
      }
      $pagetext .= "</TD></TR>\n";

      $pagetext .= "</TD>\n";
      $pagetext .= "</TR>\n";

      $pagetext .= "
</TABLE>

<TABLE WIDTH=480><TR><TD ALIGN=RIGHT><FONT COLOR=#555555>立案日時 : $create_datetime</TD></TR></TABLE>

<TABLE><TR>
";
#      if ($user_id != $login_id) {
#        $pagetext .= "<TD>";
#        $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"案件に返信する\" STYLE=\"width:140px\">";
#        $pagetext .= "</TD>";
#      }

      // 再稟議ボタン(自身、否認時のみ)
      if ($user_id==$login_id && $result_sign=="f") {
        $pagetext .= "<TD><INPUT TYPE=SUBMIT VALUE=\"案件の再登録\" ONCLICK=\"retry(".$no.")\" style=\"width:140px\"></TD>\n";
      }

      $pagetext .= "
</TR></FORM></TABLE>
</CENTER>
";
    } else {
      // エラー時
      $pagetext .= "<BR><BR>\n";
      $pagetext .= "<CENTER>\n";
      $pagetext .= "<FONT COLOR=#FF0000>\n";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>\n";
      }
      $pagetext .= "</FONT>\n";

      $pagetext .= "<BR><FORM>\n";
      $pagetext .= "<INPUT TYPE=BUTTON VALUE=\"戻る\" ONCLICK=\"history.back()\">\n";

      $pagetext .= "</FORM>\n";
      $pagetext .= "</CENTER>\n";
    }
    echo "-->";
  }
  
  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>